Repository openimsdk/open-im-server, pull requests merged in 2023-07, with the labels that each got.

#461 feat: adding actions
  .github/sync.yml
  .github/workflows/e2e-test.yml
  .github/workflows/link-pr.yml
  .github/workflows/opencommit.yml
  Makefile
  scripts/make-rules/golang.mk
Labels: size/L

#463 V3dev
  internal/api/route.go
  pkg/common/db/obj/minio.go
  pkg/common/db/relation/user_model.go
Labels: size/M

#465 Feat/parameter check
  pkg/proto/auth/auth.go
  pkg/proto/conversation/conversation.go
  pkg/proto/friend/friend.go
  pkg/proto/friend/validate.go
  pkg/proto/group/group.go
  pkg/proto/msg/msg.go
  pkg/proto/msggateway/msggateway.go
  pkg/proto/push/push.go
  pkg/proto/sdkws/sdkws.go
  pkg/proto/third/third.go
  pkg/proto/user/user.go
Labels: size/XXL

#467 add tx_oss cos
  config/config.yaml
  go.mod
  go.sum
  internal/rpc/third/third.go
  pkg/common/db/obj/obj.go
  pkg/common/db/obj/tx_oss.go
Labels: size/L

#471 Docker compose bug
  docker-compose.yaml
Labels: size/S

#490 feat: add the changelog
  docker-compose.yaml
Labels: size/XS

#492 fix: docker file path
  Dockerfile
Labels: size/XS

#495 fix: docker file path
  docker-compose.yaml
  pkg/common/cmd/root.go
  scripts/check_all.sh
  scripts/docker_start_all.sh
  scripts/msg_gateway_start.sh
  scripts/msg_transfer_start.sh
  scripts/path_info.sh
  scripts/start_all.sh
  scripts/start_rpc_service.sh
  scripts/stop_all.sh
Labels: size/M

#482 Update .gitignore
  .gitignore
Labels: size/XS

#493 Add database retry
  pkg/common/db/relation/mysql_init.go
Labels: size/M

#497 feat: add logic to deploy images
  .github/workflows/golangci-link.yml
  .github/workflows/openim-ci.yml
  .github/workflows/scripts-test.yml
  .github/workflows/sync.yml
  README.md
  assets/README.md
  assets/intive-slack.png
  assets/logo-gif/LICENSE
  assets/logo-gif/openim-logo.gif
  assets/logo/LICENSE
  assets/logo/openim-logo-blue.png
  assets/logo/openim-logo-cyan.png
  assets/logo/openim-logo-gradient.png
  assets/logo/openim-logo-green.png
  assets/logo/openim-logo-orange.png
  assets/logo/openim-logo-purple.png
  assets/logo/openim-logo-red.png
  assets/logo/openim-logo-yellow.png
  assets/logo/openim-logo.png
  go.mod
  go.sum
  install_im_server.sh
  internal/msgtransfer/persistent_msg_handler.go
  pkg/common/db/relation/mysql_init.go
  pkg/common/kafka/consumer_group.go
  pkg/utils/strings.go
  pkg/utils/time_format.go
  scripts/build_all_service.sh
  scripts/path_info.sh
  scripts/style_info.sh
Labels: size/L

#469 chore: use fmt.Errorf(...) instead of errors.New(fmt.Sprintf(...))
  pkg/common/db/unrelation/extend_msg.go
Labels: size/XS

#500 For "add database retry" add test
  pkg/common/db/relation/mysql_init.go
  pkg/common/db/relation/mysql_init_test.go
Labels: size/M

#501 fix: fix start scripts
  .github/workflows/scripts-test.yml
  assets/logo-gif/openim-logo.gif
  assets/openim-logo-gradient.pdf
  assets/openim-logo-gradient.svg
  assets/openim-logo-green.pdf
  assets/openim-logo-green.svg
Labels: size/S

#507 Delete .idea directory
  .idea/Open-IM-Server.iml
  .idea/dataSources.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
Labels: size/XS

#509 fix: remove some structs
  internal/rpc/msg/revoke.go
  pkg/common/db/relation/mysql_init_test.go
  pkg/proto/conversation/conversation.go
  pkg/proto/msg/msg.go
  pkg/proto/third/third.go
Labels: size/L

#525 feat: add scripts
  .github/workflows/release.yml
  CHANGELOG/CHANGELOG.md
  config/config.yaml
  docker-compose.yaml
  internal/api/third.go
  internal/msggateway/client.go
  internal/msgtransfer/init.go
  internal/push/push_to_client.go
  internal/rpc/conversation/conversaion.go
  internal/rpc/group/db_map.go
  internal/rpc/group/group.go
  internal/rpc/group/statistics.go
  internal/rpc/msg/server.go
  internal/rpc/msg/statistics.go
  internal/rpc/third/s3.go
  internal/rpc/third/third.go
  internal/rpc/third/tool.go
  internal/rpc/user/user.go
  internal/tools/conversation.go
  internal/tools/cron_task.go
  internal/tools/msg.go
  pkg/apistruct/msg.go
  pkg/common/cmd/rpc.go
  pkg/common/db/controller/conversation.go
  pkg/common/db/controller/group.go
  pkg/common/db/controller/msg.go
  pkg/common/db/controller/s3.go
  pkg/common/db/relation/conversation_model.go
  pkg/common/db/relation/group_model.go
  pkg/common/db/relation/object_model.go
  pkg/common/db/s3/cont/controller.go
  pkg/common/db/s3/cont/error.go
  pkg/common/db/s3/cos/cos.go
  pkg/common/db/s3/minio/minio.go
  pkg/common/db/s3/oss/oss.go
  pkg/common/db/s3/oss/sign.go
  pkg/common/db/s3/s3.go
  pkg/common/db/table/relation/conversation.go
  pkg/common/db/table/unrelation/msg.go
  pkg/common/db/unrelation/msg.go
  pkg/common/log/sql_logger.go
  pkg/discoveryregistry/zookeeper/discover.go
  pkg/proto/msg/msg.pb.go
  pkg/rpcclient/conversation.go
  pkg/rpcclient/msg.go
  pkg/rpcclient/notification/group.go
  pkg/rpcclient/notification/msg.go
  scripts/build_all_service.sh
  scripts/enterprise/check_all.sh
  scripts/githooks/pre-commit
  scripts/githooks/pre-push
  scripts/msg_gateway_start.sh
  scripts/msg_transfer_start.sh
  scripts/path_info.sh
  scripts/start_all.sh
  scripts/start_rpc_service.sh
Labels: size/XXL

#518 add MongoDB,Redis,Kafka retry mechanism
  .gitignore
  config/config.yaml
  pkg/common/db/cache/init_redis.go
  pkg/common/db/cache/init_redis_test.go
  pkg/common/db/unrelation/mongo.go
  pkg/common/http/http_client.go
  pkg/common/kafka/producer.go
  pkg/common/mw/gin.go
Labels: size/L

#533 all back-office api
  internal/api/group.go
  internal/api/msg.go
  internal/api/route.go
  internal/api/third.go
  internal/msgtransfer/init.go
  internal/rpc/msg/revoke.go
  internal/rpc/msg/server.go
  internal/rpc/msg/sync_msg.go
  internal/tools/msg.go
  pkg/common/db/controller/msg.go
  pkg/common/db/relation/group_model.go
  pkg/common/db/table/unrelation/msg.go
  pkg/common/db/unrelation/msg.go
  pkg/proto/auth/auth.pb.go
  pkg/proto/conversation/conversation.pb.go
  pkg/proto/errinfo/errinfo.pb.go
  pkg/proto/friend/friend.pb.go
  pkg/proto/group/group.pb.go
  pkg/proto/msg/msg.pb.go
  pkg/proto/msg/msg.proto
  pkg/proto/msggateway/msggateway.pb.go
  pkg/proto/push/push.pb.go
  pkg/proto/sdkws/sdkws.pb.go
  pkg/proto/statistics/statistics.pb.go
  pkg/proto/third/third.pb.go
  pkg/proto/user/user.pb.go
  pkg/proto/wrapperspb/wrapperspb.pb.go
  pkg/rpcclient/msg.go
  pkg/rpcclient/third.go
Labels: size/XL

#534 fix bug: friend, args error
  internal/rpc/friend/friend.go
  pkg/common/constant/constant.go
  pkg/common/convert/black.go
  pkg/common/convert/friend.go
  pkg/common/db/controller/friend.go
  pkg/proto/group/group.go
  pkg/proto/msg/msg.go
Labels: size/M

#537 fix: conflict resolve main
  config/config.yaml
  internal/msgtransfer/init.go
  internal/push/push_to_client.go
  internal/rpc/conversation/conversaion.go
  internal/rpc/group/group.go
  internal/rpc/group/statistics.go
  internal/rpc/msg/statistics.go
  internal/rpc/third/s3.go
  internal/rpc/third/third.go
  internal/rpc/third/tool.go
  internal/rpc/user/user.go
  internal/tools/conversation.go
  internal/tools/cron_task.go
  internal/tools/msg.go
  pkg/common/db/controller/conversation.go
  pkg/common/db/controller/group.go
  pkg/common/db/controller/msg.go
  pkg/common/db/controller/s3.go
  pkg/common/db/relation/group_model.go
  pkg/common/db/s3/cont/controller.go
  pkg/common/db/s3/cont/error.go
  pkg/common/db/s3/cos/cos.go
  pkg/common/db/s3/minio/minio.go
  pkg/common/db/s3/oss/oss.go
  pkg/common/db/s3/oss/sign.go
  pkg/common/db/s3/s3.go
  pkg/common/db/table/relation/conversation.go
  pkg/common/log/sql_logger.go
  pkg/discoveryregistry/zookeeper/discover.go
  pkg/proto/auth/auth.pb.go
  pkg/proto/conversation/conversation.pb.go
  pkg/proto/errinfo/errinfo.pb.go
  pkg/proto/friend/friend.pb.go
  pkg/proto/group/group.pb.go
  pkg/proto/msg/msg.pb.go
  pkg/proto/msggateway/msggateway.pb.go
  pkg/proto/push/push.pb.go
  pkg/proto/sdkws/sdkws.pb.go
  pkg/proto/statistics/statistics.pb.go
  pkg/proto/third/third.pb.go
  pkg/proto/user/user.pb.go
  pkg/proto/wrapperspb/wrapperspb.pb.go
  pkg/rpcclient/conversation.go
  pkg/rpcclient/msg.go
  pkg/rpcclient/notification/group.go
  pkg/rpcclient/notification/msg.go
  pkg/rpcclient/third.go
Labels: size/XXL

#538 fix: minio auto make bucket
  pkg/common/db/s3/minio/minio.go
Labels: size/XS

#539 url to uri
  pkg/common/db/unrelation/mongo.go
Labels: size/S

#542 Fix/v3 error
  .gitignore
  cmd/openim-api/main.go
  config/config.yaml
  internal/msgtransfer/init.go
  internal/rpc/msg/server.go
  internal/tools/msg.go
  pkg/common/cmd/rpc.go
  pkg/common/db/controller/msg.go
  pkg/common/db/relation/group_model.go
  pkg/proto/auth/auth.pb.go
  pkg/proto/conversation/conversation.pb.go
  pkg/proto/errinfo/errinfo.pb.go
  pkg/proto/friend/friend.pb.go
  pkg/proto/group/group.pb.go
  pkg/proto/msg/msg.pb.go
  pkg/proto/msggateway/msggateway.pb.go
  pkg/proto/push/push.pb.go
  pkg/proto/sdkws/sdkws.pb.go
  pkg/proto/statistics/statistics.pb.go
  pkg/proto/third/third.pb.go
  pkg/proto/user/user.pb.go
  pkg/proto/wrapperspb/wrapperspb.pb.go
  pkg/rpcclient/msg.go
  pkg/rpcclient/third.go
Labels: size/L

#543 fix conflict
  cmd/openim-api/main.go
  config/config.yaml
  pkg/common/cmd/rpc.go
Labels: size/XS

#546 fix: rpc mw mismatch key
  pkg/common/mw/check.go
  pkg/common/mw/check_test.go
  pkg/common/mw/rpc_client_interceptor.go
  pkg/common/mw/rpc_server_interceptor.go
Labels: size/L

#547 fix bug: log path and user rpc
  cmd/openim-api/main.go
  config/config.yaml
  internal/api/msg.go
  internal/api/route.go
  internal/api/third.go
  internal/rpc/msg/as_read.go
  internal/rpc/msg/revoke.go
  pkg/proto/msg/msg.pb.go
  pkg/proto/msg/msg.proto
  pkg/rpcclient/conversation.go
  pkg/rpcclient/msg.go
Labels: size/L

#552 fix: scripts and release
  .github/workflows/scripts-test.yml
  docker-compose.yaml
  scripts/msg_transfer_start.sh
  scripts/start_all.sh
Labels: size/M

#560 new feature: add batch send msg
  internal/api/auth.go
  internal/api/conversation.go
  internal/api/friend.go
  internal/api/group.go
  internal/api/msg.go
  internal/api/route.go
  internal/api/statistics.go
  internal/api/third.go
  internal/api/user.go
  internal/rpc/user/user.go
  pkg/apistruct/auth.go
  pkg/apistruct/aws.go
  pkg/apistruct/conversation.go
  pkg/apistruct/cos.go
  pkg/apistruct/friend.go
  pkg/apistruct/group.go
  pkg/apistruct/manage.go
  pkg/apistruct/msg.go
  pkg/apistruct/oss.go
  pkg/apistruct/pagination.go
  pkg/apistruct/public.go
  pkg/apistruct/super_group.go
  pkg/apistruct/third.go
  pkg/common/db/controller/user.go
  pkg/common/db/relation/user_model.go
  pkg/common/db/table/relation/user.go
  pkg/rpcclient/user.go
Labels: size/XXL

#562 fix get groups bug
  internal/api/msg.go
  internal/msgtransfer/init.go
  internal/rpc/msg/send.go
  internal/rpc/msg/server.go
  internal/rpc/msg/sync_msg.go
  internal/tools/msg.go
  pkg/common/constant/constant.go
  pkg/common/db/controller/chatlog.go
  pkg/common/db/controller/msg.go
  pkg/common/db/relation/chat_log_model.go
  pkg/common/db/table/relation/chatlog.go
  pkg/common/db/unrelation/msg.go
  pkg/proto/group/group.go
  pkg/proto/msg/msg.pb.go
  pkg/proto/msg/msg.proto
Labels: size/L

#555 fix bug #545
  go.mod
  internal/push/offlinepush/offlinepush_interface.go
Labels: size/XS

#565 message for your changes
  build.cmd
  internal/rpc/msg/server.go
  pkg/common/db/controller/msg.go
Labels: size/S

#566 debug
  build.cmd
  internal/rpc/msg/sync_msg.go
  pkg/common/db/controller/msg.go
  pkg/common/db/table/unrelation/msg.go
  pkg/common/db/unrelation/msg.go
Labels: size/M

#568 fix bug: multiple gateway kick user
  internal/api/msg.go
  internal/msggateway/hub_server.go
  internal/msggateway/n_ws_server.go
  internal/rpc/auth/auth.go
  internal/tools/cron_task.go
  pkg/proto/msg/msg.go
Labels: size/M

#569 fix: implement of GetUsersOnlineStatus (#567)
  internal/api/user.go
  internal/msggateway/hub_server.go
  pkg/common/db/cache/conversation.go
Labels: size/S

#580 fix: s3 browser preview #579
  config/config.yaml
  pkg/common/db/controller/s3.go
  pkg/common/db/s3/cos/cos.go
  pkg/common/db/s3/minio/minio.go
  pkg/common/db/s3/oss/oss.go
  pkg/common/db/s3/s3.go
Labels: size/M

#584 fix: user app_manger_level#581
  internal/rpc/user/user.go
  pkg/common/db/table/relation/user.go
Labels: size/XS

#596 fix: msg destruct not effect and notification self 2 self push twice
  internal/push/push_handler.go
  internal/rpc/msg/server.go
  internal/rpc/msg/sync_msg.go
  internal/tools/conversation.go
  internal/tools/cron_task.go
  pkg/common/db/controller/msg.go
  pkg/common/db/relation/conversation_model.go
  pkg/common/locker/message_locker.go
  pkg/rpcclient/msg.go
  pkg/rpcclient/notification/msg.go
  pkg/utils/utils.go
Labels: size/M

#604 fix: init grpc conn multiple in one process will cause zero address when rpc is called
  pkg/discoveryregistry/zookeeper/discover.go
  pkg/discoveryregistry/zookeeper/register.go
  pkg/discoveryregistry/zookeeper/resolver.go
  pkg/discoveryregistry/zookeeper/zk.go
  pkg/proto/friend/friend.go
Labels: size/M

#561 fix: delete batch build all file
  .env
  .github/workflows/auto-release.yml
  .github/workflows/bot-auto-cherry-pick.yml
  .github/workflows/bot-cherry-pick.yml
  .github/workflows/build-docker-image.yml
  .github/workflows/cla.yml
  .github/workflows/deploy.yml
  .github/workflows/depsreview.yaml
  .github/workflows/e2e-test.yml
  .github/workflows/golangci-link.yml
  .github/workflows/gosec.yml
  .github/workflows/image.yml
  .github/workflows/lock-issue.yml
  .github/workflows/opencommit.yml
  .github/workflows/openim-ci.yml
  .github/workflows/openimci.yml
  .github/workflows/project-progress.yml
  .github/workflows/release.yml
  .github/workflows/scripts-test.yml
  .gitignore
  .goreleaser.yaml
  Makefile
  README.md
  assets/logo-gif/openim-logo.gif
  config/config.yaml
  golangci.yaml
  init_docker.sh
  install_im_compose.sh
  install_im_server.sh
  pkg/common/db/controller/user.go
  pkg/common/db/relation/user_model.go
  scripts/batch_build_all_service.sh
  scripts/docker_check_service.sh
  scripts/env_check.sh
  scripts/init_pwd.sh
  scripts/install_im_compose.sh
  scripts/install_im_server.sh
  scripts/make-rules/golang.mk
  scripts/make-rules/image.mk
  scripts/make-rules/tools.mk
  scripts/push_start.sh
  test/common.sh
Labels: size/XXL

#630 fix: Compatible with wasm s3 oss header Date
  pkg/common/db/s3/oss/oss.go
Labels: size/XS

#628 fix bug: grpc options duplicated when send msg
  pkg/discoveryregistry/zookeeper/discover.go
Labels: size/XS

#592 fix bug: obtain user online status err(#567)
  internal/api/user.go
  internal/msggateway/hub_server.go
Labels: size/S

#632 docs: fix lint update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/XS

#638 fix: actions milestones auto
  .github/workflows/auto-assign-issue.yml
  .github/workflows/help-comment-issue.yml
Labels: size/S

#640 fix: actions milestones auto
  .github/sync.yml
  .github/workflows/auto-assign-issue.yml
  .github/workflows/auto-release.yml
  .github/workflows/cla.yml
  .github/workflows/project-progress.yml
Labels: size/M

#646 fix: StringValue json serialization problem
  pkg/proto/wrapperspb/wrapperspb.go
Labels: size/XS

#642 fix: actions milestones auto
  .github/sync.yml
  .github/workflows/auto-gh-pr.yml
  .github/workflows/auto-release.yml
  .github/workflows/check-coverage.yml
  .github/workflows/cla.yml
  .github/workflows/e2e-test.yml
  .github/workflows/openimci.yml
  .github/workflows/project-progress.yml
  .github/workflows/pull-request.yml
  .golangci.yml
  docs/CODEOWNERS
  internal/api/msg.go
  internal/msggateway/hub_server.go
  internal/push/offlinepush/offlinepush_interface.go
  internal/rpc/msg/send.go
  scripts/build.cmd
  scripts/githooks/commit-msg
  scripts/githooks/pre-commit
  scripts/start_all.sh
Labels: enhancement, good first issue, kind/feature, size/L

#648 feat: add file:
  .github/workflows/auto-release.yml
  .github/workflows/link-pr.yml
Labels: size/S

#650 feat: add file:
  .github/workflows/auto-assign-issue.yml
  .github/workflows/auto-release.yml
Labels: size/M

#659 fix: http redirect compatibility
  internal/api/third.go
Labels: size/XS

#657 feat: add test format
  .github/.codecov.yml
  .github/labels.yml
  .github/sync.yml
  .github/weekly-digest.yml
  .github/workflows/auto-assign-issue.yml
  .github/workflows/auto-gh-pr.yml
  .github/workflows/auto-invite.yml
  .github/workflows/bot-auto-cherry-pick.yml
  .github/workflows/bot-cherry-pick.yml
  .github/workflows/build-docker-image.yml
  .github/workflows/check-coverage.yml
  .github/workflows/cla.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/create_branch_on_tag.yml
  .github/workflows/deploy.yml
  .github/workflows/e2e-test.yml
  .github/workflows/gosec.yml
  .github/workflows/help-comment-issue.yml
  .github/workflows/issue-robot.yml
  .github/workflows/link-pr.yml
  .github/workflows/lock-issue.yml
  .github/workflows/opencommit.yml
  .github/workflows/openimci.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
  .github/workflows/scripts-test.yml
  .github/workflows/stale.yml
  .goreleaser.yaml
  CHANGELOG/CHANGELOG.md
  README.md
  build/docker/openim-api/Dockerfile
  build/docker/openim-cmdutils/Dockerfile
  build/docker/openim-crontask/Dockerfile
  build/docker/openim-msggateway/Dockerfile
  build/docker/openim-msgtransfer/Dockerfile
  build/docker/openim-push/Dockerfile
  build/docker/openim-rpc-auth/Dockerfile
  build/docker/openim-rpc-conversation/Dockerfile
  build/docker/openim-rpc-friend/Dockerfile
  build/docker/openim-rpc-group/Dockerfile
  build/docker/openim-rpc-msg/Dockerfile
  build/docker/openim-rpc-third/Dockerfile
  build/docker/openim-rpc-user/Dockerfile
  config/config.yaml
  docs/conversions/README.md
  docs/conversions/api.md
  docs/conversions/commit.md
  docs/conversions/directory.md
  docs/conversions/error_code.md
  docs/conversions/go_code.md
  docs/conversions/logging.md
  docs/conversions/version.md
  scripts/make-rules/common.mk
  scripts/make-rules/golang.mk
Labels: size/XXL

#669 Update README.md
  README.md
Labels: size/S

#670 docs: update CODEOWNERS
  docs/CODEOWNERS
Labels: size/XS

#673 docs: update README.md install
  README.md
Labels: size/M

#679 feat: add openim log
  .goreleaser.yaml
  Makefile
  config/config.yaml
  install.sh
  scripts/advertise.sh
  scripts/make-rules/copyright.mk
  scripts/make-rules/golang.mk
  scripts/style_info.sh
Labels: size/XL

#678 fix: sql injection risk
  go.mod
  go.sum
Labels: size/XS

#668 new feat: sync designated model data
  internal/api/friend.go
  internal/api/group.go
  internal/api/route.go
  internal/rpc/conversation/conversaion.go
  internal/rpc/friend/friend.go
  internal/rpc/group/group.go
  internal/rpc/user/user.go
  pkg/apistruct/manage.go
  pkg/common/db/controller/friend.go
  pkg/common/db/controller/group.go
  pkg/common/db/relation/friend_request_model.go
  pkg/common/db/relation/group_request_model.go
  pkg/common/db/table/relation/friend_request.go
  pkg/common/db/table/relation/group_request.go
  pkg/rpcclient/notification/conevrsation.go
Labels: size/L

#680 feat: config env optimize
  .env
  config/config.yaml
  install.sh
Labels: size/L

#683 feat: config env optimize
  config/config.yaml
  scripts/README.md
Labels: size/M

#684 Resolving code conflicts after project directory changes and Add user subscription to the operation from rpc to db layer
  go.mod
  go.sum
  internal/api/route.go
  internal/api/user.go
  internal/rpc/user/user.go
  internal/tools/msg.go
  pkg/common/db/controller/user.go
  pkg/common/db/table/unrelation/user.go
  pkg/common/db/unrelation/user.go
Labels: size/L

#691 docs: add readme docs
  .github/workflows/build-docker-image.yml
  .github/workflows/deploy.yml
  .goreleaser.yaml
  Dockerfile
  docs/conversions/images.md
  docs/conversions/version.md
  internal/rpc/group/group.go
Labels: size/L

#692 fix: docker file fix
  Dockerfile
Labels: size/XS

#693 Get user online status
  internal/api/route.go
  internal/api/user.go
  internal/rpc/user/user.go
  pkg/common/db/cache/user.go
  pkg/common/db/controller/user.go
Labels: size/L

#695 Dev2
  .github/workflows/build-docker-image.yml
  .goreleaser.yaml
  Dockerfile
  config/config.yaml
  docs/conversions/images.md
  go.mod
  go.sum
  internal/api/route.go
  internal/api/user.go
  internal/rpc/group/group.go
  internal/rpc/user/user.go
  internal/tools/msg.go
  pkg/common/db/cache/user.go
  pkg/common/db/controller/group.go
  pkg/common/db/controller/user.go
  pkg/common/db/relation/group_model.go
  pkg/common/db/table/relation/group.go
  pkg/common/db/table/unrelation/user.go
  pkg/common/db/unrelation/user.go
Labels: size/XL

#697 fix bug: join group failed
  .github/workflows/build-docker-image.yml
Labels: size/XS

#698 fix bug: When the previously applied group has a disbanded group, applying to add the group again will fail
  internal/rpc/group/group.go
  pkg/common/db/controller/group.go
  pkg/common/db/relation/group_model.go
  pkg/common/db/table/relation/group.go
Labels: kind/bug, size/S

#701 fix: docker images
  .env
  Dockerfile
  docker-compose.yaml
  scripts/make-rules/golang.mk
Labels: size/S

#700 fix: get userid function call rpc and message gateway add status change callback
  go.mod
  go.sum
  internal/api/user.go
  internal/msggateway/n_ws_server.go
  pkg/rpcclient/user.go
Labels: size/M

#699 fix: get userid function call rpc and message gateway add status change callback
  go.mod
  go.sum
  internal/api/user.go
  internal/msggateway/n_ws_server.go
  pkg/rpcclient/user.go
Labels: size/M

#702 Fix/dockerfile
  .env
  Dockerfile
  scripts/make-rules/golang.mk
Labels: size/S

#703 Update version.md
  docs/conversions/version.md
Labels: size/XS

#704 Update version.md
  docs/conversions/version.md
Labels: size/S

#705 docs: update create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: size/L

#707 Update docker-compose.yaml
  docker-compose.yaml
Labels: size/XS

#708 Create dependabot.yml
  .github/dependabot.yml
Labels: size/S

#710 Update golang.mk
  scripts/make-rules/golang.mk
Labels: size/S

#718 docs: more about docker image install
  docs/conversions/images.md
Labels: kind/documentation, size/M

#719 docs: update the document directory
  docs/conversions/README.md
Labels: kind/documentation, size/S

#722 Dev2
  internal/api/msg.go
Labels: size/XS

#725 fix bug: /msg/batch_send_msg isSendAll param not effect send msg to all user
  internal/api/msg.go
Labels: size/XS

#726 Docs: Update README.md
  README.md
Labels: size/XS

#734 feat: add get_group_member_user_id api
  internal/api/group.go
  internal/api/route.go
Labels: size/XS

#735 docs: update readme version
  docs/conversions/version.md
Labels: size/S
