Repository openimsdk/open-im-server, pull requests merged in 2023-09, with the labels that each got.

#991 fix: repeated modification session notification
  internal/rpc/conversation/conversaion.go
Labels: size/M

#992 chore: optimize modification and send notifications
  internal/rpc/conversation/conversaion.go
Labels: size/XS

#994 fix: repeated modification session notification
  internal/rpc/conversation/conversaion.go
Labels: size/M

#1005 fix: jpush return a nil pointer panic
  internal/push/push_to_client.go
Labels: size/XS

#1012 fix: go work update go.work
  go.work
Labels: size/XS

#1015 fix: user offline push
  internal/push/push_to_client.go
Labels: size/S

#1017 docs: update openim readme
  README.md
Labels: size/XS

#1016 feat: update demo scripts
  scripts/demo.sh
Labels: size/M

#1029 fix(release-v3.2)-docker compose fix port and host
  docker-compose.yaml
Labels: size/XS

#1032 fix: v3.2 update docker-compose.yaml
  docker-compose.yaml
Labels: size/XS

#1033 fix: openim-server Mirrored the pull
  docker-compose.yaml
Labels: size/XS

#1019 fix: push redis pkg
  internal/api/msg.go
  internal/push/offlinepush/getui/push.go
Labels: size/S

#1027 feat: remove redundant read deadline in gateway
  internal/msggateway/client.go
Labels: size/XS

#1048 fix: openim logs release v3.3
  docker-compose.yml
Labels: size/XS

#1051 fix: set openim volume
  .github/workflows/build-openim-web-image.yml
  CHANGELOG/CHANGELOG.md
  Dockerfile
  docker-compose.yml
  scripts/install/openim-push.sh
Labels: size/L

#1052 fix: openim logs release v3.3 (#1048)
  docker-compose.yml
Labels: size/L

#1056 fix: openim logs release v3.3 (#1048)
  .github/workflows/build-openim-web-image.yml
  .github/workflows/openimci.yml
  README.md
  config/config.yaml
  deployments/openim-chat/LICENSE
  deployments/openim-server/Chart.yaml
  deployments/openim-server/LICENSE
  deployments/openim-server/README.md
  docker-compose.yml
  scripts/demo.sh
  scripts/install-im-server.sh
Labels: size/XL

#1054 feat: choose whether to push group messages offline based on the user's session option settings
  go.mod
  go.sum
  internal/api/conversation.go
  internal/api/route.go
  internal/push/push_to_client.go
  internal/rpc/conversation/conversaion.go
  pkg/common/db/cache/conversation.go
  pkg/common/db/controller/conversation.go
  pkg/common/db/relation/conversation_model.go
  pkg/common/db/table/relation/conversation.go
Labels: size/L

#1067 feat: url to im s3
  go.work
  tools/url2im/go.mod
  tools/url2im/go.sum
  tools/url2im/main.go
  tools/url2im/pkg/api.go
  tools/url2im/pkg/buffer.go
  tools/url2im/pkg/config.go
  tools/url2im/pkg/http.go
  tools/url2im/pkg/manage.go
  tools/url2im/pkg/md5.go
  tools/url2im/pkg/progress.go
Labels: size/XL

#1078 internal/msgtransfer: fix unreachable code issue
  internal/msgtransfer/persistent_msg_handler.go
Labels: size/XS

#1101 Feature: add log support for developer
  go.mod
  internal/api/route.go
  internal/api/third.go
  internal/msggateway/client.go
  internal/msggateway/long_conn.go
  internal/rpc/third/log.go
  internal/rpc/third/third.go
  pkg/common/db/cache/conversation.go
  pkg/common/db/controller/third.go
  pkg/common/db/relation/log_model.go
  pkg/common/db/table/relation/log.go
  tools/imctl/go.mod
  tools/imctl/go.sum
Labels: size/L

#1080 feat: s3 public read
  config/config.yaml
  deployments/templates/openim.yaml
  internal/api/msg.go
  pkg/common/config/config.go
  pkg/common/db/s3/cos/cos.go
  pkg/common/db/s3/cos/doc.go
  pkg/common/db/s3/cos/internal.go
  pkg/common/db/s3/minio/doc.go
  pkg/common/db/s3/minio/internal.go
  pkg/common/db/s3/minio/minio.go
  pkg/common/db/s3/oss/doc.go
  pkg/common/db/s3/oss/internal.go
  pkg/common/db/s3/oss/oss.go
  scripts/install/environment.sh
Labels: size/L

#1104 feat: send message add sendTime field for import messages.
  config/config.yaml
  go.sum
  internal/api/msg.go
  internal/rpc/third/log.go
  pkg/apistruct/manage.go
  pkg/common/db/controller/third.go
  pkg/common/db/relation/log_model.go
  tools/component/component.go
Labels: size/M

#1112 fix: add callback for update user's info.
  config/config.yaml
  go.mod
  go.sum
  internal/rpc/user/callback.go
  internal/rpc/user/user.go
  pkg/callbackstruct/user.go
  pkg/common/config/config.go
Labels: size/M

#1055 🧶 feat: Big job! kubernetes Deployment Design
  .env
  .github/workflows/build-docker-image.yml
  .github/workflows/build-openim-web-image.yml
  .github/workflows/openimci.yml
  .gitignore
  CHANGELOG/CHANGELOG-3.1.md
  CHANGELOG/CHANGELOG-3.2.md
  CHANGELOG/CHANGELOG-3.3.md
  Makefile
  README.md
  build/README.md
  config/config.yaml
  deployments/README.md
  deployments/openim-chat/LICENSE
  deployments/openim-server/Chart.yaml
  deployments/openim-server/LICENSE
  deployments/openim-server/README.md
  deployments/templates/env_template.yaml
  deployments/templates/openim.yaml
  docker-compose.yml
  docs/contrib/environment.md
  docs/images/oepnim-design.png
  scripts/check-all.sh
  scripts/install-im-server.sh
  scripts/install/environment.sh
  scripts/install/openim-crontask.sh
  scripts/install/openim-push.sh
  scripts/install/openim-tools.sh
  scripts/make-rules/golang.mk
  scripts/make-rules/image.mk
  tools/component/component.go
  tools/imctl/.gitignore
  tools/imctl/cmd/genman/README.md
  tools/imctl/cmd/genman/genman.go
  tools/imctl/cmd/genopenimdocs/config_flags.go
  tools/imctl/cmd/imctl/imctl.go
  tools/imctl/go.mod
  tools/imctl/go.sum
  tools/imctl/internal/imctl/cmd/cmd.go
  tools/imctl/internal/imctl/cmd/color/color.go
  tools/imctl/internal/imctl/cmd/completion/completion.go
  tools/imctl/internal/imctl/cmd/info/info.go
  tools/imctl/internal/imctl/cmd/new/new.go
  tools/imctl/internal/imctl/cmd/options/options.go
  tools/imctl/internal/imctl/cmd/profiling.go
  tools/imctl/internal/imctl/cmd/version/version.go
Labels: size/XXL

#1147 fix: modifying user information notifications to join groups and group avatar issues
  go.work
  internal/rpc/group/group.go
  internal/rpc/user/user.go
  pkg/common/convert/group.go
Labels: size/M
