Repository openimsdk/open-im-server, pull requests merged in 2023-08, with the labels that each got.

#743 Update images.md
  docs/conversions/images.md
Labels: size/S

#742 Nginx reverse proxy and TLS configuration
  config/open-im-ng-example.conf
Labels: size/L

#745 Update docker-compose.yaml
  docker-compose.yaml
Labels: size/XS

#747 feat: Perfect with rpc but no api
  go.mod
  go.sum
  internal/api/friend.go
  internal/api/msg.go
  internal/api/route.go
Labels: size/M

#758 Fix bug 755
  pkg/common/db/cache/user.go
Labels: size/S

#763 nginx minio configuration picture can not be sent
  config/open-im-ng-example.conf
Labels: size/L

#774 Update images.md
  docs/conversions/images.md
Labels: size/XS

#792 Update README.md
  README.md
Labels: size/L

#793 Update README.md
  README.md
Labels: size/L

#794 Update go_code.md
  docs/conversions/go_code.md
Labels: size/XL

#795 Update README.md
  deployments/README.md
Labels: size/S

#796 Update README.md
  README.md
Labels: size/XS

#797 Update README.md
  README.md
Labels: size/S

#798 Create README.md
  assets/demo/README.md
Labels: size/S

#799 docs: add png file
  assets/demo/efficient-meetings.png
  assets/demo/group-chat.png
  assets/demo/multiple-message.png
  assets/demo/special-function.png
Labels: size/XS

#800 Update README.md
  README.md
Labels: size/S

#801 Update README.md
  assets/demo/README.md
Labels: size/XS

#802 Update README.md
  README.md
Labels: size/XS

#803 Update README.md
  README.md
Labels: size/XS

#790 feat: fix scripts and build speed
  .github/workflows/scripts-test.yml
  Dockerfile
  build/docker/openim-api/Dockerfile
  build/docker/openim-cmdutils/Dockerfile
  build/docker/openim-crontask/Dockerfile
  build/docker/openim-rpc-auth/Dockerfile
  build/docker/openim-rpc-conversation/Dockerfile
  build/docker/openim-rpc-friend/Dockerfile
  build/docker/openim-rpc-group/Dockerfile
  build/docker/openim-rpc-msg/Dockerfile
  build/docker/openim-rpc-third/Dockerfile
  build/docker/openim-rpc-user/Dockerfile
  docker-compose.yaml
  pkg/common/db/controller/user.go
  scripts/msg_gateway_start.sh
  scripts/msg_transfer_start.sh
  scripts/push_start.sh
  scripts/start_all.sh
  scripts/start_cron.sh
  scripts/stop_all.sh
Labels: size/M

#805 docs: add png multi-terminal-synchronization
  assets/demo/multi-terminal-synchronization.png
Labels: size/XS

#806 Update README.md
  README.md
Labels: size/S

#807 Update README.md
  README.md
Labels: size/XS

#810 Update docker-compose.yaml
  docker-compose.yaml
Labels: size/XS

#811 feat: add scripts format
  .gitignore
  Dockerfile
  docs/.generated_docs
  go.sum
  go.work
  go.work.sum
  install.sh
  scripts/build_all_service.sh
  scripts/check_all.sh
  scripts/common.sh
  scripts/coverage.sh
  scripts/docker_check_service.sh
  scripts/docker_start_all.sh
  scripts/env_check.sh
  scripts/environment.sh
  scripts/function.sh
  scripts/genconfig.sh
  scripts/lib/color.sh
  scripts/lib/util.sh
  scripts/make-rules/golang.mk
  scripts/start_cron.sh
  scripts/start_rpc_service.sh
  scripts/stop_all.sh
  scripts/style_info.sh
  scripts/wait-for-it.sh
  test/wrktest.sh
  tools/README.md
  tools/infra/go.mod
  tools/infra/main.go
  tools/ncpu/go.mod
  tools/ncpu/go.sum
  tools/ncpu/main.go
Labels: size/XL

#814 fix: fix bin tools path
  scripts/make-rules/common.mk
  scripts/make-rules/golang.mk
Labels: size/S

#816 Update version.md
  docs/conversions/version.md
Labels: size/M

#818 feat: server thumbnail
  config/config.yaml
  go.mod
  internal/api/third.go
  internal/rpc/third/s3.go
  internal/rpc/third/third.go
  pkg/common/config/config.go
  pkg/common/db/controller/s3.go
  pkg/common/db/controller/user.go
  pkg/common/db/s3/cont/controller.go
  pkg/common/db/s3/cos/cos.go
  pkg/common/db/s3/minio/image.go
  pkg/common/db/s3/minio/minio.go
  pkg/common/db/s3/minio/struct.go
  pkg/common/db/s3/oss/oss.go
  pkg/common/db/s3/oss/sign.go
  pkg/common/db/s3/oss/sort.go
  pkg/common/db/s3/s3.go
  pkg/common/db/unrelation/user.go
Labels: size/XL

#822 Update stop_all.sh
  scripts/stop_all.sh
Labels: size/XS

#824 fix: create group type limit
  internal/rpc/group/group.go
Labels: size/XS

#819 new feature data convert
  cmd/openim-crontask/main.go
  go.work.sum
  internal/msgtransfer/online_history_msg_handler.go
  internal/rpc/user/user.go
  internal/tools/cron_task.go
  internal/tools/msg_doc_convert.go
  pkg/common/db/controller/msg.go
  pkg/common/db/relation/user_model.go
  pkg/common/db/table/unrelation/msg.go
  pkg/common/db/unrelation/msg_convert.go
  pkg/msgprocessor/conversation.go
Labels: size/L

#766 modify search msg
  internal/rpc/msg/sync_msg.go
  pkg/common/db/controller/msg.go
  pkg/common/db/unrelation/msg.go
  scripts/start.bat
Labels: size/L

#823 Update golang.mk
  scripts/make-rules/golang.mk
Labels: size/S

#834 fix: MemberEnterNotification
  internal/rpc/group/group.go
  pkg/common/db/controller/group.go
  pkg/rpcclient/notification/group.go
Labels: size/L

#839 Fix bug: where if the last message in the document is an expired message, it won't delete the message within that document.
  pkg/common/db/controller/msg.go
Labels: size/S

#844 Fix bug: first time add friend
  pkg/common/db/controller/friend.go
  pkg/common/db/relation/friend_request_model.go
  pkg/common/db/relation/meta_db.go
Labels: size/S

#845 Fix add friend
  internal/rpc/user/user.go
  internal/tools/msg_doc_convert.go
  pkg/common/db/relation/friend_request_model.go
  pkg/common/db/unrelation/msg_convert.go
Labels: size/S

#847 chore: network mode change to start server normally
  docker-compose.yaml
  internal/msggateway/message_handler.go
Labels: size/S

#849 check components script
  Dockerfile
  docker-compose.yaml
  go.work
  scripts/docker_start_all.sh
  scripts/path_info.sh
  scripts/start_all.sh
  scripts/start_component_check.sh
  tools/component/go.mod
  tools/component/main.go
Labels: size/L

#855 fix: typo in golang.mk
  scripts/make-rules/golang.mk
Labels: size/XS

#857 group member sync use hash
  go.work.sum
  internal/rpc/group/group.go
  internal/rpc/msg/verify.go
  internal/tools/msg.go
  pkg/common/db/cache/group.go
  pkg/common/db/controller/group.go
Labels: size/L

#868 Update docker-compose.yaml
  docker-compose.yaml
Labels: size/XS

#853 Add feature 829
  config/notification.yaml
  go.mod
  go.sum
  go.work.sum
  internal/api/route.go
  internal/api/user.go
  internal/rpc/user/user.go
  pkg/common/config/config.go
  pkg/common/db/controller/user.go
  pkg/common/db/unrelation/user.go
  pkg/rpcclient/msg.go
  pkg/rpcclient/notification/friend.go
  pkg/rpcclient/notification/user.go
Labels: size/L

#867 Hotfix/arm build all services
  scripts/build_all_service.sh
Labels: size/S

#874 sync designation conversation unreadcount
  go.mod
  go.sum
  go.work.sum
  internal/rpc/msg/as_read.go
  pkg/common/db/cache/group.go
  tools/component/main.go
Labels: size/M

#881 fix: minio sign cndpoint crash caused by unconfigured
  pkg/common/db/s3/minio/minio.go
Labels: size/XS

#879 Fix bug #862
  go.mod
  go.sum
  go.work.sum
  internal/api/route.go
  internal/rpc/user/user.go
  pkg/common/db/cache/user.go
  pkg/rpcclient/user.go
Labels: size/L

#884 Feature: add api of get server time and the message's read status is incorrect when app reinstalling.
  go.mod
  go.sum
  go.work.sum
  internal/api/msg.go
  internal/api/route.go
  internal/rpc/msg/sync_msg.go
  pkg/common/convert/msg.go
  pkg/common/db/cache/user.go
  pkg/rpcclient/notification/user.go
  scripts/start_all.sh
Labels: size/S

#888 fix: script update
  scripts/start_all.sh
Labels: size/XS

#889 fix: script update
  scripts/start_all.sh
Labels: size/XS

#892 fix: start don't kill old process
  scripts/msg_gateway_start.sh
  scripts/msg_transfer_start.sh
  scripts/push_start.sh
  scripts/start_cron.sh
  scripts/start_rpc_service.sh
Labels: size/M

#859 Searchmsg
  pkg/common/db/unrelation/msg.go
Labels: size/XS

#897 chore: to map files of chat docker image into the IM server
  docker-compose.yaml
  openim-chat/config/config.yaml
  openim-chat/scripts/LICENSE/LICENSE
  openim-chat/scripts/LICENSE/LICENSE_TEMPLATES
  openim-chat/scripts/admin_rpc_start.sh
  openim-chat/scripts/build.cmd
  openim-chat/scripts/build_all_service.sh
  openim-chat/scripts/build_docker.sh
  openim-chat/scripts/check_all.sh
  openim-chat/scripts/docker_start_all.sh
  openim-chat/scripts/function.sh
  openim-chat/scripts/githooks/commit-msg
  openim-chat/scripts/githooks/pre-commit
  openim-chat/scripts/githooks/pre-push
  openim-chat/scripts/path_info.sh
  openim-chat/scripts/start.bat
  openim-chat/scripts/start_all.sh
  openim-chat/scripts/stop_all.sh
  openim-chat/scripts/style_info.sh
  scripts/docker_check_service.sh
  tools/component/main.go
Labels: size/XXL

#898 fix: check component
  pkg/common/db/unrelation/msg.go
  tools/component/main.go
Labels: size/XS

#900 docs: update sync file
  .github/sync.yml
Labels: size/S

#902 fix: pull message set isRead only message come from single.
  pkg/common/convert/msg.go
Labels: size/XS

#903 fix: pull message set isRead only message come from single.
  pkg/common/convert/msg.go
Labels: size/XS

#910 fix: admin revoke msg
  go.mod
  go.sum
  go.work.sum
  internal/rpc/msg/revoke.go
Labels: size/S

#918 fix: images bug find tput in make demo
  .env
  config/config.yaml
  deployments/templates/openim.yaml
  scripts/README.md
  scripts/demo.sh
  scripts/lib/color.sh
Labels: size/L

#894 MySQL Data conversion
  test/data-conversion/kafka-conversation.go
  test/data-conversion/kafka_test.go
  test/data-conversion/mongodb-conversion.go
  test/data-conversion/mysql-conversion.go
  test/data-conversion/mysql_test.go
  test/data-conversion/redis-conversion.go
Labels: size/L

#947 fix: add ex field to update group info.
  go.mod
  go.sum
  internal/rpc/group/db_map.go
Labels: size/XS

#954 fix: send text message by api doesn't work.
  internal/api/msg.go
  pkg/apistruct/msg.go
Labels: size/S

#960 fix: default friends and groups, no new sessions triggered
  internal/rpc/friend/friend.go
  pkg/common/kafka/consumer_group.go
  pkg/common/kafka/util.go
  pkg/common/tls/tls.go
  pkg/rpcclient/notification/group.go
Labels: size/M

#958 fix: send text message by api doesn't work. #929
  internal/api/msg.go
Labels: size/XS

#962 feat: Automating openim-docker synchronization
  .github/sync.yml
Labels: size/XS

#964 feat: create sync-release.yml
  .github/sync-release.yml
Labels: enhancement, kind/feature, size/S, kind/design

#963 feat: Automating openim-docker synchronization
  .github/workflows/sync-release.yml
Labels: enhancement, kind/feature, size/M, kind/design

#965 Update sync-release.yml
  .github/sync-release.yml
Labels: size/XS

#966 Update Dockerfile
  Dockerfile
Labels: size/XS

#974 Group members do not set their names and avatars to be updated in real time
  go.mod
  go.sum
  internal/rpc/group/fill.go
  internal/rpc/group/group.go
  internal/rpc/user/user.go
  pkg/common/db/controller/group.go
  pkg/rpcclient/group.go
  pkg/rpcclient/user.go
Labels: size/L

#977 fix: Transfer Group Questions
  pkg/common/db/controller/group.go
Labels: size/S

#986 add GetSpecifiedFriendsInfo
  go.mod
  go.sum
  internal/api/friend.go
  internal/api/route.go
  internal/rpc/friend/friend.go
  pkg/common/db/controller/black.go
  pkg/common/db/relation/black_model.go
  pkg/common/db/table/relation/black.go
Labels: size/M

#982 fix:sent message already has a timestamp, no timestamp will be generated
  internal/rpc/msg/verify.go
Labels: size/XS

#981 refactor:Optimization of text messages when accepting message req
  internal/api/msg.go
  pkg/apistruct/msg.go
Labels: size/S

#970 refactor:Returns [] an empty array when no platform is online, instea…
  pkg/common/db/cache/user.go
Labels: size/XS
