Repository openimsdk/open-im-server, pull requests merged in 2023-11, with the labels that each got.

#1312 perf: reduce register client latency
  internal/msggateway/n_ws_server.go
Labels: size/M

#1294 Optimize the control structure
  cmd/openim-api/main.go
  internal/msgtransfer/init.go
  internal/rpc/conversation/conversaion.go
  internal/tools/msg.go
  pkg/apistruct/manage.go
  pkg/common/cmd/api.go
  pkg/common/cmd/rpc.go
  pkg/common/config/parse.go
  pkg/common/db/relation/mysql_init.go
  pkg/common/discovery_register/k8s_discovery_register.go
  pkg/common/version/base.go
  pkg/common/version/types.go
  pkg/common/version/version.go
Labels: size/M

#1299 refactor: scheduled task splitting
  internal/tools/conversation.go
  internal/tools/cron_task.go
  internal/tools/msg.go
  pkg/common/db/controller/conversation.go
  pkg/common/db/relation/conversation_model.go
  pkg/common/db/table/relation/conversation.go
Labels: size/L

#1329 feat: S3 server cache
  internal/rpc/third/third.go
  pkg/common/db/cache/meta_cache.go
  pkg/common/db/cache/s3.go
  pkg/common/db/controller/s3.go
  pkg/common/db/s3/cont/controller.go
  pkg/common/db/s3/minio/minio.go
  pkg/common/db/s3/minio/struct.go
  pkg/common/db/s3/minio/thumbnail.go
Labels: size/XL

#1309 fix: wrong column
  pkg/common/db/relation/conversation_model.go
Labels: size/XS

#1293 Details optimization
  internal/msggateway/client.go
  internal/msggateway/context.go
  internal/rpc/msg/message_interceptor.go
  pkg/msgprocessor/conversation.go
Labels: size/M

#1341 Feat/add test scripts
  .github/workflows/auto-gh-pr.yml
  .github/workflows/auto-invite.yml
  .github/workflows/auto-tag.yml
  .github/workflows/bot-auto-cherry-pick.yml
  .github/workflows/check-coverage.yml
  .github/workflows/cla.yml
  .github/workflows/create_branch_on_tag.yml
  .github/workflows/deploy.yml
  .github/workflows/depsreview.yaml
  .github/workflows/e2e-test.yml
  .github/workflows/greetings.yml
  .github/workflows/issue-robot.yml
  .github/workflows/opencommit.yml
  .github/workflows/pull-request.yml
  .github/workflows/scripts-verify.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  scripts/init-config.sh
  scripts/install/environment.sh
  scripts/install/test.sh
  scripts/make-rules/common.mk
  scripts/template/footer.md.tmpl
  test/jwt/main.go
Labels: size/XXL

#1311 perf: http client transport
  pkg/common/http/http_client.go
Labels: size/M

#1313 fix: del SuperGroupRecvMsgNotNotifyUserIDs cache when conv edit
  pkg/common/db/controller/conversation.go
Labels: size/S

#1324 Fix get user in group members nil panic
  internal/rpc/group/group.go
Labels: size/M

#1343 refactor: client in msggateway
  internal/msggateway/client.go
  internal/msggateway/message_handler.go
Labels: size/L

#1349 feat: use dummy pusher by default
  internal/push/offlinepush/dummy/push.go
  internal/push/push_to_client.go
Labels: size/S

#1337 Add Prometheus monitoring function
  cmd/openim-api/main.go
  cmd/openim-msgtransfer/main.go
  config/config.yaml
  deployments/templates/openim.yaml
  go.mod
  go.sum
  internal/api/route.go
  internal/api/third.go
  internal/msggateway/hub_server.go
  internal/msggateway/init.go
  internal/msggateway/n_ws_server.go
  internal/msgtransfer/init.go
  internal/msgtransfer/online_msg_to_mongo_handler.go
  internal/push/consumer_init.go
  internal/push/push_rpc_server.go
  internal/push/push_to_client.go
  internal/rpc/auth/auth.go
  internal/rpc/msg/send.go
  internal/rpc/msg/server.go
  pkg/common/cmd/api.go
  pkg/common/cmd/msg_gateway.go
  pkg/common/cmd/msg_transfer.go
  pkg/common/cmd/rpc.go
  pkg/common/config/config.go
  pkg/common/config/parse.go
  pkg/common/db/controller/msg.go
  pkg/common/ginPrometheus/ginPrometheus.go
  pkg/common/kafka/producer.go
  pkg/common/prom_metrics/func.go
  pkg/common/prom_metrics/gin-api.go
  pkg/common/prom_metrics/grpc-auth.go
  pkg/common/prom_metrics/grpc-msg.go
  pkg/common/prom_metrics/grpc-msggateway.go
  pkg/common/prom_metrics/grpc_push.go
  pkg/common/prom_metrics/transfer.go
  pkg/common/prome/doc.go
  pkg/common/prome/gather.go
  pkg/common/prome/prometheus.go
  pkg/common/startrpc/start.go
  scripts/install/environment.sh
  scripts/install/openim-msgtransfer.sh
Labels: size/XXL

#1358 fix: initiateUpload sign list number
  pkg/common/db/s3/cont/controller.go
Labels: size/XS

#1367 fix: msg pull change and fcm redis flag fix.
  internal/api/msg.go
  pkg/common/db/cache/msg.go
  pkg/common/db/controller/msg.go
Labels: size/M

#1368 fix: sync close ws conn when kick old user avoid wrong trigger order …
  internal/msggateway/client.go
  internal/msggateway/n_ws_server.go
Labels: size/S

#1374 fix: GetUserReqApplicationList error when there is a disbanded group …
  internal/rpc/group/group.go
Labels: size/XS

#1376 fix: error when querying some information about disbanded group
  internal/rpc/group/group.go
Labels: size/M

#1378 fix: GetUserReqApplicationList dismissed group error
  internal/rpc/group/group.go
Labels: size/XS

#1370 refactor: lower the level of code nesting
  internal/push/push_to_client.go
Labels: size/L

#1339 perf: auto set runtime maxprocs in docker
  go.mod
  go.sum
  pkg/common/cmd/root.go
Labels: size/XS

#1381 build: build openim image
  .github/workflows/build-docker-image.yml
Labels: size/S

#1321 perf: improve gzip performance with sync.pool
  internal/msggateway/client.go
  internal/msggateway/compressor.go
  internal/msggateway/compressor_test.go
  internal/msggateway/init.go
Labels: size/L

#1310 fix: add kafka compress type and producer ack params
  pkg/common/config/config.go
  pkg/common/kafka/producer.go
Labels: size/S

#1338 perf: add concurrency and pipeline for redis cache
  pkg/common/config/config.go
  pkg/common/db/cache/msg.go
  pkg/common/db/cache/msg_test.go
Labels: size/L

#1371 refactor: gin prometheus for api
  pkg/common/ginprometheus/ginprometheus.go
Labels: size/L

#1327 perf: notify nodes concurrently on register
  internal/msggateway/n_ws_server.go
Labels: size/L

#1308 fix: reduce lock msg transfer
  internal/msgtransfer/init.go
  internal/msgtransfer/online_history_msg_handler.go
Labels: size/M

#1331 refactor: crontask cmd
  internal/tools/cron_task.go
  internal/tools/cron_task_test.go
  internal/tools/msg_doc_convert.go
  pkg/common/config/config.go
  pkg/common/db/cache/init_redis.go
Labels: size/L

#1388 fix: the original quoted message is withdrawn and the quoted original message is displayed.
  go.mod
  go.sum
  internal/api/third.go
  internal/push/offlinepush/dummy/push.go
  internal/tools/cron_task_test.go
  pkg/apistruct/manage.go
  pkg/common/cmd/msg_transfer.go
  pkg/common/db/controller/msg.go
  pkg/common/db/controller/msg_test.go
  pkg/common/db/s3/cont/controller.go
  pkg/common/prommetrics/prommetrics.go
  pkg/common/prommetrics/prommetrics_test.go
  pkg/common/startrpc/start.go
  test/e2e/api/user/curd.go
  test/e2e/e2e_test.go
Labels: size/L

#1393 Bug/fix online status sync trigger
  pkg/msgprocessor/conversation.go
Labels: size/XS

#1391 fix: the original quoted message is withdrawn and the quoted original message is displayed.
  pkg/common/db/controller/msg.go
Labels: size/M

#1396 refactor: lower the level of code nesting
  internal/msggateway/hub_server.go
  internal/msggateway/n_ws_server.go
Labels: size/L

#1403 "Add Prometheus Support with Documentation and Docker Compose Integration to OpenIM"
  .docker-compose_cfg/config.yaml
  .docker-compose_cfg/datasource-compose.yaml
  .docker-compose_cfg/grafana.db
  .docker-compose_cfg/grafana.ini
  .docker-compose_cfg/node-exporter-full_rev1.json
  .docker-compose_cfg/prometheus-compose.yml
  .env
  config/config.yaml
  config/prometheus-dashboard.yaml
  config/prometheus.yml
  deployments/templates/env_template.yaml
  deployments/templates/prometheus.yml
  docker-compose.yml
  docs/contrib/prometheus-grafana.md
  pkg/common/db/controller/msg.go
  scripts/genconfig.sh
  scripts/init-config.sh
  scripts/install/environment.sh
  scripts/install/install.sh
  scripts/install/openim-msggateway.sh
  scripts/lib/util.sh
  test/e2e/api/user/curd.go
Labels: size/XXL

#1411 perf: broadcast msg to all gateway with concurrency
  internal/push/push_to_client.go
  pkg/common/config/config.go
Labels: size/M

#1395 perf: redis batch delete msgs
  pkg/common/db/cache/msg.go
  pkg/common/db/cache/msg_test.go
Labels: size/L

#1424 Add Prometheus alerting functionality
  .github/workflows/e2e-test.yml
  .github/workflows/link-pr.yml
  README.md
  config/alertmanager.yml
  config/email.tmpl
  config/instance-down-rules.yml
  config/prometheus.yml
  deployments/templates/alertmanager.yml
  deployments/templates/env_template.yaml
  deployments/templates/prometheus.yml
  docker-compose.yml
  docs/contrib/prometheus-grafana.md
  scripts/init-config.sh
  scripts/install/environment.sh
  test/e2e/api/user/curd.go
  test/e2e/framework/config/config.go
Labels: size/L

#1425 Update docker-compose.yml
  docker-compose.yml
Labels: size/XS

#1432 feat: deployment and design of management backend and monitoring
  deployments/templates/env_template.yaml
  docs/contrib/environment.md
  docs/contrib/prometheus-grafana.md
  scripts/install/environment.sh
  scripts/install/install-protobuf.sh
Labels: size/S

#1455 kafka work error ,alertmanager work error
  deployments/templates/alertmanager.yml
  docker-compose.yml
  scripts/install/environment.sh
Labels: size/XS

#1451 perf: control ws write buffer
  internal/msggateway/init.go
  internal/msggateway/long_conn.go
  internal/msggateway/n_ws_server.go
  internal/msggateway/options.go
  pkg/common/config/config.go
Labels: size/S

#1477 Update README.md
  deployments/README.md
Labels: size/XS

#1423 perf: redis block with keys command
  pkg/common/db/cache/msg.go
  pkg/common/db/cache/msg_test.go
Labels: size/M

#1446 fix: update user's info will modify user create time when modify user…
  pkg/common/convert/user.go
Labels: size/XS

#1439 fix: grace shutdown for api server
  cmd/openim-api/main.go
Labels: size/M

#1485 docs: add openim search test
  scripts/install/test.sh
Labels: size/M

#1480 feat: add callback func
  deployments/templates/openim.yaml
  docs/contrib/environment.md
  internal/msggateway/callback.go
  internal/push/callback.go
  internal/rpc/friend/callback.go
  internal/rpc/friend/friend.go
  internal/rpc/group/callback.go
  internal/rpc/group/group.go
  internal/rpc/msg/as_read.go
  internal/rpc/msg/callback.go
  internal/rpc/user/callback.go
  internal/rpc/user/user.go
  pkg/callbackstruct/common.go
  pkg/callbackstruct/constant.go
  pkg/callbackstruct/friend.go
  pkg/callbackstruct/group.go
  pkg/callbackstruct/message.go
  pkg/callbackstruct/user.go
  pkg/common/config/config.go
  pkg/common/http/http_client.go
  scripts/install/environment.sh
Labels: size/XL

#1476 Feature middleware
  config/instance-down-rules.yml
  internal/msgtransfer/init.go
  internal/msgtransfer/online_history_msg_handler.go
  internal/rpc/msg/sync_msg.go
  pkg/common/db/cache/msg.go
  pkg/common/db/controller/msg.go
Labels: size/L

#1460 feat: OpenIMServer compatible qiniu kodo
  config/config.yaml
  deployments/templates/openim.yaml
  docs/contrib/environment.md
  go.mod
  go.sum
  internal/rpc/third/third.go
  pkg/common/config/config.go
  pkg/common/db/s3/kodo/internal.go
  pkg/common/db/s3/kodo/kodo.go
  scripts/install/environment.sh
Labels: size/L

#1465 add webhooks
  .env
  cmd/openim-msggateway/main.go
  config/alertmanager.yml
  config/config.yaml
  deployments/templates/alertmanager.yml
  deployments/templates/openim.yaml
  docs/contrib/environment.md
  go.mod
  go.sum
  internal/api/msg.go
  internal/msggateway/n_ws_server.go
  internal/rpc/friend/black.go
  internal/rpc/friend/callback.go
  internal/rpc/friend/friend.go
  internal/rpc/group/callback.go
  internal/rpc/group/group.go
  internal/rpc/msg/callback.go
  internal/rpc/msg/revoke.go
  internal/rpc/user/callback.go
  pkg/apistruct/msg.go
  pkg/callbackstruct/constant.go
  pkg/callbackstruct/friend.go
  pkg/callbackstruct/group.go
  pkg/callbackstruct/message.go
  pkg/callbackstruct/revoke.go
  pkg/common/config/config.go
  scripts/install/environment.sh
Labels: size/XL

#1491 docs: add rfyiamcool to code_owners
  docs/CODEOWNERS
Labels: size/S

#1502 Ⓜ️feat: openim docker fix
  .dockerignore
  .env
  .github/workflows/e2e-test.yml
  .github/workflows/opencommit.yml
  .github/workflows/openimci.yml
  .gitignore
  Dockerfile
  config/alertmanager.yml
  config/config.yaml
  deployments/templates/env_template.yaml
  install.sh
  install_guide.sh
  scripts/init-pwd.sh
Labels: size/XL
