Repository openimsdk/open-im-server, pull requests merged in 2023-12, with the labels that each got.

#1510 feat: Enhance Template Generation Logic in OPENIM Deployment Scripts
  .github/workflows/openimci.yml
  config/prometheus.yml
  scripts/init-config.sh
Labels: size/M

#1520 feat: Provides a new reading scheme for profile privacy through environment variables
  .gitignore
  docker-compose.yml
  scripts/init-config.sh
  scripts/install-im-server.sh
Labels: size/M

#1523 fix: remove docker compose mysql
  deployments/README.md
  deployments/templates/chat.yaml
  deployments/templates/env_template.yaml
  deployments/templates/openim.yaml
  docs/contrib/environment.md
  scripts/install-im-server.sh
  scripts/install/common.sh
  scripts/install/dependency.sh
  scripts/install/environment.sh
Labels: size/M

#1546 fix: fix docker compose scripts
  deployments/templates/env-template.yaml
  docs/contrib/bash-log.md
  install_guide.sh
  internal/rpc/msg/as_read.go
  scripts/init-config.sh
  scripts/install/openim-api.sh
  scripts/install/openim-rpc.sh
  scripts/lib/logging.sh
Labels: size/L

#1552 feat: optimize tools up35
  go.mod
  go.sum
  internal/rpc/friend/friend.go
  tools/up35/pkg/convert.go
  tools/up35/pkg/internal/rtc/mongo/mgo/meeting.go
  tools/up35/pkg/internal/rtc/mongo/mgo/meeting_invitation.go
  tools/up35/pkg/internal/rtc/mongo/mgo/meeting_record.go
  tools/up35/pkg/internal/rtc/mongo/mgo/signal.go
  tools/up35/pkg/internal/rtc/mongo/mgo/signal_invitation.go
  tools/up35/pkg/internal/rtc/mongo/table/meeting.go
  tools/up35/pkg/internal/rtc/mongo/table/signal.go
  tools/up35/pkg/internal/rtc/mysql/meeting.go
  tools/up35/pkg/internal/rtc/mysql/signal.go
  tools/up35/pkg/pkg.go
  tools/up35/up35.go
Labels: size/XXL

#1556 feat: optimize tools up35
  internal/rpc/friend/friend.go
  internal/rpc/user/user.go
  tools/data-conversion/go.mod
  tools/data-conversion/go.sum
  tools/up35/go.mod
Labels: size/L

#1557 fix group notification
  internal/rpc/group/group.go
Labels: size/XS

#1570 feat: support mac deployment and optimization make check
  .github/workflows/openimci.yml
  config/templates/config.yaml.template
  config/templates/env.template
  deployments/templates/env-template.yaml
  docker-compose.yml
  docs/contrib/environment.md
  scripts/check-all.sh
  scripts/docker-start-all.sh
  scripts/init-config.sh
  scripts/install/environment.sh
  scripts/lib/logging.sh
  scripts/lib/util.sh
Labels: size/L

#1565 support multipe msggateway services in k8s deployments
  pkg/common/discoveryregister/discoveryregister.go
Labels: size/M

#1573 Update check-all.sh
  scripts/check-all.sh
Labels: size/XS

#1532 add crud for general function user process, add pinFriend
  go.mod
  internal/api/friend.go
  internal/api/route.go
  internal/api/user.go
  internal/rpc/friend/black.go
  internal/rpc/friend/friend.go
  internal/rpc/group/callback.go
  internal/rpc/group/group.go
  internal/rpc/msg/callback.go
  internal/rpc/third/third.go
  internal/rpc/user/user.go
  pkg/callbackstruct/group.go
  pkg/common/convert/friend.go
  pkg/common/convert/user.go
  pkg/common/db/controller/friend.go
  pkg/common/db/controller/user.go
  pkg/common/db/mgo/friend.go
  pkg/common/db/mgo/user.go
  pkg/common/db/table/relation/friend.go
  pkg/common/db/table/relation/user.go
  pkg/common/http/http_client.go
  scripts/install/test.sh
Labels: size/L

#1585 fix: fix the output format
  tools/component/component.go
Labels: size/M

#1600 K8s environment supports multiple msggateway by consistent hash
  go.mod
  go.sum
  internal/msggateway/n_ws_server.go
  internal/push/push_to_client.go
  pkg/common/discoveryregister/kubernetes/kubernetes.go
Labels: size/L

#1591 Update check-all.sh
  scripts/check-all.sh
Labels: size/XS

#1586 Update prometheus.yml
  deployments/templates/prometheus.yml
Labels: size/S

#1534 fix: online notifications do not push to herself.
  internal/push/push_handler.go
  internal/push/push_rpc_server.go
Labels: size/S

#1602 feat: add the notificationAccount
  deployments/templates/openim.yaml
  docs/contrib/environment.md
  go.mod
  go.sum
  internal/api/friend.go
  internal/api/msg.go
  internal/api/route.go
  internal/api/user.go
  internal/rpc/friend/friend.go
  internal/rpc/user/user.go
  pkg/apistruct/msg.go
  pkg/authverify/token.go
  pkg/common/config/config.go
  pkg/common/db/controller/user.go
  pkg/common/http/http_client.go
  pkg/rpcclient/user.go
  scripts/check-all.sh
  scripts/install/environment.sh
Labels: size/L

#1610 Update openimci.yml
  .github/workflows/openimci.yml
  Makefile
Labels: size/S

#1614 feat: s3 FormData upload
  go.mod
  go.sum
  internal/api/route.go
  internal/api/third.go
  internal/rpc/friend/friend.go
  internal/rpc/third/s3.go
  internal/rpc/third/third.go
  internal/rpc/third/tool.go
  internal/rpc/user/user.go
  pkg/common/cmd/root.go
  pkg/common/db/controller/s3.go
  pkg/common/db/s3/cont/consts.go
  pkg/common/db/s3/cont/controller.go
  pkg/common/db/s3/cos/cos.go
  pkg/common/db/s3/minio/minio.go
  pkg/common/db/s3/oss/oss.go
  pkg/common/db/s3/s3.go
  pkg/common/ginprometheus/ginprometheus.go
Labels: size/L

#1615 docs: Update README.md and add openim web online demo address
  README.md
Labels: size/XS

#1617 fix: fix the searchNotificationAccout by userID or nickname
  go.mod
  go.sum
  internal/rpc/user/user.go
  pkg/common/db/controller/user.go
  pkg/common/db/mgo/user.go
  pkg/common/db/table/relation/user.go
Labels: size/M

#1609 fix: add syncself for some notifications.
  pkg/msgprocessor/options.go
  pkg/rpcclient/msg.go
Labels: size/S

#1623 fix: fix openim zk env set
  pkg/common/db/cache/init_redis.go
  pkg/common/discoveryregister/discoveryregister_test.go
  pkg/common/discoveryregister/zookeeper/zookeeper.go
  pkg/common/kafka/producer.go
  pkg/common/kafka/util.go
  tools/component/component_test.go
Labels: size/M

#1592 Add updates friend, set user ex
  config/templates/config.yaml.template
  go.sum
  internal/api/friend.go
  internal/api/msg.go
  internal/api/route.go
  internal/api/user.go
  internal/msggateway/client.go
  internal/rpc/friend/friend.go
  internal/rpc/msg/callback.go
  internal/rpc/user/callback.go
  internal/rpc/user/user.go
  pkg/callbackstruct/constant.go
  pkg/callbackstruct/user.go
  pkg/common/config/config.go
  pkg/common/convert/user.go
  pkg/common/db/controller/friend.go
  pkg/common/db/mgo/friend.go
  pkg/common/db/table/relation/friend.go
  pkg/rpcclient/msg.go
  pkg/rpcclient/notification/friend.go
  tools/component/component.go
Labels: size/L

#1611 fix: mongo uri connect
  pkg/common/db/unrelation/mongo.go
Labels: size/XS

#1604 fix: add the GetconversationAPI 1542
  go.mod
  go.sum
  internal/api/conversation.go
  internal/api/msg.go
  internal/api/route.go
  internal/rpc/conversation/conversaion.go
  internal/rpc/msg/as_read.go
  internal/rpc/msg/seq.go
  pkg/apistruct/manage.go
  pkg/common/db/controller/msg.go
  pkg/rpcclient/msg.go
Labels: size/L

#1632 fix: fix openim scripts and ci add openim check
  .github/workflows/openimci.yml
  deployments/templates/env-template.yaml
  docker-compose.yml
  scripts/check-all.sh
  scripts/install/environment.sh
  tools/component/component.go
Labels: size/M

#1641 feat: add openim scripts fix and optimize config about openim source code deployment for this PR? openim ci and scripts
  deployments/templates/env-template.yaml
Labels: size/L

#1636 feature:grafana web inside
  config/templates/config.yaml.template
  deployments/templates/openim.yaml
  docker-compose.yml
  internal/api/third.go
  pkg/common/config/config.go
  scripts/install/environment.sh
Labels: size/S

#1643 fix: Bash Compatibility in print_services_and_ports Function
  scripts/check-all.sh
Labels: size/S
