Repository openimsdk/open-im-server, pull requests merged in 2023-10, with the labels that each got.

#1157 docs(main): update openim readme
  README.md
Labels: size/L

#1160 fix: Implement Enhanced File Descriptor Limit Handling in Shell Script
  scripts/install/openim-msggateway.sh
  scripts/install/openim-msgtransfer.sh
  scripts/lib/util.sh
Labels: size/M

#1164 feat: v2 to v3 data conversion
  go.work
  tools/data-conversion/chat/conversion/cmd.go
  tools/data-conversion/chat/conversion/conversion.go
  tools/data-conversion/chat/main.go
  tools/data-conversion/chat/v2/admin.go
  tools/data-conversion/chat/v2/chat.go
  tools/data-conversion/chat/v3/admin/admin.go
  tools/data-conversion/chat/v3/admin/applet.go
  tools/data-conversion/chat/v3/admin/client_config.go
  tools/data-conversion/chat/v3/admin/forbidden_account.go
  tools/data-conversion/chat/v3/admin/invitation_register.go
  tools/data-conversion/chat/v3/admin/ip_forbidden.go
  tools/data-conversion/chat/v3/admin/limit_user_login_ip.go
  tools/data-conversion/chat/v3/admin/register_add_friend.go
  tools/data-conversion/chat/v3/admin/register_add_group.go
  tools/data-conversion/chat/v3/chat/account.go
  tools/data-conversion/chat/v3/chat/attribute.go
  tools/data-conversion/chat/v3/chat/register.go
  tools/data-conversion/chat/v3/chat/user_login_record.go
  tools/data-conversion/go.mod
  tools/data-conversion/go.sum
  tools/data-conversion/kafka-conversation.go
  tools/data-conversion/kafka_test.go
  tools/data-conversion/mongodb-conversion.go
  tools/data-conversion/mysql-conversion.go
  tools/data-conversion/mysql_test.go
  tools/data-conversion/redis-conversion.go
Labels: size/XXL

#1161 fix: make lint about cicd
  .golangci.yml
  cmd/openim-api/main.go
  internal/api/third.go
  internal/msggateway/long_conn.go
  internal/rpc/third/log.go
  pkg/common/db/cache/conversation.go
  pkg/common/db/controller/third.go
  pkg/common/db/relation/log_model.go
  tools/component/component.go
Labels: size/M

#1165 docs: add openim docs
  docs/contrib/environment.md
  docs/contrib/install_docker.md
Labels: size/XL

#1163 fix: api send msg update.
  internal/api/msg.go
Labels: size/XS

#1176 feat: v2 to v3 data conversion
  tools/data-conversion/chat/chat.go
  tools/data-conversion/chat/conversion/cmd.go
  tools/data-conversion/chat/conversion/conversion.go
  tools/data-conversion/chat/main.go
  tools/data-conversion/go.mod
  tools/data-conversion/go.sum
  tools/data-conversion/info.md
  tools/data-conversion/kafka-conversation.go
  tools/data-conversion/kafka_test.go
  tools/data-conversion/mongodb-conversion.go
  tools/data-conversion/mysql-conversion.go
  tools/data-conversion/openim/common/config.go
  tools/data-conversion/openim/common/console.go
  tools/data-conversion/openim/msg.go
  tools/data-conversion/openim/mysql.go
  tools/data-conversion/openim/mysql/cmd.go
  tools/data-conversion/openim/mysql/conversion/conversion.go
  tools/data-conversion/openim/mysql/v2/model_struct.go
  tools/data-conversion/openim/proto/msg/msg.pb.go
  tools/data-conversion/openim/proto/msg/msg.proto
  tools/data-conversion/openim/proto/sdk_ws/wrappers.proto
  tools/data-conversion/openim/proto/sdk_ws/ws.pb.go
  tools/data-conversion/openim/proto/sdk_ws/ws.proto
  tools/data-conversion/redis-conversion.go
  tools/data-conversion/utils/find_insert.go
  tools/data-conversion/utils/time.go
Labels: size/XXL

#1185 Ensure Script Compatibility Across Different Bash Versions
  scripts/lib/color.sh
Labels: needs-triage, size/XS

#1178 feat: add redis cluster mode in option
  README-zh_CN.md
  pkg/common/config/config.go
  pkg/common/db/cache/init_redis.go
Labels: size/S

#1179 optimize: reduce lock latency for localcache group
  pkg/common/db/localcache/group.go
Labels: size/XS

#1194 Docs(main): Add English translation for README.md
  README-zh_CN.md
Labels: kind/documentation, size/L

#1192 bug:update a filed
  internal/rpc/group/callback.go
Labels: size/XS

#1218 fix(release-v3.0): fix makefile go version update image
  scripts/make-rules/golang.mk
Labels: size/XS

#1171 fix: single chat unread status change.
  go.mod
  go.sum
  internal/msggateway/client.go
  internal/rpc/msg/as_read.go
  internal/rpc/user/user.go
  pkg/common/db/cache/user.go
  pkg/common/db/controller/user.go
  pkg/common/db/unrelation/user.go
  pkg/rpcclient/user.go
  tools/component/component.go
  tools/data-conversion/chat/chat.go
  tools/data-conversion/chat/v2/admin.go
  tools/data-conversion/chat/v2/chat.go
  tools/data-conversion/openim/common/config.go
  tools/data-conversion/openim/msg.go
  tools/data-conversion/openim/mysql.go
  tools/data-conversion/openim/mysql/cmd.go
  tools/data-conversion/openim/mysql/conversion/conversion.go
  tools/data-conversion/openim/mysql/v2/model_struct.go
  tools/data-conversion/utils/find_insert.go
Labels: size/L

#1217 fix(release-v3.2): fix makefile go version update image
  scripts/make-rules/golang.mk
Labels: size/XS

#1210 fix(release-v3.1): fix makefile go version update image
  scripts/make-rules/golang.mk
Labels: size/XS

#1198 fix: after modifying the avatar, offline users who joined the group did not synchronize
  go.mod
  go.sum
  internal/rpc/group/group.go
  pkg/common/db/controller/group.go
Labels: size/M

#1145 feat: Add the help chart script to support k8s deployment
  cmd/openim-api/main.go
  cmd/openim-push/main.go
  cmd/openim-rpc/openim-rpc-auth/main.go
  cmd/openim-rpc/openim-rpc-conversation/main.go
  cmd/openim-rpc/openim-rpc-friend/main.go
  cmd/openim-rpc/openim-rpc-group/main.go
  cmd/openim-rpc/openim-rpc-msg/main.go
  cmd/openim-rpc/openim-rpc-third/main.go
  cmd/openim-rpc/openim-rpc-user/main.go
  config/config.yaml
  deployments/templates/openim.yaml
  internal/msggateway/n_ws_server.go
  internal/msgtransfer/init.go
  internal/tools/msg.go
  manifest/build-docker.sh
  manifest/dockerfiles/openim-api/Dockerfile
  manifest/dockerfiles/openim-crontask/Dockerfile
  manifest/dockerfiles/openim-msggateway/Dockerfile
  manifest/dockerfiles/openim-msgtransfer/Dockerfile
  manifest/dockerfiles/openim-push/Dockerfile
  manifest/dockerfiles/openim-rpc-auth/Dockerfile
  manifest/dockerfiles/openim-rpc-conversation/Dockerfile
  manifest/dockerfiles/openim-rpc-friend/Dockerfile
  manifest/dockerfiles/openim-rpc-group/Dockerfile
  manifest/dockerfiles/openim-rpc-msg/Dockerfile
  manifest/dockerfiles/openim-rpc-third/Dockerfile
  manifest/dockerfiles/openim-rpc-user/Dockerfile
  pkg/common/cmd/api.go
  pkg/common/cmd/constant.go
  pkg/common/cmd/cron_task.go
  pkg/common/cmd/msg_gateway.go
  pkg/common/cmd/msg_transfer.go
  pkg/common/cmd/root.go
  pkg/common/cmd/rpc.go
  pkg/common/config/config.go
  pkg/common/discovery_register/k8s_discovery_register.go
  pkg/common/startrpc/start.go
  scripts/install/environment.sh
Labels: size/XL

#1231 optimize: reduce lock latency for conversation cache
  pkg/common/db/localcache/conversation.go
Labels: size/XS

#1221 fix: remove repeat platform on online status.
  pkg/common/db/cache/user.go
Labels: size/S

#1250 feat:order logs by time desc
  pkg/common/db/relation/log_model.go
Labels: size/XS

#1244 fate: api, rpc QuitGroup req add userID
  internal/rpc/group/group.go
  pkg/common/db/s3/minio/minio.go
Labels: size/M

#1265 Update README.md
  tools/data-conversion/README.md
Labels: size/XS

#1259 fix: golint code format and error log trace
  internal/msggateway/init.go
  pkg/common/cmd/root.go
  pkg/common/startrpc/doc.go
  pkg/common/startrpc/start.go
Labels: size/M

#1258 fix: not support redis cluster. CROSSSLOT Keys in request don't hash to the same slot
  pkg/common/db/cache/black.go
  pkg/common/db/cache/conversation.go
  pkg/common/db/cache/friend.go
  pkg/common/db/cache/group.go
  pkg/common/db/cache/meta_cache.go
  pkg/common/db/cache/msg.go
  pkg/common/db/cache/user.go
  pkg/common/db/controller/conversation.go
Labels: size/XXL

#1284 fix: zk add close to avoid zk block.
  go.mod
  internal/rpc/msg/sync_msg.go
  pkg/common/discovery_register/k8s_discovery_register.go
  pkg/common/startrpc/start.go
Labels: size/M

#1285 fix: create database name
  pkg/common/db/relation/mysql_init.go
  pkg/common/db/relation/mysql_init_test.go
Labels: size/L

#1287 fix: NotNotifyUser receive offline push
  internal/push/push_to_client.go
Labels: size/XS

#1304 docs: update readme docs
  Makefile
  README.md
Labels: size/XS
