Repository openimsdk/open-im-server, pull requests merged in 2024-12, with the labels that each got.

#2906 fix: go mod
  go.mod
  go.sum
Labels: size/M

#2910 fix: group member update face_url
  internal/rpc/group/db_map.go
Labels: size/XS

#2896 fix https://github.com/openimsdk/open-im-server/issues/2895
  config/openim-msggateway.yml
  config/openim-push.yml
  config/openim-rpc-auth.yml
  config/openim-rpc-conversation.yml
  config/openim-rpc-friend.yml
  config/openim-rpc-group.yml
  config/openim-rpc-msg.yml
  config/openim-rpc-third.yml
  config/openim-rpc-user.yml
  internal/msggateway/hub_server.go
  internal/msggateway/init.go
  internal/tools/addr/addr.go
  pkg/common/cmd/auth.go
  pkg/common/cmd/conversation.go
  pkg/common/cmd/friend.go
  pkg/common/cmd/group.go
  pkg/common/cmd/msg.go
  pkg/common/cmd/push.go
  pkg/common/cmd/third.go
  pkg/common/cmd/user.go
  pkg/common/config/config.go
  pkg/common/startrpc/start.go
Labels: size/L

#2924 feat: seq user and conversation seq synchronization
  go.mod
  go.sum
  internal/rpc/conversation/conversation.go
  internal/rpc/group/group.go
  internal/rpc/msg/seq.go
  internal/rpc/msg/server.go
  internal/rpc/third/log.go
  pkg/common/storage/controller/msg.go
Labels: size/M

#2929 feat: Can choose whether to set the port.
  config/openim-msggateway.yml
  config/openim-push.yml
  config/openim-rpc-auth.yml
  config/openim-rpc-conversation.yml
  config/openim-rpc-friend.yml
  config/openim-rpc-group.yml
  config/openim-rpc-msg.yml
  config/openim-rpc-third.yml
  config/openim-rpc-user.yml
  internal/msggateway/hub_server.go
  internal/msggateway/init.go
  internal/tools/addr/addr.go
  pkg/common/cmd/auth.go
  pkg/common/cmd/conversation.go
  pkg/common/cmd/friend.go
  pkg/common/cmd/group.go
  pkg/common/cmd/msg.go
  pkg/common/cmd/push.go
  pkg/common/cmd/third.go
  pkg/common/cmd/user.go
  pkg/common/config/config.go
  pkg/common/startrpc/start.go
Labels: size/L

#2934 feat: Configure mobile service discovery into discovery
  config/discovery.yml
  internal/api/init.go
  internal/api/router.go
  internal/msggateway/hub_server.go
  internal/msggateway/message_handler.go
  internal/msggateway/ws_server.go
  internal/msgtransfer/init.go
  internal/push/onlinepusher.go
  internal/push/push_handler.go
  internal/rpc/auth/auth.go
  internal/rpc/conversation/conversation.go
  internal/rpc/group/group.go
  internal/rpc/msg/server.go
  internal/rpc/relation/friend.go
  internal/rpc/third/third.go
  internal/rpc/user/user.go
  internal/tools/cron_task.go
  pkg/common/cmd/auth.go
  pkg/common/cmd/conversation.go
  pkg/common/cmd/friend.go
  pkg/common/cmd/group.go
  pkg/common/cmd/msg.go
  pkg/common/cmd/push.go
  pkg/common/cmd/third.go
  pkg/common/cmd/user.go
  pkg/common/config/config.go
  pkg/common/discoveryregister/discoveryregister.go
  pkg/common/prommetrics/rpc.go
  pkg/common/startrpc/start.go
  tools/check-component/main.go
Labels: size/L

#2938 feat: support aws
  config/openim-rpc-third.yml
  go.mod
  go.sum
  internal/rpc/third/third.go
  pkg/common/config/config.go
Labels: size/L

#2920 build: implement services image build and CI release.
  .github/workflows/build-and-release-services-images.yml
  Dockerfile
  build/images/Dockerfile
  build/images/openim-api/Dockerfile
  build/images/openim-cmdutils/Dockerfile
  build/images/openim-crontask/Dockerfile
  build/images/openim-msggateway/Dockerfile
  build/images/openim-msgtransfer/Dockerfile
  build/images/openim-push/Dockerfile
  build/images/openim-rpc-auth/Dockerfile
  build/images/openim-rpc-conversation/Dockerfile
  build/images/openim-rpc-friend/Dockerfile
  build/images/openim-rpc-group/Dockerfile
  build/images/openim-rpc-msg/Dockerfile
  build/images/openim-rpc-third/Dockerfile
  build/images/openim-rpc-user/Dockerfile
  build/images/openim-tools/component/Dockerfile
  config/discovery.yml
  config/openim-msggateway.yml
  config/openim-push.yml
  config/openim-rpc-auth.yml
  config/openim-rpc-conversation.yml
  config/openim-rpc-friend.yml
  config/openim-rpc-group.yml
  config/openim-rpc-msg.yml
  config/openim-rpc-third.yml
  config/openim-rpc-user.yml
  go.mod
  go.sum
  internal/api/init.go
  internal/msggateway/init.go
  internal/msgtransfer/init.go
  internal/tools/cron_task.go
  magefile.go
  pkg/common/cmd/root.go
  pkg/common/config/config.go
  pkg/common/config/constant.go
  pkg/common/config/load_config.go
  pkg/common/config/load_config_test.go
  pkg/common/discoveryregister/discoveryregister.go
  pkg/common/discoveryregister/kubernetes/kubernetes.go
  pkg/common/startrpc/start.go
  tools/check-component/main.go
Labels: size/XXL

#2940 fix: compilation failed under Windows
  go.mod
  go.sum
Labels: size/M

#2943 feat: Prometheus can auto set port
  config/openim-api.yml
  config/openim-msggateway.yml
  config/openim-msgtransfer.yml
  config/openim-push.yml
  config/openim-rpc-auth.yml
  config/openim-rpc-conversation.yml
  config/openim-rpc-friend.yml
  config/openim-rpc-group.yml
  config/openim-rpc-msg.yml
  config/openim-rpc-third.yml
  config/openim-rpc-user.yml
  config/prometheus.yml
  docker-compose.yml
  go.mod
  go.sum
  internal/api/init.go
  internal/api/prometheus_discovery.go
  internal/api/router.go
  internal/msggateway/init.go
  internal/msgtransfer/init.go
  pkg/common/config/config.go
  pkg/common/config/load_config_test.go
  pkg/common/discoveryregister/discoveryregister.go
  pkg/common/prommetrics/api.go
  pkg/common/prommetrics/discovery.go
  pkg/common/prommetrics/prommetrics.go
  pkg/common/prommetrics/rpc.go
  pkg/common/prommetrics/transfer.go
  pkg/common/startrpc/start.go
Labels: size/XL

#2949 fix: server can return isEnd to control fetch messages when sdk pull …
  go.mod
  go.sum
  internal/rpc/msg/sync_msg.go
  pkg/common/storage/controller/msg.go
Labels: size/M

#2927 feat: Change upload logs systemType to AppFramework.
  internal/rpc/third/log.go
  pkg/common/storage/model/log.go
Labels: size/M

#2947 fix:Only print panic function frame && feat: log.ZPanic
  go.mod
  go.sum
  internal/msggateway/client.go
  internal/msgtransfer/init.go
  internal/msgtransfer/online_history_msg_handler.go
  internal/rpc/msg/send.go
  pkg/rpccache/subscriber.go
Labels: size/S

#2819 feat: support quote ContentType in SendMsg.
  internal/api/msg.go
  pkg/apistruct/msg.go
Labels: size/M

#2958 fix: seq user and conversation seq synchronization
  internal/rpc/msg/delete.go
Labels: size/XS

#2957 fix: rpc panic recover
  go.mod
  go.sum
  internal/push/push.go
Labels: size/S

#2914 Add a lead time for the token's issuance time.
  internal/rpc/auth/auth.go
Labels: size/XS

#2972 fix: modifying other fields while setting IsPrivateChat does not take effect
  internal/rpc/conversation/conversation.go
Labels: size/S

#2969 refactor: Refactor rpc call && auto gen rpc_call code
  go.mod
  go.sum
  internal/api/auth.go
  internal/api/conversation.go
  internal/api/friend.go
  internal/api/group.go
  internal/api/init.go
  internal/api/jssdk/jssdk.go
  internal/api/msg.go
  internal/api/router.go
  internal/api/statistics.go
  internal/api/third.go
  internal/api/user.go
  internal/msggateway/client.go
  internal/msggateway/hub_server.go
  internal/msggateway/init.go
  internal/msggateway/message_handler.go
  internal/msggateway/online.go
  internal/msggateway/ws_server.go
  internal/msgtransfer/init.go
  internal/msgtransfer/online_history_msg_handler.go
  internal/push/push_handler.go
  internal/rpc/auth/auth.go
  internal/rpc/conversation/conversation.go
  internal/rpc/conversation/notification.go
  internal/rpc/group/cache.go
  internal/rpc/group/callback.go
  internal/rpc/group/convert.go
  internal/rpc/group/fill.go
  internal/rpc/group/group.go
  internal/rpc/group/notification.go
  internal/rpc/group/statistics.go
  internal/rpc/group/sync.go
  internal/rpc/msg/clear.go
  internal/rpc/msg/delete.go
  internal/rpc/msg/send.go
  internal/rpc/msg/server.go
  internal/rpc/msg/stream_msg.go
  internal/rpc/relation/black.go
  internal/rpc/relation/friend.go
  internal/rpc/relation/notification.go
  internal/rpc/third/log.go
  internal/rpc/third/third.go
  internal/rpc/user/notification.go
  internal/rpc/user/user.go
  pkg/common/startrpc/start.go
  pkg/rpccache/conversation.go
  pkg/rpccache/friend.go
  pkg/rpccache/group.go
  pkg/rpccache/online.go
  pkg/rpccache/user.go
  pkg/rpcclient/auth.go
  pkg/rpcclient/conversation.go
  pkg/rpcclient/friend.go
  pkg/rpcclient/group.go
  pkg/rpcclient/init.go
  pkg/rpcclient/msg.go
  pkg/rpcclient/push.go
  pkg/rpcclient/third.go
  pkg/rpcclient/user.go
Labels: size/XXL

#2977 fix: when fetching a referenced message, it indicates that the original message has been deleted.
  pkg/common/storage/controller/msg.go
Labels: size/M

#2975 feat: Group Monitoring Components, Enable Host Mode && Deprecate reliabilityLevel and unreadCount in notification.yml
  .env
  .github/workflows/go-build-test.yml
  config/notification.yml
  config/openim-api.yml
  config/prometheus.yml
  config/share.yml
  docker-compose.yml
  internal/msggateway/hub_server.go
  pkg/common/cmd/auth.go
  pkg/common/cmd/conversation.go
  pkg/common/cmd/friend.go
  pkg/common/cmd/group.go
  pkg/common/cmd/msg.go
  pkg/common/cmd/push.go
  pkg/common/cmd/third.go
  pkg/common/cmd/user.go
  pkg/common/config/config.go
  pkg/common/config/parse.go
  pkg/common/startrpc/start.go
Labels: size/L

#2979 feat: Add node_exporter in docker-compose
  .env
  config/openim-api.yml
  config/openim-msggateway.yml
  config/openim-msgtransfer.yml
  config/openim-push.yml
  config/openim-rpc-auth.yml
  config/openim-rpc-conversation.yml
  config/openim-rpc-friend.yml
  config/openim-rpc-group.yml
  config/openim-rpc-msg.yml
  config/openim-rpc-third.yml
  config/openim-rpc-user.yml
  config/prometheus.yml
  config/share.yml
  docker-compose.yml
Labels: size/M

#2985 feat: Optimize Scheduled Task
  go.mod
  go.sum
  internal/api/router.go
  internal/rpc/conversation/conversation.go
  internal/rpc/msg/clear.go
  internal/rpc/third/s3.go
  internal/rpc/third/third.go
  internal/tools/cron_task.go
  internal/tools/cron_test.go
  internal/tools/msg.go
  internal/tools/s3.go
  internal/tools/user_msg.go
  pkg/common/storage/controller/conversation.go
  pkg/common/storage/controller/msg.go
  pkg/common/storage/controller/s3.go
  pkg/common/storage/database/conversation.go
  pkg/common/storage/database/mgo/conversation.go
  pkg/common/storage/database/mgo/msg.go
  pkg/common/storage/database/mgo/msg_test.go
  pkg/common/storage/database/mgo/object.go
  pkg/common/storage/database/msg.go
  pkg/common/storage/database/object.go
Labels: size/XXL

#2995 feat: optimize error stack information
  go.mod
  go.sum
  internal/msggateway/client.go
  internal/msgtransfer/init.go
  internal/msgtransfer/online_history_msg_handler.go
  internal/rpc/msg/send.go
  pkg/rpccache/subscriber.go
Labels: size/S

#3001 fix: when unable EnableHistoryForNewMembers, new group member can read last one message.
  internal/rpc/group/notification.go
Labels: size/XS

#3002 fix: redis save error when KickTokens
  pkg/common/storage/cache/redis/token.go
  pkg/common/storage/cache/token.go
  pkg/common/storage/controller/auth.go
Labels: size/S

#2997 feat: config center
  config/openim-push.yml
  docker-compose.yml
  internal/api/config_manager.go
  internal/api/init.go
  internal/api/router.go
  internal/msggateway/hub_server.go
  internal/msggateway/ws_server.go
  internal/msgtransfer/init.go
  internal/tools/cron_task.go
  internal/tools/cron_test.go
  pkg/apistruct/config_manager.go
  pkg/common/cmd/api.go
  pkg/common/cmd/auth.go
  pkg/common/cmd/constant.go
  pkg/common/cmd/conversation.go
  pkg/common/cmd/cron_task.go
  pkg/common/cmd/friend.go
  pkg/common/cmd/group.go
  pkg/common/cmd/msg.go
  pkg/common/cmd/msg_gateway.go
  pkg/common/cmd/msg_transfer.go
  pkg/common/cmd/msg_utils.go
  pkg/common/cmd/push.go
  pkg/common/cmd/root.go
  pkg/common/cmd/third.go
  pkg/common/cmd/user.go
  pkg/common/config/config.go
  pkg/common/config/env.go
  pkg/common/config/load_config_test.go
  pkg/common/config/parse.go
  pkg/common/discovery/direct/direct_resolver.go
  pkg/common/discovery/direct/directconn.go
  pkg/common/discovery/direct/doc.go
  pkg/common/discovery/discoveryregister.go
  pkg/common/discovery/discoveryregister_test.go
  pkg/common/discovery/doc.go
  pkg/common/discovery/etcd/config_manager.go
  pkg/common/discovery/etcd/doc.go
  pkg/common/discovery/kubernetes/doc.go
  pkg/common/discovery/kubernetes/kubernetes.go
  pkg/common/startrpc/start.go
  tools/check-component/main.go
  tools/seq/internal/seq.go
Labels: size/XXL

#3007 feat: support message cache
  internal/msgtransfer/init.go
  internal/msgtransfer/online_msg_to_mongo_handler.go
  internal/rpc/msg/delete.go
  internal/rpc/msg/revoke.go
  internal/rpc/msg/server.go
  pkg/common/storage/cache/cachekey/msg.go
  pkg/common/storage/cache/msg.go
  pkg/common/storage/cache/redis/msg.go
  pkg/common/storage/cache/redis/msg_test.go
  pkg/common/storage/controller/msg.go
  pkg/common/storage/controller/msg_transfer.go
  pkg/common/storage/database/mgo/msg.go
  pkg/common/storage/database/msg.go
  pkg/common/storage/model/msg.go
Labels: size/XXL

#2973 docs: improve deployment docs in kubernetes.
  deployments/Readme.md
  deployments/deploy/README.md
  deployments/deploy/kafka-secret.yml
  deployments/deploy/minio-secret.yml
  deployments/deploy/minio-statefulset.yml
  deployments/deploy/mongo-secret.yml
  deployments/deploy/mongo-statefulset.yml
  deployments/deploy/openim-api-deployment.yml
  deployments/deploy/openim-config.yml
  deployments/deploy/openim-msggateway-deployment.yml
  deployments/deploy/openim-msgtransfer-deployment.yml
  deployments/deploy/openim-push-deployment.yml
  deployments/deploy/openim-rpc-auth-deployment.yml
  deployments/deploy/openim-rpc-conversation-deployment.yml
  deployments/deploy/openim-rpc-friend-deployment.yml
  deployments/deploy/openim-rpc-group-deployment.yml
  deployments/deploy/openim-rpc-msg-deployment.yml
  deployments/deploy/openim-rpc-third-deployment.yml
  deployments/deploy/openim-rpc-user-deployment.yml
  deployments/deploy/redis-secret.yml
  deployments/deploy/redis-statefulset.yml
Labels: size/L

#3009 fix: The message @ information will be set only for members in the gr…
  go.mod
  go.sum
  internal/rpc/msg/send.go
Labels: size/S

#3016 fix: jssdk not init
  internal/api/jssdk/jssdk.go
  internal/api/router.go
  internal/msgtransfer/online_history_msg_handler.go
Labels: size/S

#3018 fix: resolving v3.8.3 conflicts
  go.mod
  go.sum
  internal/api/auth.go
  internal/api/conversation.go
  internal/api/friend.go
  internal/api/group.go
  internal/api/init.go
  internal/api/jssdk/jssdk.go
  internal/api/router.go
  internal/api/statistics.go
  internal/api/third.go
  internal/api/user.go
  internal/msggateway/client.go
  internal/msggateway/hub_server.go
  internal/msggateway/init.go
  internal/msggateway/message_handler.go
  internal/msggateway/ws_server.go
  internal/msgtransfer/init.go
  internal/msgtransfer/online_history_msg_handler.go
  internal/push/push_handler.go
  internal/rpc/auth/auth.go
  internal/rpc/conversation/conversation.go
  internal/rpc/group/group.go
  internal/rpc/group/notification.go
  internal/rpc/msg/server.go
  internal/rpc/msg/stream_msg.go
  internal/rpc/relation/black.go
  internal/rpc/relation/friend.go
  internal/rpc/third/third.go
  internal/rpc/user/user.go
  pkg/common/startrpc/start.go
  pkg/notification/auth.go
  pkg/notification/conversation.go
  pkg/notification/friend.go
  pkg/notification/group.go
  pkg/notification/msg.go
  pkg/notification/push.go
  pkg/notification/third.go
  pkg/rpccache/friend.go
  pkg/rpccache/group.go
  pkg/rpccache/online.go
  pkg/rpcclient/user.go
Labels: size/XXL

#3020 build: fix uncorrect path.
  .github/workflows/build-and-release-services-images.yml
  .github/workflows/docker-build-and-release-services-images.yml
Labels: size/L

#3022 fix: online status error
  go.mod
  go.sum
  pkg/rpccache/online.go
  pkg/rpcli/group.go
Labels: size/M

#3024 build: fix docker images build.
  .github/workflows/docker-build-and-release-services-images.yml
Labels: size/XS

#3026 feat: optimize log output
  go.mod
  go.sum
  internal/msggateway/hub_server.go
  internal/push/offlinepush/dummy/push.go
Labels: size/S
