Repository openimsdk/open-im-server, pull requests merged in 2024-01, with the labels that each got.

#1646 fix openim-admin images name
  docker-compose.yml
  pkg/common/discoveryregister/kubernetes/kubernetes.go
Labels: size/S

#1651 feat: support websocket first message method response code
  internal/msggateway/constant.go
  internal/msggateway/n_ws_server.go
Labels: size/L

#1648 feat: fix openim server install scripts
  scripts/install-im-server.sh
Labels: size/S

#1655 fix: modify dismissed group's status.
  pkg/common/db/controller/group.go
  pkg/common/db/mgo/group.go
  pkg/common/db/mgo/group_member.go
  pkg/common/db/table/relation/group.go
Labels: size/S

#1660 fix: rIssue with Asset Uploading for Official Releases in GoReleaser Action v4 - release openim version not auto build
  build/goreleaser.yaml
Labels: size/S

#1653 fix: fix the search_notification_account api return result
  internal/rpc/user/user.go
Labels: size/XS

#1663 fix: update Notification update resp
  go.mod
  go.sum
  internal/rpc/user/user.go
  scripts/install-im-server.sh
Labels: size/S

#1664 fix: fix the imAdmin permission
  internal/rpc/user/user.go
  pkg/authverify/token.go
  pkg/common/db/controller/user.go
  pkg/common/db/mgo/user.go
  pkg/common/db/table/relation/user.go
  pkg/rpcclient/user.go
Labels: size/S

#1666 fix: fix the imAdmin permission and searchNoficitaion resp
  go.mod
  internal/rpc/user/user.go
  pkg/authverify/token.go
  pkg/common/db/controller/user.go
  pkg/common/db/mgo/user.go
  pkg/common/db/table/relation/user.go
  pkg/rpcclient/user.go
Labels: size/M

#1670 Update env-template.yaml
  deployments/templates/env-template.yaml
Labels: size/S

#1674 feat(release-v3.5): fix openim docker start openim server internal port lock
  build/goreleaser.yaml
  docker-compose.yml
  go.mod
  go.sum
  internal/msggateway/constant.go
  internal/msggateway/n_ws_server.go
  pkg/common/db/controller/group.go
  pkg/common/db/mgo/group.go
  pkg/common/db/mgo/group_member.go
  pkg/common/db/table/relation/group.go
  pkg/common/discoveryregister/kubernetes/kubernetes.go
  scripts/docker-start-all.sh
  scripts/install-im-server.sh
Labels: size/L

#1673 feat(main): fix openim docker start openim server internal port lock
  pkg/authverify/token.go
  scripts/docker-start-all.sh
Labels: size/S

#1672 fix: dissmissGroup and lack of keyword bug
  go.mod
  go.sum
  internal/rpc/group/group.go
Labels: size/M

#1678 fix: dissmissGroup and lack of keyword bug
  go.mod
  internal/rpc/group/group.go
Labels: size/M

#1683 Update docker-start-all.sh
  scripts/docker-start-all.sh
Labels: size/S

#1684 MongoDB supports non-root users
  deployments/templates/env-template.yaml
  deployments/templates/openim.yaml
  docker-compose.yml
  pkg/common/db/unrelation/mongo.go
  scripts/install/environment.sh
  scripts/mongo-init.sh
  tools/component/component.go
Labels: size/M

#1679 Update docker-start-all.sh fix MSG_TRANSFER_PROM_PORT
  deployments/templates/env-template.yaml
  scripts/docker-start-all.sh
Labels: size/S

#1690 fix openim config mongo passwd env
  docs/contrib/environment.md
  pkg/common/db/unrelation/mongo.go
  scripts/install/dependency.sh
Labels: size/S

#1689 Fix(main): fix openim config from mongo password env upgrade openim build CICD
  .github/workflows/openimci.yml
  docs/contrib/environment.md
  pkg/common/db/unrelation/mongo.go
  scripts/install-im-server.sh
  scripts/install/dependency.sh
Labels: size/M

#1692 Request for Assistance with PR Title and Description Update cla.yml
  .github/workflows/cla.yml
Labels: size/XS

#1696 Enhancements to Script Variables and Logic in OpenIM, Including dig Detection and Mongo Startup Checks
  .github/workflows/docker-buildx.yml
  .github/workflows/e2e-test.yml
  .github/workflows/openimci.yml
  deployments/templates/env-template.yaml
  docker-compose.yml
  docs/contrib/environment.md
  docs/contrib/images.md
  docs/contrib/version.md
  pkg/common/config/version
  pkg/msgprocessor/conversation.go
  pkg/msgprocessor/options.go
  scripts/genconfig.sh
  scripts/install-im-server.sh
  scripts/install/environment.sh
  scripts/lib/util.sh
  scripts/make-rules/common.mk
  scripts/mongo-init.sh
Labels: size/L

#1705 feat: send msg at text
  internal/api/msg.go
Labels: size/XS

#1712 fix: fix some bug
  go.mod
  go.sum
  internal/rpc/user/user.go
  pkg/common/db/controller/user.go
  pkg/common/db/mgo/user.go
  pkg/common/db/table/relation/user.go
Labels: size/L

#1710 fix: fix some bug
  .github/workflows/openimci.yml
  go.mod
  go.sum
  internal/rpc/user/user.go
  pkg/common/db/controller/user.go
  pkg/common/db/mgo/user.go
  pkg/common/db/table/relation/user.go
Labels: size/L

#1714 update: update readme
  README-zh_CN.md
  README.md
Labels: size/L

#1719 fix: group messages sync failed.
  pkg/common/db/controller/conversation.go
Labels: size/XS

#1729 fix: fix the getSortedConversationList api
  go.mod
  internal/api/conversation.go
  internal/api/route.go
  internal/rpc/conversation/conversaion.go
  internal/rpc/user/user.go
Labels: size/M

#1681 update usercommand and fix callback
  deployments/templates/openim.yaml
  internal/api/route.go
  internal/api/user.go
  internal/push/callback.go
  internal/push/push_to_client.go
  internal/rpc/friend/friend.go
  internal/rpc/group/callback.go
  internal/rpc/group/group.go
  internal/rpc/msg/callback.go
  internal/rpc/msg/send.go
  internal/rpc/user/user.go
  pkg/callbackstruct/constant.go
  pkg/common/config/config.go
  pkg/common/db/cache/friend.go
  pkg/common/db/controller/friend.go
  pkg/common/db/controller/user.go
  pkg/common/db/mgo/friend.go
  pkg/common/db/mgo/user.go
  pkg/common/db/table/relation/friend.go
  pkg/common/db/table/relation/user.go
  pkg/rpcclient/notification/friend.go
  pkg/rpcclient/notification/user.go
Labels: size/L

#1725 fix: fix the GetSortedConversationList
  go.mod
  go.sum
  internal/api/conversation.go
  internal/api/route.go
  internal/rpc/conversation/conversaion.go
  internal/rpc/user/user.go
Labels: size/M

#1736 fix: fix the mongo search error
  pkg/common/db/mgo/user.go
Labels: size/XS

#1737 fix: fix the mongo search error
  pkg/common/db/mgo/user.go
Labels: size/XS

#1741 fix: GroupApplicationRejectedNotification not notification apply for userID
  pkg/rpcclient/notification/group.go
Labels: size/S

#1745 Update util.sh
  scripts/lib/util.sh
Labels: size/S

#1747 fix: NotificationUserInfoUpdate not notified
  internal/rpc/group/group.go
Labels: size/XS

#1740 fix: GroupApplicationRejectedNotification not notification apply for userID
  internal/rpc/group/group.go
  pkg/rpcclient/notification/group.go
Labels: size/S

#1748 docs: update oepnim docs openim-tools images
  scripts/install/openim-tools.sh
Labels: size/XS

#1721 🚀 Enhancements in Offline Deployment Documentation, CICD Process Upgrades, Deployment Optimization, and Additional Fixes
  .devcontainer /README.md
  .devcontainer /devcontainer.json
  .github/workflows/e2e-test.yml
  .github/workflows/openimci.yml
  CHANGELOG/CHANGELOG-3.4.md
  CHANGELOG/CHANGELOG-3.5.0.md
  CHANGELOG/CHANGELOG-3.5.md
  README.md
  assets/README.md
  cmd/openim-api/main.go
  docker-compose.yml
  docs/contrib/environment.md
  docs/contrib/gitcherry-pick.md
  docs/contrib/github-workflow.md
  docs/contrib/init-config.md
  docs/contrib/mac-developer-deployment-guide.md
  docs/contrib/offline-deployment.md
  docs/contrib/prometheus-grafana.md
  docs/contrib/release.md
  go.work
  pkg/common/prommetrics/gin_api.go
  pkg/common/prommetrics/prommetrics.go
  scripts/.spelling_failures
  scripts/build-all-service.sh
  scripts/check-all.sh
  scripts/common.sh
  scripts/ensure-tag.sh
  scripts/genconfig.sh
  scripts/install/environment.sh
  scripts/install/openim-man.sh
  scripts/install/openim-tools.sh
  scripts/lib/chat.sh
  scripts/lib/golang.sh
  scripts/lib/init.sh
  scripts/lib/release.sh
  scripts/lib/util.sh
  scripts/make-rules/common.mk
  scripts/make-rules/tools.mk
  scripts/release.sh
  scripts/stop-all.sh
  scripts/update-generated-docs.sh
  scripts/update-yamlfmt.sh
  scripts/verify-shellcheck.sh
  scripts/verify-spelling.sh
  scripts/verify-yamlfmt.sh
  test/typecheck/typecheck.go
  test/wrktest.sh
  tools/changelog/changelog.go
  tools/component/component.go
  tools/formitychecker/README.md
  tools/formitychecker/checker/checker.go
  tools/formitychecker/config/config.go
  tools/formitychecker/formitychecker.go
  tools/formitychecker/go.mod
  tools/imctl/imctl.go
  tools/up35/pkg/convert.go
  tools/up35/pkg/pkg.go
  tools/yamlfmt/OWNERS
Labels: size/XXL

#1755 update release-v3.5
  scripts/check-all.sh
  scripts/lib/util.sh
  tools/component/component.go
Labels: size/XXL

#1756 Rename devcontainer.json to devcontainer.json
  .devcontainer/devcontainer.json
Labels: size/XS

#1757 Rename README.md to README.md
  .devcontainer/README.md
Labels: size/XS

#1758 Update openim-tools.sh tools scripts images
  scripts/install/openim-tools.sh
Labels: size/XS

#1760 Update docker-compose.yml
  docker-compose.yml
Labels: size/XS

#1759 Update docker-compose.yml
  docker-compose.yml
Labels: size/XS

#1761 fix: mac deployment
  scripts/lib/util.sh
Labels: size/XS

#1763 Stability Enhancement: Pin Docker Compose Images for minio and openim-web
  docker-compose.yml
Labels: size/L

#1762 Stability Enhancement: Pin Docker Compose Images for minio and openim-web
  docker-compose.yml
Labels: size/M

#1771 feat: send msg at text (#1705)
  internal/api/msg.go
Labels: size/XS

#1750 fix(realease-v3.5): add more cases for get_users api, so it accept users in older version
  internal/rpc/user/user.go
  pkg/common/db/controller/user.go
  pkg/common/db/mgo/user.go
  pkg/common/db/table/relation/user.go
Labels: size/S

#1751 fix(main): add more cases for get_users api, so it accept users in older version. feat(main): also add search functionality
  go.mod
  internal/rpc/user/user.go
  pkg/common/db/controller/user.go
  pkg/common/db/mgo/user.go
  pkg/common/db/table/relation/user.go
Labels: size/M

#1776 Update docker-compose.yaml support arm/v6, arm/v8
  docker-compose.yml
Labels: size/XS

#1786 fix: update nick name field for get_user
  go.mod
  internal/rpc/user/user.go
  pkg/common/db/controller/user.go
  pkg/common/db/mgo/user.go
  pkg/common/db/table/relation/user.go
Labels: size/S

#1790 fix: change the afterSendSingleMsg config and fix CallbackSingleMsgRead unused problem
  deployments/templates/openim.yaml
  internal/rpc/msg/as_read.go
  pkg/callbackstruct/message.go
Labels: size/S

#1794 feat: Enhance Script Details and Add MacOS Compatibility with Documentation Updates
  .devcontainer/devcontainer.json
  assets/colors.md
  pkg/common/config/parse.go
  pkg/util/flag/flag.go
  pkg/util/genutil/genutil.go
  pkg/util/genutil/genutil_test.go
  scripts/docker-start-all.sh
  scripts/install/openim-msgtransfer.sh
  scripts/install/openim-rpc.sh
  scripts/start-all.sh
Labels: size/L

#1795 feat: Enhance Mac Deployment for Chat with Containerization and Documentation Updates
  docker-compose.yml
  docs/contrib/mac-developer-deployment-guide.md
Labels: size/M

#1806 Fix(release-v3.5) Enhance Component Monitoring with Dual Logging to Screen and File
  scripts/install/openim-tools.sh
Labels: size/XS

#1817 fix: fix openim-server scripts and optimize build date
  .github/workflows/pull-request.yml
  .github/workflows/sync-release.yml
  .github/workflows/sync.yml
  scripts/lib/logging.sh
Labels: size/S

#1775 Feature: add direct connect mode with zookeeper, etcd, and k8s
  internal/api/route.go
  internal/msgtransfer/init.go
  internal/rpc/user/user.go
  internal/tools/msg.go
  pkg/common/discoveryregister/direct/directResolver.go
  pkg/common/discoveryregister/direct/directconn.go
  pkg/common/discoveryregister/discoveryregister.go
  pkg/common/discoveryregister/discoveryregister_test.go
  pkg/common/discoveryregister/kubernetes/kubernetes.go
  pkg/common/startrpc/start.go
Labels: size/L

#1819 feat: Enhanced Automation for OpenIM Advanced CICD and GitOps Support
  build/images/openim-rpc-encryption/Dockerfile
  build/images/openim-rpc-extend-msg/Dockerfile
  scripts/install-im-server.sh
  scripts/lib/release.sh
  scripts/make-rules/image.mk
  scripts/release.sh
Labels: size/L

#1823 fix: conversation aggregate find error
  go.mod
  go.sum
  pkg/common/db/mgo/conversation.go
Labels: size/M

#1822 fix: conversation aggregate find error
  go.mod
  go.sum
  pkg/common/db/mgo/conversation.go
Labels: size/S

#1824 feat: add pull request set workflows
  .github/workflows/pull-request.yml
Labels: size/M

#1827 [Auto PR] Bump League Patch in '"base branch'
  .github/workflows/pull-request.yml
Labels: size/S

#1816 fix duplicated offline push
  internal/push/push_to_client.go
Labels: size/S

#1830 feat: del the manager configure and it's initializestatement
  deployments/templates/config.yaml
  docs/contrib/environment.md
  internal/push/push_to_client.go
  internal/rpc/msg/revoke.go
  internal/rpc/msg/verify.go
  internal/rpc/user/user.go
  pkg/authverify/token.go
  scripts/install/environment.sh
Labels: size/M

#1833 fix(docker-compose): Update the env template to uncomment the mongo port
  deployments/templates/env-template.yaml
Labels: size/XS

#1841 Delete build/images/openim-rpc-extend-msg directory
  build/images/openim-rpc-extend-msg/Dockerfile
Labels: size/M

#1842 Delete build/images/openim-rpc-encryption directory
  build/images/openim-rpc-encryption/Dockerfile
Labels: size/M

#1843 Update offline-deployment.md openim offine deployment docs
  docs/contrib/offline-deployment.md
Labels: size/S

#1847 Update environment.md fix environment mongo username
  docs/contrib/environment.md
Labels: size/XS
