Repository openimsdk/open-im-server, pull requests merged in 2024-11, with the labels that each got.

#2822 Update login policy
  go.mod
  go.sum
  internal/msggateway/ws_server.go
  pkg/common/storage/controller/auth.go
Labels: size/M

#2826 build: implement version file update when release.
  .github/workflows/.github/workflows/update-version-file-on-release.yml
Labels: size/M

#2824 feat: support stream message
  go.mod
  go.sum
  internal/api/msg.go
  internal/api/router.go
  internal/rpc/msg/notification.go
  internal/rpc/msg/send.go
  internal/rpc/msg/server.go
  internal/rpc/msg/stream_msg.go
  pkg/apistruct/msg.go
  pkg/common/storage/controller/stream_msg.go
  pkg/common/storage/database/mgo/stream_msg.go
  pkg/common/storage/database/name.go
  pkg/common/storage/database/stream_msg.go
  pkg/common/storage/model/stream_msg.go
  tools/streammsg/main.go
Labels: size/L

#2836 fix: Write back message to Redis
  pkg/common/storage/cache/redis/msg.go
  pkg/common/storage/controller/msg.go
Labels: size/S

#2839 fix: ws write io timeout
  internal/msggateway/client.go
Labels: size/XS

#2842 fix: get group return repeated result
  pkg/common/storage/database/mgo/group.go
Labels: size/XS

#2838 fix: SetConversations can update new conversation
  internal/rpc/conversation/conversation.go
Labels: size/XS

#2856 feat: merge js sdk
  config/openim-msggateway.yml
  config/openim-push.yml
  internal/msggateway/client.go
  internal/msggateway/constant.go
  internal/msggateway/context.go
  internal/msggateway/encoder.go
  internal/msggateway/hub_server.go
  internal/msggateway/message_handler.go
  internal/msggateway/ws_server.go
  pkg/common/storage/controller/auth.go
Labels: size/L

#2858 build: update mongo and kafka start logic.
  .env
  Dockerfile
  config/mongodb.yml
  docker-compose.yml
  go.mod
  go.sum
  pkg/common/config/config.go
  scripts/create-topic.sh
  scripts/mongo-init.sh
  tools/check-component/main.go
Labels: size/L

#2844 fix(push): push content with jpush
  config/openim-push.yml
  internal/push/offlinepush/jpush/body/notification.go
  internal/push/offlinepush/jpush/push.go
  internal/push/offlinepush_handler.go
  internal/push/push_handler.go
Labels: size/M

#2861 fix #2860 migrate jpns to jpush
  config/openim-push.yml
  deployments/templates/config.yaml
  docs/contrib/environment.md
  internal/push/offlinepush/jpush/body/notification.go
  internal/push/offlinepush/jpush/push.go
  pkg/common/config/config.go
Labels: size/M

#2871 fix: Remove admin token in redis
  internal/rpc/auth/auth.go
  pkg/common/storage/controller/auth.go
  pkg/common/storage/controller/msg.go
Labels: size/M

#2869 build: create changelog tool and workflows.
  .github/workflows/changelog.yml
  tools/changelog/changelog.go
  tools/changelog/main.go
Labels: size/XL

#2862 Fix Push2User webhookBeforeOfflinePush
  internal/push/push_handler.go
Labels: size/S

#2850 feat: Print Panic Log
  .github/workflows/go-build-test.yml
  internal/api/router.go
  internal/msggateway/client.go
  internal/msgtransfer/init.go
  internal/msgtransfer/online_history_msg_handler.go
  internal/rpc/msg/send.go
  pkg/rpccache/subscriber.go
Labels: size/M

#2837 fix: move workflow to correct path
  .github/workflows/update-version-file-on-release.yml
Labels: size/XS

#2825 fix: del login Policy
  config/openim-push.yml
  config/share.yml
  go.mod
  go.sum
  internal/push/offlinepush/dummy/push.go
  internal/push/offlinepush/offlinepusher.go
  internal/rpc/msg/as_read.go
  internal/rpc/msg/seq.go
  pkg/common/config/config.go
  pkg/common/storage/controller/auth.go
  pkg/common/storage/controller/msg.go
Labels: size/M

#2876 fix: Wrong Redis Error Check
  internal/rpc/msg/as_read.go
  internal/rpc/msg/seq.go
  pkg/common/storage/controller/msg.go
Labels: size/XS

#2877 build: update version to v3.8.2
  version/version
Labels: size/XS

#2881 fix: minor log typo
  pkg/common/storage/cache/redis/conversation.go
Labels: size/XS

#2884 fix: webhookAfterSingleMsgRead will be called correctly
  internal/rpc/msg/as_read.go
Labels: size/S

#2885 fix: webhookBeforeSendSingleMsg will call before black and friend check
  internal/rpc/msg/send.go
  internal/rpc/msg/verify.go
Labels: size/XS

#2883 revert: write msg to redis
  pkg/common/storage/controller/msg.go
Labels: size/S

#2887 build: update Server version.
  version/version
Labels: size/XS

#2893 chore: update admin front image version
  .env
Labels: size/XS

#2891 fix: Wrong Redis Error Check
  internal/rpc/auth/auth.go
  internal/rpc/msg/as_read.go
  pkg/common/storage/controller/msg.go
Labels: size/S

#2901 fix: improve crontask delete outdated Data.
  Dockerfile
  config/openim-crontask.yml
  go.mod
  go.sum
  internal/msggateway/hub_server.go
  internal/push/push.go
  internal/rpc/auth/auth.go
  internal/rpc/conversation/conversation.go
  internal/rpc/group/group.go
  internal/rpc/msg/server.go
  internal/rpc/relation/friend.go
  internal/rpc/third/s3.go
  internal/rpc/third/third.go
  internal/rpc/user/user.go
  internal/tools/cron_task.go
  pkg/common/config/config.go
  pkg/common/storage/controller/s3.go
  pkg/common/storage/database/mgo/object.go
  pkg/common/storage/database/object.go
Labels: size/L
