Repository openimsdk/open-im-server, pull requests merged in 2024-06, with the labels that each got.

#2325 refactor: db cache batch refactor and batch consume message.
  config/redis.yml
  go.mod
  go.sum
  internal/api/init.go
  internal/msggateway/hub_server.go
  internal/msggateway/init.go
  internal/msgtransfer/init.go
  internal/msgtransfer/online_history_msg_handler.go
  internal/msgtransfer/online_msg_to_mongo_handler.go
  internal/push/push_handler.go
  internal/rpc/group/group.go
  internal/rpc/group/notification.go
  internal/rpc/msg/server.go
  pkg/common/config/config.go
  pkg/common/startrpc/start.go
  pkg/common/storage/cache/cachekey/msg.go
  pkg/common/storage/cache/conversation.go
  pkg/common/storage/cache/msg.go
  pkg/common/storage/cache/redis/batch_handler.go
  pkg/common/storage/cache/redis/conversation.go
  pkg/common/storage/cache/redis/lua_script.go
  pkg/common/storage/cache/redis/lua_script_test.go
  pkg/common/storage/cache/redis/meta_cache.go
  pkg/common/storage/cache/redis/msg.go
  pkg/common/storage/cache/redis/msg_test.go
  pkg/common/storage/cache/redis/redis_shard_manager.go
  pkg/common/storage/cache/user.go
  pkg/common/storage/controller/msg.go
  pkg/common/storage/database/mgo/msg.go
  pkg/tools/batcher/batcher.go
  pkg/tools/batcher/batcher_test.go
Labels: size/XXL

#2327 Add a retry mechanism to mongo init
  scripts/mongo-init.sh
Labels: size/M

#2328 Add a retry mechanism to mongo init
  scripts/mongo-init.sh
Labels: size/M

#2345 feat: implement to invalid token when forceKickOff user.
  internal/rpc/auth/auth.go
Labels: size/S

#2347 fix:FCM push failed will return error
  internal/push/offlinepush/fcm/push.go
Labels: size/S

#2341 Fix group and config
  config/openim-push.yml
  go.mod
  go.sum
  internal/push/offlinepush/fcm/push.go
  internal/push/offlinepush/offlinepusher.go
  internal/push/push.go
  pkg/common/cmd/push.go
  pkg/common/cmd/root.go
  pkg/common/config/config.go
Labels: size/M

#2352 fix:create auth token can add expire time
  internal/rpc/auth/auth.go
  pkg/common/storage/cache/redis/token.go
  pkg/common/storage/cache/token.go
  pkg/common/storage/controller/auth.go
Labels: size/M

#2371 fix: message can store Ex
  internal/api/msg.go
  pkg/apistruct/manage.go
Labels: size/XS

#2370 feat: add webhook AttentionIds
  config/webhooks.yml
  internal/rpc/msg/callback.go
  pkg/common/config/config.go
Labels: size/S

#2367 fix: group application
  internal/rpc/group/notification.go
Labels: size/M

#2372 fix: message can store Ex (#2371)
  internal/api/msg.go
  pkg/apistruct/manage.go
Labels: size/XS
