Repository openimsdk/open-im-server, pull requests merged in 2024-08, with the labels that each got.

#2468 fix: online status renewal
  internal/msggateway/online.go
  internal/msggateway/user_map.go
  internal/push/push_handler.go
Labels: size/S

#2466 feat: implement scheduled destruct msgs feature in cron task.
  go.mod
  go.sum
  internal/rpc/conversation/conversaion.go
  internal/rpc/msg/clear.go
  internal/rpc/msg/server.go
  internal/tools/cron_task.go
  pkg/common/convert/conversation.go
  pkg/rpcclient/conversation.go
Labels: size/L

#2473 fix: the local cache obtained can be modified
  internal/msggateway/user_map.go
  pkg/common/storage/database/mgo/msg.go
  pkg/rpccache/common.go
  pkg/rpccache/conversation.go
  pkg/rpccache/friend.go
  pkg/rpccache/group.go
  pkg/rpccache/online.go
  pkg/rpccache/user.go
Labels: size/L

#2476 chore: revert tool pkg version.
  go.mod
  go.sum
Labels: size/XS

#2477 chore: revert tool pkg version. (#2476)
  go.mod
  go.sum
Labels: size/XS

#2484 feat: update grafana template
  config/grafana-template/Demo.json
Labels: size/XXL

#2487 feat: update web front images
  .env
Labels: size/XS

#2492 fix: import del cache
  pkg/common/storage/controller/friend.go
Labels: size/XS

#2493 fix:update recive name to same
  pkg/rpcclient/friend.go
Labels: size/XS

#2499 fix: fix-validate message.
  pkg/apistruct/msg.go
Labels: size/XS

#2501 feat:add message send time in callback
  internal/rpc/msg/callback.go
  pkg/callbackstruct/common.go
Labels: size/XS

#2511 refactor: refactor workflows structure.
  .github/.codecov.yml
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/deployment.yml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/other.yml
  .github/ISSUE_TEMPLATE/rfc.md
  .github/code-language-detector.yml
  .github/labels.yml
  .github/release-drafter.yml
  .github/standardizer.yml
  .github/sync-release.yml
  .github/sync.yml
  .github/weekly-digest.yml
  .github/workflows/auto-assign-issue.yml
  .github/workflows/auto-gh-pr.yml
  .github/workflows/auto-invite-comment.yml
  .github/workflows/auto-tag.yml
  .github/workflows/bot-auto-cherry-pick.yml
  .github/workflows/bot-cherry-pick.yml
  .github/workflows/check-coverage.bak
  .github/workflows/cla-assistant.yml
  .github/workflows/cla.yml
  .github/workflows/code-language-detector.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/comment-check.yml
  .github/workflows/create-branch-on-tag.bak
  .github/workflows/depsreview.yaml
  .github/workflows/docker-buildx.bak
  .github/workflows/e2e-test.bak
  .github/workflows/go-build-test.yml
  .github/workflows/golangci-lint.bak
  .github/workflows/gosec.yml
  .github/workflows/issue-robot.yml
  .github/workflows/lock-issue.bak
  .github/workflows/milestone.yml
  .github/workflows/opencommit.yml
  .github/workflows/openimci.yml
  .github/workflows/project-progress.yml
  .github/workflows/publish-docker-image.yml
  .github/workflows/pull-request.bak
  .github/workflows/release-drafter.yml
  .github/workflows/release.bak
  .github/workflows/remove-unused-labels.yml
  .github/workflows/reopen-issue.yml
  .github/workflows/sync-release.bak
  .github/workflows/sync.bak
  .github/workflows/user-first-interaction.yml
  .golangci.yml
Labels: size/XXL

#2513 fix: solve uncorrect outdated msg get.
  .github/workflows/help-comment-issue.yml
  internal/rpc/conversation/conversaion.go
  internal/rpc/msg/clear.go
  internal/tools/cron_task.go
  pkg/common/storage/controller/msg.go
  pkg/common/storage/database/mgo/msg.go
  pkg/common/storage/database/msg.go
Labels: size/L

#2521 feat: update issue translator in workflows
  .github/workflows/issue-translator.yml
Labels: size/S

#2532 fix: pass getMinioImageThumbnailKey error.
  internal/rpc/third/s3.go
Labels: size/XS

#2534 docs: update CLA comments contents.
  .github/workflows/go-build-test.yml
  CONTRIBUTING-zh_CN.md
  CONTRIBUTING.md
Labels: size/XS

#2525 fix Details
  internal/api/msg.go
  internal/msgtransfer/init.go
  internal/msgtransfer/online_history_msg_handler.go
  internal/msgtransfer/online_msg_to_mongo_handler.go
  internal/push/onlinepusher.go
  internal/push/push_handler.go
  pkg/common/storage/controller/msg.go
  pkg/common/storage/database/mgo/msg.go
  pkg/common/storage/model/msg.go
Labels: size/M

#2542 Fix: solve conversation blocking in private chat when non friendship.
  .github/workflows/cla-assistant.yml
  CONTRIBUTING-zh_CN.md
  CONTRIBUTING.md
  internal/rpc/conversation/conversaion.go
Labels: size/M

#2494 fix:get msg error
  pkg/rpcclient/msg.go
Labels: size/XS

#2496 fix:mgo delete err
  pkg/common/storage/database/mgo/user.go
Labels: size/XS

#2495 fix:doPut error
  tools/url2im/pkg/manage.go
Labels: size/XS

#2544 feat: update set conversation logic.
  internal/rpc/conversation/conversaion.go
Labels: size/L

#2548 Groupmsg
  config/openim-rpc-group.yml
  go.mod
  go.sum
  internal/rpc/conversation/conversaion.go
  internal/rpc/group/group.go
  internal/rpc/group/notification.go
  pkg/common/config/config.go
  pkg/rpcclient/conversation.go
Labels: size/L

#2552 feat: implement `SetGroupInfoEX` interface.
  config/webhooks.yml
  go.mod
  go.sum
  internal/api/group.go
  internal/api/router.go
  internal/api/user.go
  internal/rpc/group/callback.go
  internal/rpc/group/db_map.go
  internal/rpc/group/group.go
  internal/rpc/user/user.go
  pkg/callbackstruct/constant.go
  pkg/callbackstruct/group.go
  pkg/common/config/config.go
Labels: size/XL

#2556 fix: set min seq
  go.mod
  go.sum
  internal/rpc/group/notification.go
  internal/rpc/msg/seq.go
  pkg/rpcclient/msg.go
Labels: size/M

#2559 Fix push
  config/openim-api.yml
  config/openim-msggateway.yml
  config/openim-msgtransfer.yml
  config/openim-push.yml
  config/openim-rpc-auth.yml
  config/openim-rpc-conversation.yml
  config/openim-rpc-friend.yml
  config/openim-rpc-group.yml
  config/openim-rpc-msg.yml
  config/openim-rpc-third.yml
  config/openim-rpc-user.yml
  config/prometheus.yml
  internal/msggateway/client.go
  internal/push/push_handler.go
  pkg/rpcclient/msg.go
  start-config.yml
Labels: size/M

#2558 fix: read seq is written to mongo, online status redis cluster is supported
  go.sum
  internal/msgtransfer/online_history_msg_handler.go
  internal/msgtransfer/online_msg_to_mongo_handler.go
  internal/push/a_test.go
  pkg/apistruct/msg_test.go
  pkg/common/storage/cache/redis/online.go
  pkg/common/storage/cache/redis/online_test.go
  pkg/common/storage/cache/redis/seq_user.go
  pkg/common/storage/cache/seq_user.go
  pkg/common/storage/controller/msg.go
  pkg/common/storage/database/mgo/seq_user.go
Labels: size/L

#2562 fix: invitation to join group notification opuser is null
  internal/rpc/group/notification.go
Labels: size/S

#2564 Fix set convsation
  internal/rpc/conversation/conversaion.go
Labels: size/S

#2566 fix: delay deleteObject func.
  internal/tools/cron_task.go
Labels: size/M

#2568 fix: memory queue optimization
  internal/rpc/relation/friend.go
  pkg/common/storage/controller/friend.go
  pkg/rpcclient/msg.go
Labels: size/S
