Repository openimsdk/open-im-server, pull requests merged in 2024-03, with the labels that each got.

#1980 Enhance Documentation for OpenIM Configuration and Linters Settings
  docs/contrib/go-code.md
Labels: size/L

#1968 fix: Revolutionary Bug Fixes in API Testing with 'RP': Solving Glitches with the Power of 'make test'
  scripts/install/test.sh
Labels: size/M

#1984 docs: update openim server readme github codespaces
  README.md
Labels: size/XS

#1989 feat: Update .golangci.yml Configuration for Improved Linting Efficiency
  .golangci.yml
Labels: size/M

#1976 Change back to err name
  internal/msgtransfer/init.go
  internal/rpc/friend/black.go
  internal/rpc/friend/friend.go
  internal/rpc/group/group.go
  internal/rpc/msg/as_read.go
  internal/rpc/msg/revoke.go
  internal/rpc/msg/send.go
  internal/rpc/msg/server.go
  internal/rpc/third/s3.go
  internal/rpc/third/third.go
  internal/rpc/user/user.go
Labels: size/M

#1995 feat: optimize openim make lint style format
  internal/msgtransfer/online_history_msg_handler.go
  internal/push/offlinepush/fcm/push.go
  pkg/common/discoveryregister/kubernetes/kubernetes.go
  pkg/common/kafka/producer.go
  test/e2e/api/token/token.go
  test/e2e/framework/helpers/chat/chat.go
Labels: size/M

#2001 fix: fix the component logic
  go.mod
  go.sum
  tools/component/component.go
Labels: size/L

#2005 fix: wrap the error of group user and thrid
  internal/rpc/group/group.go
  internal/rpc/third/s3.go
  internal/rpc/third/third.go
  internal/rpc/user/user.go
  pkg/common/db/cache/meta_cache.go
  pkg/common/db/cache/msg.go
  pkg/common/db/mgo/object.go
  pkg/common/db/mgo/user.go
  pkg/common/db/s3/minio/image.go
  pkg/common/db/unrelation/mongo.go
  pkg/common/discoveryregister/direct/directconn.go
  pkg/rpcclient/msg.go
  tools/up35/pkg/pkg.go
Labels: size/M

#2009 fix: remove unnecessary error handling to avoid sending failed notifi…
  pkg/rpcclient/notification/group.go
Labels: size/XS

#2014 Optimizing Docker Log Output Detection
  scripts/check-all.sh
  scripts/docker-start-all.sh
  scripts/lib/logging.sh
  scripts/start-all.sh
Labels: size/S

#2018 Optimizing Docker Log Output
  scripts/check-all.sh
  scripts/lib/logging.sh
  scripts/lib/util.sh
  scripts/start-all.sh
Labels: size/S

#2026 Execute after the component check succeeds && minio.Enable is not configured to use MinIO
  scripts/install/openim-tools.sh
  scripts/start-all.sh
  tools/component/component.go
Labels: size/M

#2030 Log redirection causes incorrect program exit status.
  scripts/install/openim-tools.sh
Labels: size/XS

#2031 Log redirection causes incorrect program exit status.
  CHANGELOG/CHANGELOG-3.6.md
  pkg/common/config/version
  scripts/install/openim-tools.sh
Labels: size/S

#2041 Error not handled
  scripts/install/openim-tools.sh
  scripts/lib/util.sh
  tools/component/component.go
Labels: size/M

#2040 Error not handled
  scripts/lib/util.sh
  tools/component/component.go
Labels: size/M

#2036 feat: add local cache for high frequency reads
  deployments/templates/config.yaml
  go.mod
  go.sum
  internal/msggateway/callback.go
  internal/msggateway/hub_server.go
  internal/push/push_rpc_server.go
  internal/push/push_to_client.go
  internal/rpc/conversation/conversaion.go
  internal/rpc/friend/friend.go
  internal/rpc/msg/as_read.go
  internal/rpc/msg/revoke.go
  internal/rpc/msg/send.go
  internal/rpc/msg/server.go
  internal/rpc/msg/statistics.go
  internal/rpc/msg/sync_msg.go
  internal/rpc/msg/verify.go
  pkg/common/cachekey/black.go
  pkg/common/cachekey/conversation.go
  pkg/common/cachekey/friend.go
  pkg/common/cachekey/group.go
  pkg/common/cachekey/user.go
  pkg/common/config/config.go
  pkg/common/config/parse_test.go
  pkg/common/db/cache/black.go
  pkg/common/db/cache/config.go
  pkg/common/db/cache/conversation.go
  pkg/common/db/cache/friend.go
  pkg/common/db/cache/group.go
  pkg/common/db/cache/meta_cache.go
  pkg/common/db/cache/msg.go
  pkg/common/db/cache/user.go
  pkg/common/db/localcache/conversation.go
  pkg/common/db/localcache/doc.go
  pkg/common/db/localcache/group.go
  pkg/common/db/localcache/meta_local_cache.go
  pkg/common/db/mgo/conversation.go
  pkg/common/db/table/relation/conversation.go
  pkg/common/redispubsub/redispubliser.go
  pkg/common/redispubsub/redissubscriber.go
  pkg/localcache/cache.go
  pkg/localcache/cache_test.go
  pkg/localcache/go.mod
  pkg/localcache/link/link.go
  pkg/localcache/link/link_test.go
  pkg/localcache/lru/lru.go
  pkg/localcache/lru/lru_expiration.go
  pkg/localcache/lru/lru_lazy.go
  pkg/localcache/lru/lru_lazy_test.go
  pkg/localcache/lru/lru_slot.go
  pkg/localcache/option.go
  pkg/localcache/tool.go
  pkg/rpccache/common.go
  pkg/rpccache/conversation.go
  pkg/rpccache/friend.go
  pkg/rpccache/group.go
  pkg/rpccache/subscriber.go
  pkg/rpccache/user.go
  pkg/rpcclient/conversation.go
  pkg/rpcclient/friend.go
  pkg/rpcclient/group.go
Labels: size/XXL

#2033 Fix bug Remove duplicate function definitions
  scripts/lib/util.sh
Labels: size/M

#2044 Fix bug configGetEnv failed,err:string to int failed: strconv.Atoi: parsing "openim_v3": invalid syntaxr
  config/templates/env.template
  deployments/templates/env-template.yaml
  scripts/start-all.sh
  tools/component/component.go
Labels: size/XS

#2047 delete log for update images
  tools/component/component.go
Labels: size/XS

#2050 Feature: delete log for update images
  tools/component/component.go
Labels: size/XS

#2053 Bug: component check
  tools/component/component.go
Labels: size/M

#2054 Bug: component check
  go.sum
  tools/component/component.go
Labels: size/M

#2056 Bug: component check
  go.sum
  scripts/install/openim-tools.sh
  tools/component/component.go
Labels: size/M

#2063 Fix bug redis address
  Dockerfile
  tools/component/component.go
Labels: size/XS

#2065 Run in the background
  scripts/docker-start-all.sh
Labels: size/XS

#2068 fix: fix make lint error about scripts errout
  scripts/verify-shellcheck.sh
Labels: size/XS

#2069 fix: fix docker file images proxy
  Dockerfile
  build/images/openim-api/Dockerfile
  build/images/openim-cmdutils/Dockerfile
  build/images/openim-crontask/Dockerfile
  build/images/openim-msggateway/Dockerfile
  build/images/openim-msgtransfer/Dockerfile
  build/images/openim-push/Dockerfile
  build/images/openim-rpc-auth/Dockerfile
  build/images/openim-rpc-conversation/Dockerfile
  build/images/openim-rpc-friend/Dockerfile
  build/images/openim-rpc-group/Dockerfile
  build/images/openim-rpc-msg/Dockerfile
  build/images/openim-rpc-third/Dockerfile
  build/images/openim-rpc-user/Dockerfile
  build/images/openim-tools/component/Dockerfile
  build/images/openim-tools/openim-web/Dockerfile
Labels: size/M

#2074 fix: fix the bug of background, such as groups count error，fix Msgfield to contentType
  go.mod
  go.sum
  internal/api/route.go
  internal/rpc/group/group.go
  internal/rpc/msg/sync_msg.go
  internal/rpc/third/log.go
  pkg/common/db/mgo/group.go
  pkg/common/db/unrelation/msg.go
  scripts/install/test.sh
Labels: size/M

#2082 optimization: message remove options.
  internal/rpc/msg/verify.go
Labels: size/XS

#2083 optimization: message remove options.
  internal/rpc/msg/verify.go
Labels: size/XS

#2101 cicd: update e2e-test fix e2e and api test ci
  .github/workflows/e2e-test.yml
Labels: size/S

#2113 add github actions is create code-language-detector.yml
  .github/code-language-detector.yml
  .github/workflows/code-language-detector.yml
  go.work
  scripts/verify-annotation-language.sh
  tools/codescan/checker/checker.go
  tools/codescan/codescan.go
  tools/codescan/config.yaml
  tools/codescan/config/config.go
  tools/codescan/go.mod
Labels: size/L

#2076 docs: Update openim version management strategy, detailed design
  docs/contrib/version.md
Labels: size/XS

#2084 feat: golang fix apt test design
  .golangci.yml
  docker-compose.yml
  internal/api/msg.go
  internal/msggateway/context.go
  internal/msggateway/user_map.go
  internal/msgtransfer/online_history_msg_handler.go
  internal/push/offlinepush/getui/push.go
  internal/push/push_rpc_server.go
  internal/push/tools.go
  internal/rpc/friend/black.go
  internal/rpc/friend/friend.go
  internal/rpc/group/group.go
  pkg/rpcclient/notification/friend.go
  scripts/install/test.sh
Labels: size/L

#2090 fix: Add Descending Sort by Creation Time to Group Search & Fix Admin Update Error
  pkg/common/db/mgo/group.go
Labels: size/S

#2108 fix: Fix Incorrect Group Member Count in SearchMessage API group getGroupMemberIDs is 0 err
  internal/rpc/group/cache.go
  internal/rpc/group/group.go
  internal/rpc/msg/sync_msg.go
  pkg/authverify/token.go
  pkg/rpcclient/group.go
Labels: size/M

#2087 fix: conversation crash caused by non-existence
  internal/rpc/conversation/conversaion.go
  tools/component/component.go
Labels: size/M

#2091 fix: conversation crash caused by non-existence
  internal/rpc/conversation/conversaion.go
  tools/component/component.go
Labels: size/M

#2114 fix: Fix the callback after reading the group message
  internal/rpc/msg/callback.go
Labels: size/XS

#2124 feat: add scripts verify shell check
  internal/rpc/msg/callback.go
  scripts/verify-shellcheck.sh
Labels: size/XS

#2122 feat: remove tools/codescan catalog
  .github/code-language-detector.yml
  .github/workflows/code-language-detector.yml
  go.work
  scripts/verify-annotation-language.sh
  tools/codescan/checker/checker.go
  tools/codescan/codescan.go
  tools/codescan/config.yaml
  tools/codescan/config/config.go
  tools/codescan/go.mod
Labels: size/L

#2123 fix: fix docker file images proxy
  Dockerfile
  build/images/openim-api/Dockerfile
  build/images/openim-cmdutils/Dockerfile
  build/images/openim-crontask/Dockerfile
  build/images/openim-msggateway/Dockerfile
  build/images/openim-msgtransfer/Dockerfile
  build/images/openim-push/Dockerfile
  build/images/openim-rpc-auth/Dockerfile
  build/images/openim-rpc-conversation/Dockerfile
  build/images/openim-rpc-friend/Dockerfile
  build/images/openim-rpc-group/Dockerfile
  build/images/openim-rpc-msg/Dockerfile
  build/images/openim-rpc-third/Dockerfile
  build/images/openim-rpc-user/Dockerfile
  build/images/openim-tools/component/Dockerfile
  build/images/openim-tools/openim-web/Dockerfile
Labels: size/M

#2119 The check script is not compatible with Mac.
  Dockerfile
  scripts/lib/util.sh
  tools/component/component.go
Labels: size/XS

#2126 The check script is not compatible with Mac.
  scripts/lib/util.sh
Labels: size/XS

#2128 Fix Path Resolution Error for Root Directory .env File Generation Update env-template.yaml
  deployments/templates/env-template.yaml
Labels: size/XS

#2131 feat: set git cherry pick and Milestone
  .github/workflows/bot-auto-cherry-pick.yml
  .github/workflows/milestone.yml
Labels: size/S

#2132 Update bot-cherry-pick.yml
  .github/workflows/bot-cherry-pick.yml
Labels: size/M

#2129 releasev3.6: Automated cherry pick of #2128 upstream release v3.6
  deployments/templates/env-template.yaml
Labels: size/XS

#2140 feat: Remove Go Typecheck Tools Implement GitHub Actions Based Typecheck for OpenIM
  .github/workflows/openimci.yml
  go.work
  scripts/make-rules/tools.mk
  scripts/run-in-gopath.sh
  scripts/update-generated-docs.sh
  scripts/update-yamlfmt.sh
  scripts/verify-shellcheck.sh
  scripts/verify-spelling.sh
  scripts/verify-typecheck.sh
  scripts/verify-yamlfmt.sh
  test/typecheck/README.md
  test/typecheck/go.mod
  test/typecheck/go.sum
  test/typecheck/typecheck.go
  test/typecheck/typecheck_test.go
Labels: size/XL

#2154 docs: Optimize Deployment Speed for Users in China with Aliyun Image Registry
  docs/contrib/images.md
Labels: size/S
