Repository openimsdk/open-im-server, pull requests merged in 2024-02, with the labels that each got.

#1852 docs:Add multi-language README.md in ./docs/ file
  docs/README_ar.md
  docs/README_cs.md
  docs/README_da.md
  docs/README_de.md
  docs/README_el.md
  docs/README_eo.md
  docs/README_es.md
  docs/README_fa.md
  docs/README_fi.md
  docs/README_fr.md
  docs/README_hu.md
  docs/README_id.md
  docs/README_it.md
  docs/README_ja.md
  docs/README_ko.md
  docs/README_ml.md
  docs/README_nl.md
  docs/README_pl.md
  docs/README_pt_BR.md
  docs/README_ru.md
  docs/README_tr.md
  docs/README_ua.md
  docs/README_vi.md
  docs/README_zh_CN.md
  docs/README_zh_TW.md
Labels: size/XXL

#1848 docs: fix environments minio document parameter errors
  docs/contrib/environment.md
Labels: size/XS

#1846 Bug: replace the component check func by tools pkg
  go.mod
  go.sum
  pkg/rpcclient/third.go
  tools/component/component.go
Labels: size/L

#1862 fix: process add errors wrap.
  cmd/openim-api/main.go
  internal/msgtransfer/init.go
  internal/msgtransfer/online_history_msg_handler.go
  internal/msgtransfer/online_msg_to_mongo_handler.go
  internal/push/consumer_init.go
  internal/push/push_handler.go
  internal/push/push_rpc_server.go
  internal/rpc/msg/server.go
  internal/tools/cron_task.go
  internal/tools/msg.go
  pkg/common/db/cache/init_redis.go
  pkg/common/db/controller/msg.go
  pkg/common/db/mgo/conversation.go
  pkg/common/db/mgo/group.go
  pkg/common/db/mgo/group_member.go
  pkg/common/db/mgo/group_request.go
  pkg/common/db/mgo/user.go
  pkg/common/db/unrelation/mongo.go
  pkg/common/kafka/consumer_group.go
  pkg/common/kafka/producer.go
  pkg/common/startrpc/start.go
Labels: size/L

#1868 fix: Refactoring the code for component detection
  go.mod
  go.sum
  pkg/common/db/cache/init_redis.go
  pkg/common/db/unrelation/mongo.go
  pkg/common/discoveryregister/zookeeper/zookeeper.go
  pkg/common/kafka/consumer_group.go
  tools/component/component.go
Labels: size/L

#1860 feat: add architecture layers
  CONTRIBUTING-zh_CN.md
  CONTRIBUTING.md
  README-zh_CN.md
  README.md
  docs/README.md
  docs/README_ar.md
  docs/README_cs.md
  docs/README_da.md
  docs/README_de.md
  docs/README_el.md
  docs/README_eo.md
  docs/README_es.md
  docs/README_fa.md
  docs/README_fi.md
  docs/README_fr.md
  docs/README_hu.md
  docs/README_id.md
  docs/README_it.md
  docs/README_ja.md
  docs/README_ko.md
  docs/README_ml.md
  docs/README_nl.md
  docs/README_pl.md
  docs/README_pt_BR.md
  docs/README_ru.md
  docs/README_tr.md
  docs/README_ua.md
  docs/README_vi.md
  docs/README_zh_CN.md
  docs/README_zh_TW.md
  docs/contributing/CONTRIBUTING-JP.md
  docs/contributing/CONTRIBUTING-PL.md
  docs/images/Open-IM-Servers-on-System.png
  docs/images/Open-IM-Servers-on-docker.png
  docs/images/architecture-layers.png
  docs/images/build.png
  docs/images/docker_build.png
  docs/readme/README-UA.md
Labels: size/XXL

#1866 feat: Optimize openim scripts and standard output logs
  cmd/openim-api/main.go
  cmd/openim-cmdutils/main.go
  cmd/openim-crontask/main.go
  cmd/openim-msggateway/main.go
  cmd/openim-msgtransfer/main.go
  cmd/openim-push/main.go
  cmd/openim-rpc/openim-rpc-auth/main.go
  cmd/openim-rpc/openim-rpc-conversation/main.go
  cmd/openim-rpc/openim-rpc-friend/main.go
  cmd/openim-rpc/openim-rpc-group/main.go
  cmd/openim-rpc/openim-rpc-msg/main.go
  cmd/openim-rpc/openim-rpc-third/main.go
  cmd/openim-rpc/openim-rpc-user/main.go
  go.mod
  go.sum
  pkg/common/cmd/root.go
  pkg/common/db/unrelation/mongo.go
  pkg/common/discoveryregister/zookeeper/zookeeper.go
  pkg/common/startrpc/start.go
  scripts/check-all.sh
  scripts/install/openim-api.sh
  scripts/install/openim-crontask.sh
  scripts/install/openim-msggateway.sh
  scripts/install/openim-msgtransfer.sh
  scripts/install/openim-push.sh
  scripts/install/openim-rpc.sh
  scripts/lib/logging.sh
  scripts/lib/util.sh
  tools/component/component.go
  tools/ncpu/ncpu.go
Labels: size/L

#1877 fix(main): fix openim scripts start rpc log
  pkg/common/startrpc/start.go
Labels: size/XS

#1878 feat: Add Color Logging for Error Messages
  scripts/lib/logging.sh
  scripts/lib/util.sh
  scripts/start-all.sh
Labels: size/S

#1880 feat: add getUserToken api and add ex field in getSortedConversationListResp
  go.mod
  go.sum
  internal/api/auth.go
  internal/api/route.go
  internal/rpc/auth/auth.go
  internal/rpc/conversation/conversaion.go
  internal/rpc/group/group.go
  internal/rpc/user/user.go
  pkg/authverify/token.go
Labels: size/M

#1883 Implement Graceful Shutdown for Go Application
  scripts/lib/util.sh
Labels: size/XS

#1483 fix: graceful exit for kafka consumer of msgtransfer
  internal/msgtransfer/init.go
  internal/msgtransfer/online_history_msg_handler.go
  pkg/common/kafka/consumer_group.go
Labels: lifecycle/stale, size/L

#1891 docs: add README.md JP
  .github/workflows/golangci-lint.yml
  .github/workflows/openimci.yml
  docs/readme/README-JP.md
Labels: size/L

#1890 Fix Script Error and Enhance Code Robustness and Details
  .devcontainer/README.md
  .devcontainer/devcontainer.json
  cmd/openim-api/main.go
  pkg/common/cmd/api.go
  pkg/common/cmd/msg_transfer.go
  pkg/common/cmd/root.go
  pkg/common/config/parse.go
  scripts/install/openim-api.sh
  scripts/install/openim-crontask.sh
  scripts/install/openim-msggateway.sh
  scripts/install/openim-msgtransfer.sh
  scripts/install/openim-push.sh
  scripts/install/openim-rpc.sh
  scripts/lib/util.sh
  scripts/stop-all.sh
Labels: size/L

#1900 docs: add README.md-TR
  docs/readme/README-TR.md
Labels: size/L

#1895 docs: add README.md -KR
  docs/readme/README-KR.md
Labels: size/L

#1898 docs:Modified the language naming of files and changed some error paths
  README-zh_CN.md
  README.md
  docs/readme/README-UA.md
  docs/readme/README_ja.md
  docs/readme/README_uk.md
Labels: size/L

#1915 docs: renmaing README files about other languages
  README_zh_CN.md
  docs/readme/README_ko.md
  docs/readme/README_tr.md
Labels: size/M

#1914 Docs: Modify the wrong file name
  docs/readme/README_ko.md
Labels: size/M

#1896 docs: add README-ES
  docs/readme/README-ES.md
Labels: size/L

#1901 docs: add README.md -FR
  docs/readme/README-FR.md
Labels: size/L

#1917 docs:add README_cs.md
  docs/readme/README_cs.md
  scripts/.spelling_failures
Labels: size/L

#1918 Update and rename README-ES.md to README-e.md
  docs/readme/README_es.md
  docs/readme/README_fr.md
Labels: size/L

#1885 fix: refactoring code of graceful exits
  cmd/openim-api/main.go
  cmd/openim-cmdutils/main.go
  cmd/openim-crontask/main.go
  cmd/openim-msggateway/main.go
  cmd/openim-msgtransfer/main.go
  cmd/openim-push/main.go
  cmd/openim-rpc/openim-rpc-auth/main.go
  cmd/openim-rpc/openim-rpc-conversation/main.go
  cmd/openim-rpc/openim-rpc-friend/main.go
  cmd/openim-rpc/openim-rpc-group/main.go
  cmd/openim-rpc/openim-rpc-msg/main.go
  cmd/openim-rpc/openim-rpc-third/main.go
  cmd/openim-rpc/openim-rpc-user/main.go
  internal/msggateway/init.go
  internal/msggateway/n_ws_server.go
  internal/msgtransfer/init.go
  internal/push/callback.go
  internal/push/consumer_init.go
  internal/push/push_rpc_server.go
  internal/tools/cron_task.go
  pkg/common/ginprometheus/ginprometheus.go
  pkg/common/kafka/consumer_group.go
  pkg/common/startrpc/start.go
  pkg/util/genutil/genutil.go
  scripts/githooks/pre-commit.sh
  scripts/install/openim-push.sh
  scripts/lib/util.sh
Labels: size/XL

#1919 docs:add README_hu.md
  docs/readme/README_hu.md
Labels: size/L

#1920 docs:add README_fa.md
  docs/readme/README_fa.md
Labels: size/L

#1922 docs: README add community
  README.md
Labels: size/XS

#1925 add Docs/readme vi
  docs/readme/README_vi.md
Labels: size/L

#1929 add docs/README_el
  docs/readme/README_el.md
Labels: size/L

#1931 feat: optimize server code
  go.mod
  go.sum
  internal/msggateway/client.go
  internal/msggateway/compressor.go
  internal/msggateway/encoder.go
  internal/push/offlinepush/getui/push.go
  internal/rpc/auth/auth.go
  internal/rpc/group/group.go
  pkg/common/db/cache/meta_cache.go
  pkg/common/db/cache/msg.go
  pkg/common/db/controller/auth.go
  pkg/common/db/controller/msg.go
  pkg/common/db/unrelation/msg.go
  pkg/common/db/unrelation/user.go
  pkg/common/http/http_client.go
  pkg/common/kafka/producer.go
Labels: size/L

#1940 fix function name on comment
  tools/formitychecker/checker/checker.go
Labels: size/XS

#1939 docs: modify README Twitter
  README.md
Labels: size/XS

#1951 Fix lint errors in modified code
  internal/msggateway/client.go
  internal/msggateway/long_conn.go
  internal/msggateway/n_ws_server.go
  internal/msggateway/user_map.go
  internal/msgtransfer/init.go
  internal/msgtransfer/online_history_msg_handler.go
Labels: size/L

#1943 docs: update README Community
  README.md
Labels: size/XS

#1952 Fix lint errors in modified code
  pkg/common/cmd/msg_utils.go
  pkg/common/convert/friend.go
  pkg/common/db/cache/conversation.go
  pkg/common/db/controller/auth.go
  pkg/common/db/controller/conversation.go
  pkg/common/db/controller/msg.go
  pkg/common/db/s3/cont/controller.go
  pkg/common/db/s3/cos/cos.go
  pkg/common/db/s3/minio/minio.go
Labels: size/M

#1956 Fix lint errors in modified code in the /pkg directory
  pkg/common/cmd/msg_utils.go
  pkg/common/db/controller/auth.go
  pkg/common/db/s3/minio/minio.go
  pkg/common/db/s3/minio/thumbnail.go
  pkg/common/db/s3/oss/oss.go
  pkg/common/db/unrelation/msg.go
  pkg/rpcclient/notification/group.go
  pkg/rpcclient/third.go
  pkg/statistics/statistics.go
Labels: size/M

#1858 add aws upload, but not complete, leave some todos
  config/templates/config.yaml.template
  deployments/templates/config.yaml
  go.mod
  pkg/common/config/config.go
  pkg/common/db/s3/aws/aws.go
  scripts/install/environment.sh
Labels: size/L

#1942 fix: change consumer group receive messages avoid kafka consumer group always rebalanced.
  internal/msgtransfer/init.go
  internal/msgtransfer/online_history_msg_handler.go
  internal/push/consumer_init.go
  pkg/common/kafka/consumer_group.go
Labels: size/M

#1953 fix: reconstruct the script of 'make start' 'make stop' and 'make check'
  cmd/openim-api/main.go
  install.sh
  internal/msggateway/init.go
  internal/msgtransfer/init.go
  pkg/common/startrpc/start.go
  pkg/util/genutil/genutil.go
  scripts/advertise.sh
  scripts/build-all-service.sh
  scripts/check-all.sh
  scripts/cherry-pick.sh
  scripts/common.sh
  scripts/docker-start-all.sh
  scripts/gen-swagger-docs.sh
  scripts/init-config.sh
  scripts/init-env.sh
  scripts/install-im-server.sh
  scripts/install/common.sh
  scripts/install/dependency.sh
  scripts/install/install.sh
  scripts/install/openim-api.sh
  scripts/install/openim-crontask.sh
  scripts/install/openim-man.sh
  scripts/install/openim-msggateway.sh
  scripts/install/openim-msgtransfer.sh
  scripts/install/openim-push.sh
  scripts/install/openim-rpc.sh
  scripts/install/openim-tools.sh
  scripts/lib/golang.sh
  scripts/lib/init.sh
  scripts/lib/logging.sh
  scripts/lib/util.sh
  scripts/list-feature-tests.sh
  scripts/release.sh
  scripts/run-in-gopath.sh
  scripts/start-all.sh
  scripts/stop-all.sh
  scripts/update-generated-docs.sh
  scripts/update-yamlfmt.sh
  scripts/verify-pkg-names.sh
  scripts/verify-shellcheck.sh
  scripts/verify-spelling.sh
  scripts/verify-typecheck.sh
  scripts/verify-yamlfmt.sh
Labels: size/XL

#1966 Fix lint errors in modified code
  internal/push/consumer_init.go
  internal/rpc/friend/black.go
  internal/rpc/friend/friend.go
  internal/rpc/group/group.go
  internal/rpc/msg/as_read.go
  internal/rpc/msg/revoke.go
  internal/rpc/msg/send.go
  internal/rpc/msg/server.go
  internal/rpc/third/s3.go
  internal/rpc/third/third.go
  internal/rpc/user/user.go
Labels: size/L
