Repository openimsdk/open-im-server, pull requests merged in 2024-10, with the labels that each got.

#2697 feat: improve publish docker image workflows
  .github/workflows/publish-docker-image.yml
  Dockerfile
  internal/rpc/group/group.go
Labels: size/M

#2700 fix: update load file logic.
  .github/workflows/publish-docker-image.yml
Labels: size/S

#2703 feat: Msg filter
  config/webhooks.yml
  go.mod
  go.sum
  internal/rpc/msg/callback.go
  internal/rpc/msg/filter.go
  pkg/common/config/config.go
Labels: size/L

#2712 feat: provide the interface required by js sdk
  cmd/openim-api/main.go
  go.mod
  go.sum
  internal/api/jssdk/jssdk.go
  internal/api/jssdk/stu.go
  internal/api/jssdk/tools.go
  internal/api/jssdk_test.go
  internal/api/router.go
  internal/rpc/relation/friend.go
  pkg/common/convert/friend.go
Labels: size/L

#2716 Line webhook
  config/discovery.yml
  docker-compose.yml
  internal/msggateway/online.go
Labels: size/M

#2718 fix: the message I sent is not set to read seq in mongodb
  internal/push/a_test.go
  pkg/common/storage/controller/msg_transfer.go
Labels: size/M

#2719 fix: cannot modify group member avatars
  internal/rpc/group/group.go
Labels: size/XS

#2720 merge: update code from main to v3.8-js-sdk-only.
  .env
  .github/workflows/publish-docker-image.yml
  Dockerfile
  cmd/openim-api/main.go
  config/discovery.yml
  config/webhooks.yml
  docker-compose.yml
  go.mod
  go.sum
  internal/api/auth.go
  internal/api/jssdk/jssdk.go
  internal/api/jssdk/stu.go
  internal/api/jssdk/tools.go
  internal/api/jssdk_test.go
  internal/api/router.go
  internal/api/user.go
  internal/msggateway/hub_server.go
  internal/msggateway/online.go
  internal/push/a_test.go
  internal/rpc/auth/auth.go
  internal/rpc/group/callback.go
  internal/rpc/group/db_map.go
  internal/rpc/group/group.go
  internal/rpc/msg/callback.go
  internal/rpc/msg/filter.go
  internal/rpc/relation/callback.go
  internal/rpc/relation/friend.go
  internal/rpc/user/online.go
  pkg/callbackstruct/constant.go
  pkg/callbackstruct/friend.go
  pkg/common/cmd/msg_gateway_test.go
  pkg/common/config/config.go
  pkg/common/convert/friend.go
  pkg/common/storage/controller/auth.go
  pkg/common/storage/controller/msg_transfer.go
  pkg/msgprocessor/conversation.go
  pkg/msgprocessor/conversation_test.go
  tools/url2im/pkg/api.go
  tools/url2im/pkg/manage.go
  version/version
Labels: size/XXL

#2724 fix: auth package import twice
  pkg/rpcclient/auth.go
Labels: size/S

#2772 fix: join the group chat directly, notification type error
  internal/rpc/group/group.go
  internal/rpc/group/notification.go
Labels: size/M

#2730 fix: change update group member level logic
  internal/rpc/group/group.go
Labels: size/M

#2770 feat: Add More Multi Login Policy
  config/share.yml
  go.mod
  go.sum
  internal/msggateway/ws_server.go
  internal/rpc/auth/auth.go
  pkg/common/config/config.go
  pkg/common/storage/cache/cachekey/token.go
  pkg/common/storage/cache/redis/token.go
  pkg/common/storage/cache/token.go
  pkg/common/storage/controller/auth.go
  pkg/rpcclient/auth.go
Labels: size/L

#2773 fix: joinSource check args error.
  go.mod
  go.sum
Labels: size/XS

#2775 feat: Push configuration can ignore case sensitivity
  internal/push/offlinepush/offlinepusher.go
Labels: size/XS

#2777 fix: Change group member roleLevel can`t send notification
  internal/rpc/group/group.go
Labels: size/XS

#2779 fix: client sends message status error to server
  go.mod
  go.sum
  internal/push/offlinepush_handler.go
  internal/push/push_handler.go
  pkg/common/storage/controller/msg_transfer.go
Labels: size/S

#2786 chore: remove unused content
  CHANGELOG/.chglog/CHANGELOG.tpl.md
  CHANGELOG/.chglog/config.yml
  build/goreleaser.yaml
Labels: size/L

#2782 fix: improve setConversationAtInfo logic.
  internal/rpc/msg/send.go
Labels: size/S

#2789 Revert: Change group member roleLevel can`t send notification
  internal/rpc/group/group.go
Labels: size/XS

#2792 fix: improve getUserInfo logic.
  internal/rpc/user/user.go
  pkg/rpccache/user.go
Labels: size/XS

#2794 feat: support app update service
  go.mod
  go.sum
  internal/api/router.go
  internal/api/third.go
  internal/rpc/third/application.go
  internal/rpc/third/third.go
  internal/rpc/third/tool.go
  pkg/common/storage/cache/application.go
  pkg/common/storage/cache/cachekey/application.go
  pkg/common/storage/cache/redis/application.go
  pkg/common/storage/controller/application.go
  pkg/common/storage/database/application.go
  pkg/common/storage/database/mgo/application.go
  pkg/common/storage/model/application.go
Labels: size/L

#2796 feat: implement merge milestone PR to target-branch.
  .github/workflows/cleanup-after-milestone-prs-merged.yml
  .github/workflows/merge-from-milestone.yml
Labels: size/L

#2801 build: improve workflows logic.
  .github/workflows/go-build-test.yml
  .github/workflows/merge-from-milestone.yml
Labels: size/XS

#2804 fix: improve time condition check mehtod.
  internal/rpc/group/group.go
Labels: size/XS

#2805 fix: webhook before online push
  internal/push/callback.go
Labels: size/XS

#2808 fix: set own read seq in MongoDB when sender send a message.
  internal/msgtransfer/init.go
  internal/msgtransfer/online_history_msg_handler.go
  pkg/common/storage/controller/msg_transfer.go
Labels: size/L

#2806 fix: solve err Notification when setGroupInfo.
  .github/workflows/cleanup-after-milestone-prs-merged.yml
  config/notification.yml
  internal/rpc/group/group.go
Labels: size/M

#2788 Introducing OpenIM Guru on Gurubase.io
  README.md
Labels: size/XS

#2811 feat: support app update service
  go.mod
  go.sum
  internal/rpc/third/application.go
  pkg/common/storage/cache/application.go
  pkg/common/storage/cache/cachekey/application.go
  pkg/common/storage/cache/redis/application.go
  pkg/common/storage/controller/application.go
  pkg/common/storage/database/application.go
  pkg/common/storage/database/mgo/application.go
  pkg/common/storage/model/application.go
Labels: size/M

#2813 feat: ApplicationVersion move chat
  go.mod
  go.sum
  internal/api/router.go
  internal/api/third.go
  internal/rpc/third/application.go
  internal/rpc/third/third.go
  pkg/common/storage/cache/application.go
  pkg/common/storage/cache/cachekey/application.go
  pkg/common/storage/cache/redis/application.go
  pkg/common/storage/controller/application.go
  pkg/common/storage/database/application.go
  pkg/common/storage/database/mgo/application.go
Labels: size/L

#2815 fix: improve condition check.
  internal/rpc/group/group.go
Labels: size/XS

#2818 merge: update code from main to v3.8-js-sdk-only.
  .github/workflows/cleanup-after-milestone-prs-merged.yml
  .github/workflows/go-build-test.yml
  .github/workflows/merge-from-milestone.yml
  README.md
  config/notification.yml
  go.mod
  go.sum
  internal/api/router.go
  internal/api/third.go
  internal/msgtransfer/init.go
  internal/msgtransfer/online_history_msg_handler.go
  internal/push/callback.go
  internal/rpc/group/group.go
  internal/rpc/third/application.go
  internal/rpc/third/third.go
  pkg/common/storage/cache/application.go
  pkg/common/storage/cache/cachekey/application.go
  pkg/common/storage/cache/redis/application.go
  pkg/common/storage/controller/application.go
  pkg/common/storage/controller/msg_transfer.go
  pkg/common/storage/database/application.go
  pkg/common/storage/database/mgo/application.go
  pkg/common/storage/model/application.go
Labels: size/XL
