Repository openimsdk/open-im-server, pull requests merged in 2024-07, with the labels that each got.

#2379 feat: support incremental synchronization
  config/redis.yml
  go.mod
  go.sum
  internal/api/friend.go
  internal/api/group.go
  internal/api/router.go
  internal/push/push_handler.go
  internal/rpc/friend/black.go
  internal/rpc/friend/callback.go
  internal/rpc/friend/friend.go
  internal/rpc/friend/notification.go
  internal/rpc/friend/sync.go
  internal/rpc/group/convert.go
  internal/rpc/group/group.go
  internal/rpc/group/notification.go
  internal/rpc/group/sync.go
  internal/rpc/incrversion/option.go
  internal/rpc/msg/seq.go
  internal/rpc/user/user.go
  pkg/common/cmd/group.go
  pkg/common/cmd/msg_gateway_test.go
  pkg/common/convert/user.go
  pkg/common/storage/cache/cachekey/friend.go
  pkg/common/storage/cache/cachekey/group.go
  pkg/common/storage/cache/friend.go
  pkg/common/storage/cache/group.go
  pkg/common/storage/cache/redis/friend.go
  pkg/common/storage/cache/redis/group.go
  pkg/common/storage/controller/friend.go
  pkg/common/storage/controller/group.go
  pkg/common/storage/controller/user.go
  pkg/common/storage/database/friend.go
  pkg/common/storage/database/group.go
  pkg/common/storage/database/group_member.go
  pkg/common/storage/database/mgo/black.go
  pkg/common/storage/database/mgo/conversation.go
  pkg/common/storage/database/mgo/friend.go
  pkg/common/storage/database/mgo/friend_request.go
  pkg/common/storage/database/mgo/group.go
  pkg/common/storage/database/mgo/group_member.go
  pkg/common/storage/database/mgo/group_request.go
  pkg/common/storage/database/mgo/log.go
  pkg/common/storage/database/mgo/object.go
  pkg/common/storage/database/mgo/user.go
  pkg/common/storage/database/mgo/version_log.go
  pkg/common/storage/database/mgo/version_test.go
  pkg/common/storage/database/name.go
  pkg/common/storage/database/user.go
  pkg/common/storage/database/version_log.go
  pkg/common/storage/model/friend.go
  pkg/common/storage/model/user.go
  pkg/common/storage/model/version_log.go
  pkg/common/storage/versionctx/rpc.go
  pkg/common/storage/versionctx/version.go
  pkg/rpcclient/friend.go
  pkg/util/hashutil/id.go
Labels: size/XXL

#2387 Optimize get conversation seq
  pkg/common/storage/cache/redis/seq.go
  pkg/rpccache/conversation.go
Labels: size/M

#2386 update gomake version
  Dockerfile
  go.mod
  go.sum
Labels: size/XS

#2389 fix:start
  pkg/common/startrpc/start.go
Labels: size/XS

#2396 fix:log
  config/log.yml
  go.mod
  go.sum
  pkg/common/cmd/root.go
  pkg/common/config/config.go
Labels: size/M

#2400 fix: remove repeat append logic in search message.
  pkg/common/storage/database/mgo/msg.go
Labels: size/XS

#2403 Fix token
  config/log.yml
  pkg/common/storage/controller/auth.go
Labels: size/S

#2404 feat: implement server-initiated heartbeat in msgGateway module
  internal/msggateway/client.go
  internal/msggateway/constant.go
  internal/msggateway/long_conn.go
  internal/msggateway/ws_server.go
Labels: size/M

#2363 feature: support for Kodo
  config/openim-rpc-third.yml
  go.mod
  internal/rpc/third/third.go
  pkg/common/config/config.go
Labels: size/M

#2408 feat: incremental synchronization of session list
  go.mod
  go.sum
  internal/api/conversation.go
  internal/api/friend.go
  internal/api/router.go
  internal/rpc/conversation/conversaion.go
  internal/rpc/conversation/sync.go
  internal/rpc/third/s3.go
  internal/rpc/third/third.go
  internal/rpc/user/user.go
  pkg/common/storage/cache/cachekey/conversation.go
  pkg/common/storage/cache/conversation.go
  pkg/common/storage/cache/redis/conversation.go
  pkg/common/storage/controller/conversation.go
  pkg/common/storage/database/conversation.go
  pkg/common/storage/database/mgo/conversation.go
  pkg/common/storage/database/mgo/msg.go
  pkg/common/storage/database/name.go
Labels: size/L

#2414 Feature domain
  config/log.yml
  config/prometheus.yml
  go.mod
  go.sum
  pkg/common/cmd/root.go
  pkg/common/config/config.go
Labels: size/M

#2415 chore: add ping Handler DEBUG log in msgGateway.
  internal/msggateway/client.go
Labels: size/S

#2419 fix: seq conversion bug
  tools/seq/internal/main.go
Labels: size/XS

#2421 fix: redis pipe exec
  pkg/common/storage/cache/redis/seq_conversation.go
Labels: size/XS

#2427 feat: group members, friends sorting version, client online subscription
  go.mod
  go.sum
  internal/msggateway/client.go
  internal/msggateway/subscription.go
  internal/msggateway/ws_server.go
  internal/rpc/friend/notification.go
  internal/rpc/friend/sync.go
  internal/rpc/group/notification.go
  internal/rpc/group/sync.go
  internal/rpc/user/online.go
  internal/rpc/user/user.go
  pkg/common/storage/controller/user.go
  pkg/common/storage/database/mgo/friend.go
  pkg/common/storage/database/mgo/group_member.go
  pkg/common/storage/database/mgo/subscribe.go
  pkg/common/storage/database/mgo/version_log.go
  pkg/common/storage/database/mgo/version_test.go
  pkg/common/storage/database/subscribe.go
  pkg/common/storage/model/version_log.go
  tools/seq/main.go
Labels: size/XL

#2429 Feat metrics
  config/alertmanager.yml
  config/grafana-template/Demo.json
  config/instance-down-rules.yml
  internal/rpc/user/user.go
  pkg/common/prommetrics/grpc_user.go
  pkg/common/prommetrics/rpc.go
Labels: size/XXL

#2417 feat: implement true batchGetIncrGroupMember RPC method and dependency methods.
  internal/api/group.go
  internal/rpc/conversation/sync.go
  internal/rpc/friend/sync.go
  internal/rpc/group/sync.go
  internal/rpc/incrversion/batch_option.go
  internal/rpc/incrversion/option.go
  pkg/common/storage/cache/group.go
  pkg/common/storage/cache/redis/group.go
  pkg/common/storage/controller/group.go
  pkg/common/storage/database/group_member.go
  pkg/common/storage/database/mgo/group_member.go
  pkg/common/storage/database/mgo/version_log.go
  pkg/common/storage/database/version_log.go
Labels: size/XL

#2425 Fix search log
  config/email.tmpl
  internal/rpc/third/log.go
  pkg/common/storage/controller/user.go
Labels: size/M

#2434 feat: msg queue push
  go.mod
  go.sum
  internal/msggateway/hub_server.go
Labels: size/L

#2432 docs: fix english typo
  README.md
  README_zh_CN.md
  docs/contrib/util-scripts.md
  docs/contributing/CONTRIBUTING-JP.md
  docs/contributing/CONTRIBUTING-PL.md
  docs/readme/README_cs.md
  docs/readme/README_da.md
  docs/readme/README_el.md
  docs/readme/README_es.md
  docs/readme/README_fa.md
  docs/readme/README_fr.md
  docs/readme/README_hu.md
  docs/readme/README_ja.md
  docs/readme/README_ko.md
  docs/readme/README_tr.md
  docs/readme/README_uk.md
  docs/readme/README_vi.md
Labels: size/M

#2438 fix: batchGetMaxSeq bug
  pkg/common/storage/cache/redis/seq_conversation.go
  pkg/common/storage/database/mgo/msg.go
Labels: size/S

#2436 feat: implement log isSimpilfy.
  config/log.yml
  go.mod
  go.sum
  pkg/common/cmd/root.go
  pkg/common/config/config.go
Labels: size/S

#2442 fix: user seq bug
  pkg/common/storage/cache/redis/batch.go
  pkg/common/storage/cache/redis/batch_handler.go
  pkg/common/storage/cache/redis/seq_user.go
  pkg/common/storage/cache/seq_user.go
  pkg/common/storage/controller/msg.go
  pkg/common/storage/database/mgo/seq_user.go
  pkg/common/storage/database/seq_user.go
  tools/seq/internal/main.go
Labels: size/L

#2444 fix: display is read
  internal/rpc/group/notification.go
Labels: size/M

#2446 chore: add debug log in writePongMsg
  go.mod
  go.sum
  internal/msggateway/client.go
Labels: size/S

#2447 fix: user seq, asynchronous friend notification, message search
  internal/rpc/friend/friend.go
  internal/rpc/friend/sync.go
  internal/rpc/msg/sync_msg.go
  pkg/common/storage/cache/redis/batch_test.go
  pkg/common/storage/cache/redis/seq_user_test.go
  pkg/common/storage/controller/msg.go
  pkg/common/storage/database/mgo/msg.go
  pkg/common/storage/database/mgo/msg_test.go
  pkg/common/storage/database/mgo/seq_conversation_test.go
  pkg/common/storage/database/mgo/seq_user.go
  pkg/common/storage/database/msg.go
Labels: size/XL

#2346 cicd: add e2e in ci & before build docker image
  .github/workflows/build-docker-image.yml
  .github/workflows/link-pr.yml
  .github/workflows/openimci.yml
  .github/workflows/stale.yml
Labels: size/L

#2449 fix: rm e2e in ci
  .github/workflows/build-docker-image.yml
  .github/workflows/openimci.yml
Labels: size/L

#2422 fix: fill notification offlinePush by config
  pkg/rpcclient/msg.go
Labels: size/XS

#2452 chore: add Warn log in writePongMsg.
  internal/msggateway/client.go
Labels: size/XS

#2423 fix: #2410 BeforeMemberJoinGroup callback member error
  internal/rpc/group/group.go
Labels: size/XS

#2456 fix: search log can return platform
  go.mod
  go.sum
  internal/rpc/third/log.go
Labels: size/XS

#2458 fix ImportFriends
  pkg/common/storage/controller/friend.go
Labels: size/M

#2459 feat: update webhookBeforeMemberJoinGroup to batch method.
  .env
  internal/msggateway/client.go
  internal/rpc/group/callback.go
  internal/rpc/group/group.go
  pkg/callbackstruct/constant.go
  pkg/callbackstruct/group.go
  pkg/common/cmd/api.go
  pkg/common/cmd/auth.go
  pkg/common/cmd/conversation.go
  pkg/common/cmd/cron_task.go
  pkg/common/cmd/friend.go
  pkg/common/cmd/group.go
  pkg/common/cmd/msg.go
  pkg/common/cmd/msg_gateway.go
  pkg/common/cmd/msg_transfer.go
  pkg/common/cmd/push.go
  pkg/common/cmd/root.go
  pkg/common/cmd/third.go
  pkg/common/cmd/user.go
  pkg/common/config/parse.go
  pkg/common/config/version
  version/version
  version/version.go
Labels: size/L

#2461 feat: add some logs
  internal/push/push_handler.go
  pkg/common/storage/cache/redis/online.go
  pkg/rpccache/online.go
Labels: size/M

#2462 fix: return value
  pkg/rpccache/online.go
Labels: size/XS

#2463 refactor: rename friend module to relation.
  internal/rpc/relation/black.go
  internal/rpc/relation/callback.go
  internal/rpc/relation/friend.go
  internal/rpc/relation/notification.go
  internal/rpc/relation/sync.go
  internal/rpc/user/user.go
  pkg/common/cmd/friend.go
Labels: size/M
