Repository openimsdk/open-im-server, pull requests merged in 2024-04, with the labels that each got.

#2177 update release-v3.1 images
  README.md
Labels: size/XS

#2178 feat: update release-v3.2 images
  README.md
Labels: size/XS

#2179 fix: fix release-v3.3 start bug
  README.md
  docker-compose.yml
  scripts/make-rules/golang.mk
Labels: size/S

#2182 feat: optimize go version auto set
  scripts/make-rules/golang.mk
Labels: size/XS

#2200 update some ci file
  .github/workflows/e2e-test.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/openimci.yml
Labels: size/L

#2202 3.6.1 code conventions
  .dockerignore
  Dockerfile
  bootstrap.sh
  config/README.md
  config/minio.yml
  go.mod
  go.sum
  internal/api/init.go
  internal/msgtransfer/init.go
  internal/msgtransfer/online_history_msg_handler.go
  internal/push/push_handler.go
  internal/rpc/third/third.go
  pkg/common/config/config.go
  pkg/common/config/load_config_test.go
  pkg/common/config/version
  pkg/common/discoveryregister/discoveryregister.go
  pkg/localcache/cache.go
  pkg/localcache/go.mod
  pkg/localcache/go.sum
  pkg/localcache/option.go
  pkg/rpccache/conversation.go
  pkg/rpccache/friend.go
  pkg/rpccache/group.go
  pkg/rpccache/user.go
  scripts/create-topic.sh
  scripts/docker-start-all.sh
  scripts/mongo-init.sh
Labels: size/L

#2203 3.6.1 code conventions
  .dockerignore
  .gitattributes
  Dockerfile
  config/README.md
  config/minio.yml
  go.mod
  go.sum
  internal/api/init.go
  internal/msgtransfer/init.go
  internal/msgtransfer/online_history_msg_handler.go
  internal/push/push_handler.go
  internal/rpc/third/third.go
  pkg/common/config/config.go
  pkg/common/config/load_config_test.go
  pkg/common/config/version
  pkg/common/discoveryregister/discoveryregister.go
  pkg/localcache/cache.go
  pkg/localcache/go.mod
  pkg/localcache/go.sum
  pkg/localcache/option.go
  pkg/rpccache/conversation.go
  pkg/rpccache/friend.go
  pkg/rpccache/group.go
  pkg/rpccache/user.go
  scripts/docker-start-all.sh
Labels: size/L

#2211 Update action
  .github/workflows/e2e-test.yml
  .github/workflows/golangci-lint.bak
  .github/workflows/openimci.yml
Labels: size/XS

#2213 Update action
  .github/workflows/docker-buildx.bak
Labels: size/XS

#2210 update go.mod go.sum
  config/kafka.yml
  config/minio.yml
  config/mongodb.yml
  config/notification.yml
  config/openim-msggateway.yml
  config/openim-msgtransfer.yml
  config/openim-push.yml
  config/openim-rpc-auth.yml
  config/openim-rpc-conversation.yml
  config/openim-rpc-friend.yml
  config/openim-rpc-group.yml
  config/openim-rpc-msg.yml
  config/openim-rpc-third.yml
  go.mod
  go.sum
  internal/push/offlinepush/offlinepusher.go
  internal/push/push_handler.go
  start-config.yml
Labels: size/L

#2209 update go.mod go.sum
  .github/workflows/e2e-test.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/openimci.yml
  config/kafka.yml
  config/minio.yml
  config/mongodb.yml
  config/notification.yml
  config/openim-msggateway.yml
  config/openim-msgtransfer.yml
  config/openim-push.yml
  config/openim-rpc-auth.yml
  config/openim-rpc-conversation.yml
  config/openim-rpc-friend.yml
  config/openim-rpc-group.yml
  config/openim-rpc-msg.yml
  config/openim-rpc-third.yml
  go.mod
  go.sum
  internal/push/offlinepush/offlinepusher.go
  internal/push/push_handler.go
  start-config.yml
Labels: size/XL

#2221 Update the document
  .github/workflows/e2e-test.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/openimci.yml
  README.md
  README_zh_CN.md
  docs/CODEOWNERS
Labels: size/L

#2225 update action
  .github/workflows/create-branch-on-tag.bak
  .github/workflows/e2e-test.bak
  .github/workflows/pull-request.bak
Labels: size/XS

#2231 use openim/openim-admin openim/openim-web image
  .env
  .github/workflows/e2e-test.yml
Labels: size/XS

#2241 auto close issue test
  README.md
Labels: size/XS

#2244 Simplify the contribution process 2234
  CONTRIBUTING-zh_CN.md
  CONTRIBUTING.md
  docs/CODEOWNERS
Labels: size/XL

#2247 update web/admin front image
  .env
Labels: size/XS

#2249 fix bug:invalid go version '1.21.2' : must match format 1.23
  go.mod
Labels: size/XS

#2237 feat: optimize corn tasks
  config/openim-crontask.yml
  go.mod
  go.sum
  internal/rpc/conversation/conversaion.go
  internal/rpc/msg/clear.go
  internal/tools/conversation.go
  internal/tools/cron_task.go
  internal/tools/cron_task_test.go
  internal/tools/msg.go
  internal/tools/msg_doc_convert.go
  pkg/authverify/token.go
  pkg/common/cmd/cron_task.go
  pkg/common/cmd/msg_utils.go
  pkg/common/config/config.go
  pkg/common/db/controller/msg.go
  pkg/common/db/mgo/conversation.go
  pkg/common/db/mgo/msg.go
  pkg/common/db/table/relation/msg.go
  pkg/rpcclient/conversation.go
  pkg/rpcclient/msg.go
Labels: size/XXL

#2243 Auto close issue test
  README.md
Labels: size/XS

#2252 fix bug:If there are uppercase letters in the directory, 'mage start' encounters an error
  go.mod
  go.sum
Labels: size/XS

#2257 Update action v3.7
  .env
  .github/workflows/check-coverage.yml
  .github/workflows/create-branch-on-tag.yml
  .github/workflows/docker-buildx.yml
  .github/workflows/release.yml
  .github/workflows/sync-release.yml
  .github/workflows/sync.yml
Labels: size/XL

#2253 fix bug: If there are uppercase letters in the directory, 'mage start' encounters an error
  go.mod
  go.sum
Labels: size/XS

#2256 Update action
  .env
  .github/workflows/check-coverage.bak
  .github/workflows/release.bak
  .github/workflows/sync-release.bak
  .github/workflows/sync.bak
Labels: size/S

#2238 feat: optimize corn tasks
  .github/workflows/create-branch-on-tag.bak
  .github/workflows/docker-buildx.bak
  .github/workflows/e2e-test.bak
  .github/workflows/golangci-lint.bak
  .github/workflows/pull-request.bak
  config/openim-crontask.yml
  go.mod
  go.sum
  internal/rpc/conversation/conversaion.go
  internal/rpc/msg/clear.go
  internal/tools/conversation.go
  internal/tools/cron_task.go
  internal/tools/cron_task_test.go
  internal/tools/msg.go
  internal/tools/msg_doc_convert.go
  pkg/authverify/token.go
  pkg/common/cmd/cron_task.go
  pkg/common/cmd/msg_utils.go
  pkg/common/config/config.go
  pkg/common/db/controller/msg.go
  pkg/common/db/mgo/conversation.go
  pkg/common/db/mgo/msg.go
  pkg/common/db/table/relation/msg.go
  pkg/rpcclient/conversation.go
  pkg/rpcclient/msg.go
Labels: size/XXL

#2264 fix: minio config url recognition error
  pkg/common/config/config.go
Labels: size/S

#2263 fix: minio config build
  pkg/common/config/config.go
Labels: size/S
