Repository openimsdk/open-im-server, pull requests merged in 2024-09, with the labels that each got.

#2588 feat: implement no gob encoder.
  internal/msggateway/encoder.go
  internal/msggateway/encoder_test.go
Labels: size/M

#2590 feat: update group notification when set to null.
  internal/rpc/group/group.go
  internal/rpc/relation/friend.go
Labels: size/M

#2584 feat: add long time push msg in prometheus
  config/redis.yml
  go.mod
  go.sum
  internal/msgtransfer/online_history_msg_handler.go
  internal/push/offlinepush/dummy/push.go
  internal/push/push_handler.go
  pkg/common/cmd/root.go
  pkg/common/config/config.go
  pkg/common/prommetrics/grpc_push.go
  pkg/common/prommetrics/rpc.go
  pkg/common/storage/cache/redis/batch_handler.go
  pkg/rpccache/conversation.go
Labels: size/M

#2582 feat: supports getting messages based on session ID and seq
  go.mod
  go.sum
  internal/msggateway/client.go
  internal/msggateway/constant.go
  internal/msggateway/message_handler.go
  internal/rpc/group/group.go
  internal/rpc/group/notification.go
  internal/rpc/msg/sync_msg.go
  pkg/rpcclient/msg.go
  pkg/util/conversationutil/conversationutil.go
Labels: size/L

#2591 feat: implement request batch count limit.
  go.mod
  go.sum
Labels: size/XS

#2595 fix: getting messages based on session ID and seq
  internal/rpc/msg/sync_msg.go
Labels: size/XS

#2602 feat: avoid pulling messages from sessions with a large number of max seq values of 0
  internal/rpc/msg/sync_msg.go
Labels: size/XS

#2604 refactor: improve db structure in `storage/controller`
  internal/msgtransfer/init.go
  internal/msgtransfer/online_history_msg_handler.go
  internal/msgtransfer/online_msg_to_mongo_handler.go
  pkg/common/storage/controller/msg.go
  pkg/common/storage/controller/msg_transfer.go
Labels: size/L

#2600 feat: implement offline push using kafka
  config/kafka.yml
  go.mod
  go.sum
  internal/msgtransfer/init.go
  internal/push/offlinepush/getui/push.go
  internal/push/offlinepush_handler.go
  internal/push/push.go
  internal/push/push_handler.go
  pkg/common/cmd/push.go
  pkg/common/config/config.go
  pkg/common/storage/controller/push.go
  scripts/create-topic.sh
  tools/check-component/main.go
Labels: size/L

#2609 feat: API supports gzip
  config/openim-api.yml
  go.mod
  go.sum
  internal/api/router.go
  pkg/common/config/config.go
Labels: size/M

#2608 Fix err
  config/grafana-template/Demo.json
  config/openim-api.yml
  config/openim-msggateway.yml
  config/openim-msgtransfer.yml
  config/openim-push.yml
  config/openim-rpc-auth.yml
  config/openim-rpc-conversation.yml
  config/openim-rpc-friend.yml
  config/openim-rpc-group.yml
  config/openim-rpc-msg.yml
  config/openim-rpc-third.yml
  config/openim-rpc-user.yml
  config/prometheus.yml
  docker-compose.yml
  go.mod
  go.sum
  internal/msggateway/init.go
  internal/msggateway/ws_server.go
  internal/msgtransfer/init.go
  internal/msgtransfer/online_history_msg_handler.go
  internal/msgtransfer/online_msg_to_mongo_handler.go
  internal/push/offlinepush/dummy/push.go
  internal/push/offlinepush/getui/push.go
  internal/push/offlinepush_handler.go
  internal/push/onlinepusher.go
  internal/push/push_handler.go
  internal/rpc/msg/clear.go
  internal/rpc/user/online.go
  internal/tools/cron_task.go
  pkg/common/config/config.go
  pkg/common/startrpc/start.go
  pkg/common/storage/cache/cachekey/online.go
  pkg/common/storage/cache/online.go
  pkg/common/storage/cache/redis/batch.go
  pkg/common/storage/cache/redis/batch_handler.go
  pkg/common/storage/cache/redis/online.go
  pkg/localcache/lru/lru.go
  pkg/localcache/lru/lru_expiration.go
  pkg/localcache/lru/lru_lazy.go
  pkg/localcache/lru/lru_slot.go
  pkg/rpccache/online.go
  pkg/rpcclient/user.go
  start-config.yml
Labels: size/XXL

#2611 feature: add GetConversationsHasReadAndMaxSeq interface to the WebSoc…
  go.mod
  go.sum
  internal/msggateway/client.go
  internal/msggateway/constant.go
  internal/msggateway/message_handler.go
  pkg/rpcclient/msg.go
Labels: size/M

#2613 fix: lru lock
  pkg/localcache/lru/lru_lazy.go
Labels: size/XS

#2618 fix: nil pointer error on close
  go.sum
  pkg/common/startrpc/start.go
Labels: size/S

#2620 fix: blockage caused by listen error
  go.mod
  go.sum
  pkg/common/startrpc/start.go
Labels: size/M

#2621 fix: go.mod
  go.mod
  go.sum
Labels: size/M

#2614 feat: improve searchMsg implement.
  go.mod
  go.sum
  internal/rpc/msg/sync_msg.go
  internal/rpc/third/log.go
  pkg/common/storage/controller/msg.go
  pkg/common/storage/controller/user.go
  scripts/githooks/commit-msg.sh
  scripts/githooks/pre-commit.sh
  scripts/githooks/pre-push.sh
Labels: size/L

#2622 Fix lock
  pkg/localcache/lru/lru_lazy.go
Labels: size/XS

#2625 fix: update setGroupInfoEX field name.
  go.mod
  go.sum
  internal/rpc/group/callback.go
  internal/rpc/group/group.go
Labels: size/M

#2631 feat: msg gateway add log
  internal/msggateway/context.go
  internal/msggateway/ws_server.go
Labels: size/XS

#2634 fix: update setGroupInfoEx func name and field.
  config/webhooks.yml
  go.mod
  go.sum
  internal/api/group.go
  internal/api/router.go
  internal/rpc/group/callback.go
  internal/rpc/group/db_map.go
  internal/rpc/group/group.go
  pkg/callbackstruct/constant.go
  pkg/callbackstruct/group.go
  pkg/common/config/config.go
Labels: size/L

#2645 fix: fix setConversations req fill.
  internal/rpc/conversation/conversaion.go
Labels: size/XS

#2647 fix: GetMsgBySeqs boundary issues
  pkg/common/storage/cache/redis/token.go
  pkg/common/storage/controller/msg.go
Labels: size/S

#2644 fix: the attribute version is obsolete, remove it
  docker-compose.yml
Labels: size/XS

#2650 refactor: update Userregister request field.
  go.mod
  go.sum
  internal/rpc/user/callback.go
  internal/rpc/user/user.go
  pkg/callbackstruct/user.go
  test/e2e/api/token/token.go
Labels: size/S

#2643 fix: kick group member callback
  config/openim-msgtransfer.yml
  config/openim-push.yml
  config/prometheus.yml
  internal/rpc/group/callback.go
Labels: size/XS

#2654 fix: route
  internal/api/router.go
Labels: size/XS

#2656 feat: add GetSpecifiedBlacks interface.
  go.mod
  go.sum
  internal/api/friend.go
  internal/api/router.go
  internal/rpc/group/group.go
  internal/rpc/relation/black.go
  internal/rpc/relation/friend.go
  pkg/rpcclient/user.go
Labels: size/L

#2638 Upgrade the Google Firebase version.
  go.mod
  go.sum
  internal/push/offlinepush/fcm/push.go
Labels: size/L

#2653 Fix token
  config/openim-msggateway.yml
  config/share.yml
  internal/msggateway/ws_server.go
  internal/rpc/auth/auth.go
  pkg/common/config/config.go
  pkg/common/storage/controller/auth.go
Labels: size/M

#2658 feat: get not notify conversationIDs
  go.mod
  go.sum
  internal/api/conversation.go
  internal/api/router.go
  internal/rpc/conversation/conversation.go
  pkg/common/storage/cache/cachekey/conversation.go
  pkg/common/storage/cache/conversation.go
  pkg/common/storage/cache/redis/conversation.go
  pkg/common/storage/controller/conversation.go
  pkg/common/storage/database/conversation.go
  pkg/common/storage/database/mgo/conversation.go
Labels: size/M

#2660 feat: GetPinnedConversationIDs
  go.mod
  go.sum
  internal/api/conversation.go
  internal/api/router.go
  internal/rpc/conversation/conversation.go
  pkg/common/storage/cache/cachekey/conversation.go
  pkg/common/storage/cache/conversation.go
  pkg/common/storage/cache/redis/conversation.go
  pkg/common/storage/controller/conversation.go
  pkg/common/storage/database/conversation.go
  pkg/common/storage/database/mgo/conversation.go
Labels: size/M

#2633 Upgrade the FCM SDK to v4, and use the `SendEach` method instead of the `SendAll` method.
  go.mod
  go.sum
Labels: size/XS

#2661 feat: implement GetSpecifiedUserGroupRequestInfo interface.
  go.mod
  go.sum
  internal/api/group.go
  internal/api/router.go
  internal/rpc/group/group.go
  pkg/common/storage/cache/cachekey/group.go
  pkg/common/storage/cache/group.go
  pkg/common/storage/cache/redis/group.go
  pkg/common/storage/controller/group.go
  pkg/common/storage/database/group_member.go
  pkg/common/storage/database/mgo/group_member.go
Labels: size/L

#2664 feat: provide the interface required by js sdk
  go.mod
  go.sum
  internal/api/jssdk/jssdk.go
  internal/api/jssdk/sort.go
  internal/api/jssdk/stu.go
  internal/api/jssdk/tools.go
  internal/api/jssdk_test.go
  internal/api/router.go
  internal/rpc/group/group.go
  internal/rpc/msg/as_read.go
  internal/rpc/msg/seq.go
  internal/rpc/msg/utils.go
  pkg/common/storage/cache/redis/seq_conversation.go
  pkg/common/storage/cache/redis/seq_conversation_test.go
  pkg/common/storage/cache/seq_conversation.go
  pkg/common/storage/controller/msg.go
  pkg/common/storage/database/seq.go
Labels: size/XL

#2666 feat: improve get admin role memberIDs implement.
  internal/rpc/group/group.go
  pkg/common/storage/cache/cachekey/group.go
  pkg/common/storage/cache/group.go
  pkg/common/storage/cache/redis/group.go
  pkg/common/storage/controller/group.go
  pkg/common/storage/database/group_member.go
  pkg/common/storage/database/mgo/group_member.go
Labels: size/M

#2673 fix: fix update groupName invalid.
  internal/rpc/group/db_map.go
Labels: size/XS

#2670 refactor: change platform to platformID
  go.mod
  go.sum
  internal/api/user.go
  internal/msggateway/hub_server.go
Labels: size/S

#2675 feat: don`t return nil data
  go.mod
  go.sum
Labels: size/XS

#2676 refactor: update fields type in userStatus and check registered.
  go.mod
  go.sum
  internal/api/router.go
  internal/api/user.go
  internal/msggateway/hub_server.go
  internal/rpc/auth/auth.go
  internal/rpc/group/callback.go
  internal/rpc/user/online.go
Labels: size/M

#2677 fix: usertoken auth.
  go.mod
  go.sum
  internal/rpc/auth/auth.go
  tools/url2im/pkg/api.go
Labels: size/S

#2680 feat: add friend agree after callback
  config/webhooks.yml
  internal/rpc/relation/callback.go
  internal/rpc/relation/friend.go
  pkg/callbackstruct/constant.go
  pkg/callbackstruct/friend.go
  pkg/common/config/config.go
Labels: size/M

#2682 fix: sn not sort
  pkg/msgprocessor/conversation.go
  pkg/msgprocessor/conversation_test.go
Labels: size/L

#2684 refactor: add GetAdminToken interface.
  go.mod
  go.sum
  internal/api/auth.go
  internal/api/router.go
  internal/rpc/auth/auth.go
  pkg/common/cmd/msg_gateway_test.go
  tools/url2im/pkg/api.go
  tools/url2im/pkg/manage.go
Labels: size/M

#2686 fix: admin token
  config/webhooks.yml
  pkg/common/storage/controller/auth.go
Labels: size/S

#2688 fix: update workflows logic.
  .github/workflows/publish-docker-image.yml
Labels: size/M

#2687 fix: admin token
  pkg/common/storage/controller/auth.go
Labels: size/XS

#2693 update the front image
  .env
  version/version
Labels: size/S

#2692 update the front image
  .env
  version/version
Labels: size/S
