Repository openimsdk/open-im-server, pull requests merged in 2024-05, with the labels that each got.

#2274 fix: avoid frequent scheduled task
  .github/workflows/build-docker-image.yml
  .github/workflows/lock-issue.bak
  .github/workflows/stale.yml
Labels: size/XS

#2279 Skip minio check
  docker-compose.yml
  go.mod
  go.sum
  internal/tools/cron_task.go
  magefile.go
  tools/check-component/main.go
Labels: size/M

#2281 Skip minio check
  docker-compose.yml
  go.mod
  go.sum
  internal/tools/cron_task.go
  magefile.go
  tools/check-component/main.go
Labels: size/M

#2285 update gomake
  Dockerfile
Labels: size/XS

#2286 update gomake
  Dockerfile
Labels: size/XS

#2289 fix: search for messag
  pkg/common/db/mgo/msg.go
Labels: size/L

#2300 Etcd naming and discovery
  .env
  config/discovery.yml
  config/share.yml
  config/zookeeper.yml
  docker-compose.yml
  go.mod
  go.sum
  internal/api/init.go
  internal/api/router.go
  internal/msggateway/client.go
  internal/msggateway/hub_server.go
  internal/msggateway/init.go
  internal/msggateway/n_ws_server.go
  internal/msgtransfer/init.go
  internal/msgtransfer/online_history_msg_handler.go
  internal/msgtransfer/online_msg_to_mongo_handler.go
  internal/push/onlinepusher.go
  internal/push/push.go
  internal/push/push_handler.go
  internal/rpc/auth/auth.go
  internal/rpc/conversation/conversaion.go
  internal/rpc/friend/friend.go
  internal/rpc/group/group.go
  internal/rpc/msg/server.go
  internal/rpc/third/third.go
  internal/rpc/user/user.go
  internal/tools/cron_task.go
  pkg/common/cmd/api.go
  pkg/common/cmd/auth.go
  pkg/common/cmd/constant.go
  pkg/common/cmd/conversation.go
  pkg/common/cmd/cron_task.go
  pkg/common/cmd/friend.go
  pkg/common/cmd/group.go
  pkg/common/cmd/msg.go
  pkg/common/cmd/msg_gateway.go
  pkg/common/cmd/msg_transfer.go
  pkg/common/cmd/push.go
  pkg/common/cmd/third.go
  pkg/common/cmd/user.go
  pkg/common/config/config.go
  pkg/common/discoveryregister/discoveryregister.go
  pkg/common/discoveryregister/etcd/doc.go
  pkg/common/discoveryregister/zookeeper/zookeeper.go
  pkg/common/startrpc/start.go
  tools/check-component/main.go
Labels: size/L

#2304 fix: s3 config
  config/openim-rpc-third.yml
  go.mod
  go.sum
  internal/msgtransfer/online_history_msg_handler.go
  internal/msgtransfer/online_msg_to_mongo_handler.go
  internal/push/push_handler.go
Labels: size/M

#2303 fix: s3 config
  config/openim-rpc-third.yml
  go.mod
  go.sum
Labels: size/S

#2309 feat: auth by middleware
  internal/api/router.go
Labels: size/M

#2318 etcd naming and discovery
  .env
  config/discovery.yml
  config/share.yml
  config/zookeeper.yml
  docker-compose.yml
  go.mod
  go.sum
  internal/api/init.go
  internal/api/router.go
  internal/msggateway/client.go
  internal/msggateway/hub_server.go
  internal/msggateway/init.go
  internal/msggateway/n_ws_server.go
  internal/msgtransfer/init.go
  internal/push/onlinepusher.go
  internal/push/push.go
  internal/rpc/auth/auth.go
  internal/rpc/conversation/conversaion.go
  internal/rpc/friend/friend.go
  internal/rpc/group/group.go
  internal/rpc/msg/server.go
  internal/rpc/third/third.go
  internal/rpc/user/user.go
  internal/tools/cron_task.go
  pkg/common/cmd/api.go
  pkg/common/cmd/auth.go
  pkg/common/cmd/constant.go
  pkg/common/cmd/conversation.go
  pkg/common/cmd/cron_task.go
  pkg/common/cmd/friend.go
  pkg/common/cmd/group.go
  pkg/common/cmd/msg.go
  pkg/common/cmd/msg_gateway.go
  pkg/common/cmd/msg_transfer.go
  pkg/common/cmd/push.go
  pkg/common/cmd/third.go
  pkg/common/cmd/user.go
  pkg/common/config/config.go
  pkg/common/discoveryregister/discoveryregister.go
  pkg/common/discoveryregister/etcd/doc.go
  pkg/common/discoveryregister/zookeeper/zookeeper.go
  pkg/common/startrpc/start.go
  tools/check-component/main.go
Labels: size/L

#2266 fix: main bug fix notification unread
  internal/msgtransfer/online_history_msg_handler.go
Labels: size/S

#2316 fix: at group message.
  internal/rpc/msg/send.go
Labels: size/XS
