Repository openimsdk/open-im-server, pull requests merged in 2025-07, with the labels that each got.

#3447 fix: solve `createTime` not set in setConversation and Create Conversation.
  internal/rpc/conversation/conversation.go
Labels: size/S

#3452 fix: remove update version file workflows have new line in 3.8.3-patch branch.
  .github/workflows/update-version-file-on-release.yml
  version/version.go
Labels: size/M

#3454 fix: s3 aws init
  internal/rpc/third/third.go
Labels: size/XS

#3479 docs: update slack link.
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/other.yml
  .github/workflows/auto-invite-comment.yml
  .github/workflows/help-comment-issue.yml
  .github/workflows/user-first-interaction.yml
  README.md
  README_zh_CN.md
  docs/readme/README_cs.md
  docs/readme/README_da.md
  docs/readme/README_el.md
  docs/readme/README_es.md
  docs/readme/README_fa.md
  docs/readme/README_fr.md
  docs/readme/README_hu.md
  docs/readme/README_ja.md
  docs/readme/README_ko.md
  docs/readme/README_tr.md
  docs/readme/README_uk.md
  docs/readme/README_vi.md
  install.sh
Labels: size/XL

#3472 fix: added AtUserIDList to the @ message for API sending.
  internal/api/msg.go
  pkg/apistruct/msg.go
Labels: size/M

#3476 fix: solve batch incorrect error in Find DocIDs
  pkg/common/storage/controller/msg.go
  pkg/common/storage/model/msg.go
Labels: size/S

#3433 feat: support mongo replicaset mode.
  config/mongodb.yml
  go.mod
  go.sum
  pkg/common/config/config.go
Labels: size/M

#3483 feat: add filtering for invalid messages and invalid conversations to…
  internal/api/jssdk/jssdk.go
  pkg/rpcli/msg.go
Labels: size/M

#3356 docs: update readme of config file.
  config/README.md
  config/README_zh_CN.md
Labels: size/L

#3485 fix: performance issues with Kafka caused by encapsulating the MQ interface
  go.mod
  go.sum
  internal/msgtransfer/init.go
  internal/msgtransfer/online_history_msg_handler.go
  internal/msgtransfer/online_msg_to_mongo_handler.go
  internal/push/push.go
Labels: size/M

#3488 fix: import friends send notification in v3.8.3-patch
  internal/rpc/relation/friend.go
  internal/rpc/relation/notification.go
Labels: size/S
