Repository openimsdk/open-im-server, pull requests merged in 2025-03, with the labels that each got.

#3172 fix: solve uncorrect notification when set group info
  internal/rpc/group/db_map.go
  internal/rpc/group/group.go
  internal/rpc/group/notification.go
Labels: size/M

#3180 feat: optimizing BatchGetIncrementalGroupMember
  internal/rpc/group/sync.go
Labels: size/L

#3185 fix: the sorting is wrong after canceling the administrator in group settings
  internal/rpc/group/notification.go
Labels: size/XS

#3187 feat: system account send msg doesn't need friend verify
  internal/rpc/msg/verify.go
  pkg/authverify/token.go
Labels: size/S

#3188 fix: solve uncorrect GroupMember enter group notification type.
  internal/rpc/group/group.go
  internal/rpc/group/notification.go
Labels: size/M

#3194 refactor: improve setConversations method.
  internal/rpc/conversation/conversation.go
  internal/rpc/conversation/db_map.go
Labels: size/L

#3213 fix: solve unocrrect invite notification
  internal/rpc/group/group.go
Labels: size/XS

#3220 fix: solve unocrrect invite notification
  internal/rpc/group/group.go
Labels: size/XS

#3183 feat: set configs api
  internal/api/config_manager.go
  internal/api/router.go
  pkg/apistruct/config_manager.go
Labels: size/L

#3223 feat: check if the secret in config/share.yml has been changed during registration
  .github/workflows/go-build-test.yml
  internal/rpc/user/user.go
  pkg/common/servererrs/code.go
  pkg/common/servererrs/predefine.go
Labels: size/M

#3228 feat: Implement webhook in createConversation
  config/webhooks.yml
  internal/rpc/conversation/callback.go
  internal/rpc/conversation/conversation.go
  internal/tools/cron/cron_test.go
  pkg/callbackstruct/constant.go
  pkg/callbackstruct/conversation.go
  pkg/common/cmd/conversation.go
  pkg/common/config/config.go
  pkg/common/config/load_config_test.go
  pkg/common/storage/controller/conversation.go
Labels: size/XL

#3225 feat: add a function for business info change to update related conve…
  go.mod
  go.sum
  internal/api/conversation.go
  internal/api/msg.go
  internal/api/router.go
  internal/rpc/conversation/conversation.go
  internal/rpc/msg/notification.go
  internal/rpc/msg/send.go
  internal/rpc/msg/server.go
  internal/rpc/msg/stream_msg.go
  pkg/common/storage/controller/conversation.go
  pkg/common/storage/controller/stream_msg.go
  pkg/common/storage/database/conversation.go
  pkg/common/storage/database/mgo/conversation.go
  pkg/common/storage/database/mgo/stream_msg.go
  pkg/common/storage/database/stream_msg.go
  pkg/common/storage/model/stream_msg.go
Labels: size/L

#3239 feat: add filtering for invalid messages and invalid conversations to…
  internal/api/jssdk/jssdk.go
  pkg/rpcli/msg.go
Labels: size/M

#3265 fix: improve stress test tools parms.
  tools/stress-test/main.go
Labels: size/M
