Repository openimsdk/open-im-server, pull requests merged in 2025-04, with the labels that each got.

#3271 feat: support server-issued configuration, which can be set for individual users
  go.mod
  go.sum
  internal/api/router.go
  internal/api/user.go
  internal/rpc/user/config.go
  internal/rpc/user/user.go
  pkg/common/storage/cache/cachekey/client_config.go
  pkg/common/storage/cache/client_config.go
  pkg/common/storage/cache/redis/client_config.go
  pkg/common/storage/controller/client_config.go
  pkg/common/storage/database/client_config.go
  pkg/common/storage/database/mgo/client_config.go
  pkg/common/storage/model/client_config.go
Labels: size/L

#3281 feat: GetConversationsHasReadAndMaxSeq support pinned
  go.mod
  go.sum
  internal/rpc/msg/as_read.go
  pkg/rpccache/conversation.go
Labels: size/M

#3284 fix: transferring the group owner to a muted member, incremental version error
  internal/rpc/group/notification.go
Labels: size/XS

#3286 fix: group status in GroupDismissedNotification
  internal/rpc/group/group.go
Labels: size/XS

#3292 feat: Implement stress test v2.
  tools/stress-test-v2/main.go
  tools/stress-test/main.go
Labels: size/XL

#3293 License
  .golangci.yml
  README.md
  README_zh_CN.md
Labels: size/S

#3304 fix: data version SetVersion will add record
  tools/seq/internal/seq.go
Labels: size/XS

#3295 refactor: move stress-test tools location.
  test/stress-test-v2/README.md
  test/stress-test-v2/main.go
  test/stress-test/README.md
  test/stress-test/main.go
  tools/stress-test/README.md
Labels: size/L
