Repository openimsdk/open-im-server, pull requests merged in 2025-08, with the labels that each got.

#3500 fix: admin token in standalone mode (#3499)
  internal/api/router.go
  pkg/common/storage/cache/redis/token.go
Labels: size/S

#3514 fix: optimize to lru local cache.
  pkg/common/storage/cache/mcache/msg_cache.go
  pkg/localcache/cache.go
  pkg/localcache/lru/lru_lazy.go
  pkg/localcache/lru/lru_slot.go
  pkg/rpccache/online.go
Labels: size/M

#3523 fix: fill in the most recent sendTime for a gap message to prevent th…
  pkg/common/storage/database/mgo/msg.go
  pkg/common/storage/model/msg.go
Labels: size/S

#3529 feat: enable redis aof-use-rdb-preamble && disable auto rdb
  docker-compose.yml
Labels: size/XS

#3537 build: comment admin services.
  docker-compose.yml
Labels: size/S
