Repository openimsdk/open-im-server, pull requests merged in 2025-02, with the labels that each got.

#3102 fix: the user sets the conversation timer cleanup timestamp unit incorrectly
  internal/rpc/conversation/conversation.go
  pkg/common/storage/database/mgo/conversation.go
Labels: size/S

#3103 build: keep conflict is true.
  .github/workflows/merge-from-milestone.yml
Labels: size/S

#3104 build: keep conflict is true in pre release.
  .github/workflows/merge-from-milestone.yml
Labels: size/S

#3106 fix: solve workflows stop when merge failed
  .github/workflows/merge-from-milestone.yml
Labels: size/M

#3105 fix: solve stop when merge failed in pre release.
  .github/workflows/merge-from-milestone.yml
Labels: size/M

#3130 fix: seq conversion not reading env in docker environment
  tools/seq/internal/seq.go
Labels: size/S

#3133 fix: pre-release-v3.8.4 startup error caused by merging
  config/notification.yml
  go.mod
  go.sum
  internal/api/msg.go
  internal/api/router.go
  internal/tools/cron_test.go
  pkg/common/config/config.go
  pkg/common/config/parse.go
  tools/seq/internal/main.go
Labels: size/L

#3137 fix: the source message of the reference is withdrawn, and the referenced message is deleted
  internal/msgtransfer/online_msg_to_mongo_handler.go
  pkg/common/storage/controller/msg.go
Labels: size/S

#3151 feat: Change after webhook filter && feat SendSimpleMsg
  config/webhooks.yml
  go.mod
  go.sum
  internal/api/msg.go
  internal/rpc/msg/callback.go
  internal/rpc/msg/filter.go
  internal/rpc/user/user.go
  pkg/apistruct/manage.go
  pkg/common/config/config.go
  pkg/common/storage/controller/user.go
  pkg/common/storage/database/mgo/user.go
  pkg/common/storage/database/user.go
  pkg/common/webhook/http_client.go
Labels: size/L

#3158 fix: PCAndOther multi login policy can`t get old clients correctly
  internal/msggateway/ws_server.go
Labels: size/XS

#3168 feat: the default notification.yml is not configured properly
  config/notification.yml
  internal/push/push_handler.go
Labels: size/M

#3162 feat: add a new message type: Markdown text
  go.mod
  go.sum
  internal/api/msg.go
  internal/rpc/msg/verify.go
  pkg/apistruct/msg.go
Labels: size/M

#3163 feat: add a field to specify whether to send a notification message w…
  go.mod
  go.sum
  internal/api/msg.go
  internal/rpc/conversation/notification.go
  internal/rpc/group/group.go
  internal/rpc/group/notification.go
  internal/rpc/msg/notification.go
  internal/rpc/msg/server.go
  internal/rpc/relation/notification.go
  internal/rpc/user/notification.go
  pkg/common/config/parse.go
  pkg/notification/msg.go
Labels: size/L

#3173 refactor: change sendNotification to sendMessage to avoid ambiguity regarding message sending behavior.
  go.mod
  go.sum
  internal/rpc/group/group.go
  internal/rpc/group/notification.go
  pkg/common/config/parse.go
  pkg/notification/msg.go
Labels: size/M

#3174 fix: Offline push does not have a badge && Android offline push (#3146)
  internal/push/offlinepush/fcm/push.go
  internal/push/offlinepush/getui/body.go
  internal/push/offlinepush/getui/push.go
  pkg/common/storage/cache/redis/lua_script.go
Labels: size/M
