Repository openimsdk/open-im-server, pull requests merged in 2025-06, with the labels that each got.

#3395 fix redis config db field
  pkg/common/config/config.go
Labels: size/XS

#3401 feat: support distributed lock in crontask.
  internal/tools/cron/cron_task.go
  internal/tools/cron/dist_look.go
  start-config.yml
Labels: size/L

#3416 build: update gomake version in dockerfile.[Patch branch]
  Dockerfile
Labels: size/XS

#3420 fix: import friends send notification
  internal/rpc/relation/friend.go
  internal/rpc/relation/notification.go
Labels: size/S

#3382 fix: improve mileston PR workflows contents.
  .github/workflows/merge-from-milestone.yml
Labels: size/S

#3394 feat: Implement etcd and kafka auth.
  .env
  config/discovery.yml
  config/kafka.yml
  docker-compose.yml
Labels: size/L

#3438 fix: Add friend DB in notification sender
  internal/rpc/relation/friend.go
Labels: bug, size/S
