Repository openimsdk/open-im-server, pull requests merged in 2025-05, with the labels that each got.

#3313 fix: delete token by correct platformID && feat: adminToken can be re…
  internal/rpc/auth/auth.go
  pkg/common/storage/cache/cachekey/token.go
  pkg/common/storage/cache/mcache/token.go
  pkg/common/storage/cache/redis/token.go
  pkg/common/storage/cache/token.go
  pkg/common/storage/controller/auth.go
  pkg/common/storage/database/mgo/cache.go
Labels: size/L

#3319 feat: optimize server code
  go.mod
  go.sum
  pkg/common/storage/controller/msg_transfer.go
Labels: size/M

#3327 fix: optimize grpc option and fix some interface permission checks
  go.mod
  go.sum
  internal/api/config_manager.go
  internal/api/msg.go
  internal/api/router.go
  internal/msggateway/hub_server.go
  internal/rpc/auth/auth.go
  internal/rpc/conversation/sync.go
  internal/rpc/group/group.go
  internal/rpc/group/notification.go
  internal/rpc/group/sync.go
  internal/rpc/msg/clear.go
  internal/rpc/msg/delete.go
  internal/rpc/msg/revoke.go
  internal/rpc/msg/sync_msg.go
  internal/rpc/relation/black.go
  internal/rpc/relation/friend.go
  internal/rpc/relation/sync.go
  internal/rpc/third/log.go
  internal/rpc/third/s3.go
  internal/rpc/third/tool.go
  internal/rpc/user/config.go
  internal/rpc/user/user.go
  pkg/authverify/token.go
  pkg/common/startrpc/mw.go
  pkg/common/startrpc/start.go
Labels: size/L

#3355 fix: resolving merge conflicts
  go.mod
  go.sum
  internal/api/msg.go
  internal/api/router.go
  internal/msggateway/init.go
  internal/msgtransfer/online_history_msg_handler.go
  internal/msgtransfer/online_msg_to_mongo_handler.go
  internal/push/offlinepush_handler.go
  internal/push/push_handler.go
  internal/rpc/conversation/notification.go
  internal/rpc/group/db_map.go
  internal/rpc/group/group.go
  internal/rpc/group/notification.go
  internal/rpc/group/sync.go
  internal/rpc/msg/notification.go
  internal/rpc/msg/server.go
  internal/rpc/relation/notification.go
  internal/rpc/user/notification.go
  magefile.go
  pkg/common/config/config.go
  pkg/common/config/load_config_test.go
  pkg/common/config/parse.go
  pkg/common/startrpc/start.go
  pkg/common/storage/cache/mcache/token.go
  pkg/common/storage/controller/auth.go
  pkg/common/storage/controller/msg.go
  pkg/common/storage/controller/msg_transfer.go
  pkg/common/storage/controller/push.go
  pkg/notification/msg.go
  pkg/rpcli/auth.go
  tools/check-component/main.go
  tools/stress-test/README.md
  tools/stress-test/main.go
Labels: size/XXL

#3359 fix: standalone mode cannot be used
  go.mod
  go.sum
  internal/api/router.go
  internal/msggateway/ws_server.go
  internal/msgtransfer/online_msg_to_mongo_handler.go
  internal/push/push_handler.go
  pkg/authverify/token.go
  pkg/common/startrpc/start.go
  pkg/common/startrpc/tools.go
  pkg/rpccache/online.go
Labels: size/L

#3360 fix: standalone mode cannot be used
  go.mod
  go.sum
  internal/api/router.go
  internal/msggateway/ws_server.go
  internal/msgtransfer/online_msg_to_mongo_handler.go
  internal/push/push_handler.go
  pkg/authverify/token.go
  pkg/common/startrpc/start.go
  pkg/common/startrpc/tools.go
  pkg/rpccache/online.go
Labels: size/L

#3366 feat: add rpc interface permission check
  internal/api/conversation.go
  internal/api/router.go
  internal/rpc/conversation/conversation.go
  internal/rpc/conversation/sync.go
  internal/rpc/group/cache.go
  internal/rpc/group/group.go
  internal/rpc/group/statistics.go
  internal/rpc/group/sync.go
  internal/rpc/msg/as_read.go
  internal/rpc/msg/delete.go
  internal/rpc/msg/send.go
  internal/rpc/msg/seq.go
  internal/rpc/msg/statistics.go
  internal/rpc/msg/sync_msg.go
  internal/rpc/relation/black.go
  internal/rpc/relation/friend.go
  internal/rpc/third/log.go
  internal/rpc/third/third.go
  pkg/authverify/token.go
  pkg/tools/batcher/batcher.go
Labels: size/L

#3372 feat: add rpc interface permission check
  config/webhooks.yml
  internal/api/conversation.go
  internal/api/router.go
  internal/rpc/conversation/callback.go
  internal/rpc/conversation/conversation.go
  internal/rpc/conversation/db_map.go
  internal/rpc/conversation/notification.go
  internal/rpc/conversation/sync.go
  internal/rpc/group/cache.go
  internal/rpc/group/group.go
  internal/rpc/group/statistics.go
  internal/rpc/group/sync.go
  internal/rpc/msg/as_read.go
  internal/rpc/msg/delete.go
  internal/rpc/msg/send.go
  internal/rpc/msg/seq.go
  internal/rpc/msg/statistics.go
  internal/rpc/msg/sync_msg.go
  internal/rpc/relation/black.go
  internal/rpc/relation/friend.go
  internal/rpc/third/log.go
  internal/rpc/third/third.go
  internal/tools/cron/cron_test.go
  pkg/authverify/token.go
  pkg/callbackstruct/constant.go
  pkg/callbackstruct/conversation.go
  pkg/common/cmd/conversation.go
  pkg/common/storage/controller/conversation.go
  pkg/common/storage/database/conversation.go
  pkg/common/storage/database/mgo/conversation.go
  pkg/tools/batcher/batcher.go
Labels: size/XXL

#3375 fix: solve user not found when notification invitedUserID is zero in …
  internal/rpc/group/group.go
Labels: size/S

#3362 fix: send simple msg
  internal/api/msg.go
  internal/api/router.go
  internal/rpc/msg/send.go
Labels: size/M

#3326 fix: solve updateUserInfoEx null pointer.
  go.mod
  go.sum
  internal/rpc/user/user.go
Labels: size/XS

#3377 fix: add rpc interface permission check
  internal/push/push.go
  internal/rpc/conversation/conversation.go
  internal/rpc/group/cache.go
  internal/rpc/group/group.go
Labels: size/S

#3396 feat: optimize friend and group applications
  go.mod
  go.sum
  internal/api/friend.go
  internal/api/group.go
  internal/api/router.go
  internal/rpc/group/group.go
  internal/rpc/group/notification.go
  internal/rpc/msg/notification.go
  internal/rpc/relation/friend.go
  internal/rpc/relation/notification.go
  magefile.go
  pkg/common/convert/friend.go
  pkg/common/storage/controller/friend.go
  pkg/common/storage/controller/group.go
  pkg/common/storage/database/friend_request.go
  pkg/common/storage/database/group_request.go
  pkg/common/storage/database/mgo/friend_request.go
  pkg/common/storage/database/mgo/group_request.go
  tools/s3/internal/conversion.go
Labels: size/XL
