Repository openimsdk/open-im-server, pull requests merged in 2025-01, with the labels that each got.

#3029 feat: support GetLastMessage
  go.mod
  go.sum
  internal/msggateway/client.go
  internal/msggateway/constant.go
  internal/msggateway/message_handler.go
  internal/rpc/msg/sync_msg.go
  pkg/common/storage/controller/msg.go
  pkg/common/storage/database/mgo/msg.go
  pkg/common/storage/database/mgo/object.go
  pkg/common/storage/database/msg.go
  pkg/common/storage/database/object.go
  tools/s3/README.md
  tools/s3/internal/conversion.go
  tools/s3/main.go
Labels: size/L

#3033 fix: resolving v3.8.3 conflicts
  config/openim-rpc-third.yml
  go.sum
  pkg/common/config/config.go
Labels: size/L

#3036 feat: Add enable config center button && fix: grpc connection leakage
  go.mod
  go.sum
  internal/api/config_manager.go
  internal/api/init.go
  internal/api/router.go
  internal/msggateway/hub_server.go
  internal/msgtransfer/init.go
  internal/tools/cron_task.go
  pkg/apistruct/config_manager.go
  pkg/common/cmd/auth.go
  pkg/common/cmd/conversation.go
  pkg/common/cmd/friend.go
  pkg/common/cmd/group.go
  pkg/common/cmd/msg.go
  pkg/common/cmd/push.go
  pkg/common/cmd/root.go
  pkg/common/cmd/third.go
  pkg/common/cmd/user.go
  pkg/common/discovery/discoveryregister.go
  pkg/common/discovery/etcd/config_manager.go
  pkg/common/discovery/etcd/const.go
  pkg/common/discovery/etcd/doc.go
  pkg/common/startrpc/start.go
Labels: size/L

#3038 feat: change appNotificationAccount to appManagerAccount && fix: enable config center add env check && fix: error return
  go.mod
  go.sum
  internal/api/config_manager.go
  internal/api/router.go
  internal/rpc/auth/auth.go
  internal/rpc/user/user.go
Labels: size/M

#3040 fix: GetUsersOnline returns an error in the online list
  pkg/rpccache/online.go
Labels: size/XS

#3044 fix: resolving v3.8.3 conflicts
  go.mod
  go.sum
  internal/api/config_manager.go
  internal/api/router.go
  pkg/common/discoveryregister/discoveryregister.go
Labels: size/XL

#3048 feat: SendBusinessNotification supported configuration parameters
  internal/api/msg.go
Labels: size/M

#3052 fix: seq conversion failed without exiting
  tools/seq/main.go
Labels: size/XS

#3054 Fix: Service Discovery err in v3.8.3
  internal/api/init.go
  internal/msggateway/hub_server.go
  internal/msgtransfer/init.go
  internal/tools/cron_task.go
  pkg/common/cmd/auth.go
  pkg/common/cmd/conversation.go
  pkg/common/cmd/friend.go
  pkg/common/cmd/group.go
  pkg/common/cmd/msg.go
  pkg/common/cmd/push.go
  pkg/common/cmd/third.go
  pkg/common/cmd/user.go
  pkg/common/discoveryregister/discoveryregister.go
  pkg/common/startrpc/start.go
  version/version
Labels: size/M

#3055 update: env image version
  .env
Labels: size/XS

#3059 fix: add autoSetPort && prometheus port discovery
  .env
  config/openim-api.yml
  config/openim-msggateway.yml
  config/openim-msgtransfer.yml
  config/openim-push.yml
  config/openim-rpc-auth.yml
  config/openim-rpc-conversation.yml
  config/openim-rpc-friend.yml
  config/openim-rpc-group.yml
  config/openim-rpc-msg.yml
  config/openim-rpc-third.yml
  config/openim-rpc-user.yml
  config/prometheus.yml
  docker-compose.yml
  go.mod
  internal/api/init.go
  internal/api/prometheus_discovery.go
  internal/api/router.go
  internal/msggateway/hub_server.go
  internal/msggateway/init.go
  internal/msgtransfer/init.go
  pkg/common/cmd/auth.go
  pkg/common/cmd/conversation.go
  pkg/common/cmd/friend.go
  pkg/common/cmd/group.go
  pkg/common/cmd/msg.go
  pkg/common/cmd/push.go
  pkg/common/cmd/third.go
  pkg/common/cmd/user.go
  pkg/common/config/config.go
  pkg/common/config/constant.go
  pkg/common/config/load_config_test.go
  pkg/common/discoveryregister/discoveryregister.go
  pkg/common/prommetrics/api.go
  pkg/common/prommetrics/discovery.go
  pkg/common/prommetrics/prommetrics.go
  pkg/common/prommetrics/rpc.go
  pkg/common/prommetrics/transfer.go
  pkg/common/startrpc/start.go
Labels: size/XL

#3061 fix: node exporter image
  .env
Labels: size/XS

#3062 Fix: prometheus config
  config/prometheus.yml
  docker-compose.yml
Labels: size/M

#3066 feat: add backup volume && optimize log print
  .env
  docker-compose.yml
  go.mod
  go.sum
  internal/push/push_handler.go
Labels: size/M

#3076 fix: check error in BatchSetTokenMapByUidPid
  pkg/common/storage/controller/auth.go
Labels: size/S

#3078 fix: DeleteDoc crash
  pkg/common/storage/controller/msg.go
Labels: size/XS

#3072 refactor: improve workflows logic.
  .github/workflows/docker-build-and-release-services-images.yml
  .github/workflows/go-build-test.yml
  .github/workflows/merge-from-milestone.yml
  .github/workflows/publish-docker-image.yml
Labels: size/L

#3082 build: improve workflows contents.
  .github/workflows/docker-build-and-release-services-images.yml
  .github/workflows/go-build-test.yml
  .github/workflows/merge-from-milestone.yml
  .github/workflows/publish-docker-image.yml
Labels: size/L

#3087 fix: the abnormal message has no sending time, causing the SDK to be abnormal
  pkg/common/storage/database/mgo/msg.go
  pkg/common/storage/model/msg.go
Labels: size/L
